export const css = `
.ir-feel{--ink:#f5edf9;--quiet:#b3acc5;position:relative;box-sizing:border-box;width:100%;max-width:740px;min-height:510px;margin:auto;padding:20px;color:var(--ink);font:16px/1.4 system-ui,sans-serif;background:radial-gradient(ellipse at 50% 35%,#34334d 0,#191a29 65%);border:1px solid #555069;border-radius:24px;overflow:hidden;isolation:isolate}
.ir-feel *{box-sizing:border-box}.ir-feel button{font:inherit;color:inherit;-webkit-tap-highlight-color:transparent;touch-action:manipulation;cursor:pointer}
.ir-top{display:flex;justify-content:space-between;align-items:center;gap:12px;font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--quiet)}
.ir-step{color:#e2cef9;font-variant-numeric:tabular-nums}.ir-title{margin:20px 0 5px;text-align:center;font-size:clamp(23px,5.3vw,32px);font-weight:650;letter-spacing:-.04em}
.ir-instruction{min-height:44px;margin:0;text-align:center;color:#c9c3d7;font-size:14px}.ir-stage{position:relative;min-height:226px;display:grid;place-items:center;padding:12px 0}
.ir-watch{width:174px;height:192px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;background:linear-gradient(145deg,#55516966,#282839);border:1px solid #c6b1de66;box-shadow:0 14px 45px #0b091c77;border-radius:24px}
.ir-watch svg{width:116px;height:116px;filter:drop-shadow(0 5px 8px #12102055)}.ir-watch span{color:#ddd5ed;font-size:15px}.ir-count{position:absolute;bottom:0;letter-spacing:12px;color:#9789b6;font-size:14px}
.ir-choices{width:100%;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.ir-choice{position:relative;border:0;padding:0;background:none;min-height:174px;border-radius:20px}
.ir-face{position:absolute;inset:0;border-radius:20px;background:linear-gradient(150deg,#48445e,#2a2a3e);border:1px solid #91849f88;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:12px;box-shadow:0 8px 0 #100f1d,0 12px 22px #0b0a1455;transition:transform 70ms,box-shadow 70ms,border-color 100ms}
.ir-face svg{width:82%;max-width:122px;height:106px;pointer-events:none}.ir-face span{font-size:13px;color:#e0d6e9}.ir-choice:not(:disabled):active .ir-face,.ir-choice.ir-pressed .ir-face{transform:translateY(5px) scale(.965);box-shadow:0 3px 0 #100f1d}
.ir-choice:focus-visible{outline:3px solid #f7d786;outline-offset:5px}.ir-choice:disabled{cursor:default}.ir-choice.ir-restored .ir-face{border-color:#b8edda;background:linear-gradient(145deg,#415d60,#2a374a)}
.ir-choice.ir-other .ir-face{opacity:.58}.ir-mark{position:absolute;top:8px;right:10px;font-size:18px;color:#c4f4db;z-index:3}
.ir-evidence{display:flex;justify-content:center;align-items:center;gap:12px;min-height:100px;padding:8px 0}.ir-evidence figure{margin:0;display:grid;justify-items:center;width:96px}.ir-evidence svg{width:52px;height:52px}.ir-evidence figcaption{font-size:11px;color:#cfc5df}.ir-arrow{color:#b2a3ca;font-size:20px}.ir-feedback{min-height:108px;text-align:center}.ir-feedback p{margin:8px 0;font-size:14px;color:#c9c3d7}
.ir-next{border:1px solid #c7b4df88;background:#dbc3f1;color:#211b2c!important;min-height:48px;padding:11px 25px;border-radius:14px;font-weight:650!important;box-shadow:0 4px 0 #493952;transition:transform 70ms}.ir-next:active{transform:translateY(3px);box-shadow:0 1px 0 #493952}.ir-next:focus-visible{outline:3px solid white;outline-offset:4px}
.ir-mosaic{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin-top:10px;padding-top:16px;border-top:1px solid #8d7da033}.ir-memory{height:51px;display:grid;place-items:center;background:#242235;border:1px solid #6f657a55;border-radius:10px;color:#847294;font-size:12px}.ir-memory svg{width:34px;height:34px}.ir-memory.ir-filled{background:#454051;border-color:#9b8ba6}
.ir-mosaic-label{text-align:center;color:#a99bb7;font-size:11px;margin-top:9px;letter-spacing:.07em}.ir-burst{position:absolute;inset:0;pointer-events:none;z-index:6}.ir-spark{position:absolute;width:6px;height:6px;background:#ead9ff;border-radius:2px}.ir-final .ir-stage{min-height:250px}.ir-final .ir-mosaic{width:100%;grid-template-columns:repeat(3,1fr);border:0;margin:0;padding:10px;gap:12px}.ir-final .ir-memory{height:92px;box-shadow:0 5px 0 #171324}.ir-final .ir-memory svg{width:64px;height:64px}.ir-final .ir-feedback{min-height:40px}.ir-seal{font-size:70px;line-height:1;color:#e3cdff;text-shadow:0 0 35px #b992c088}.ir-finale{position:absolute;inset:0;pointer-events:none;background:linear-gradient(110deg,transparent 35%,#fbe9ff33 50%,transparent 65%)}
.ir-paused:after{content:'Paused';position:absolute;inset:0;display:grid;place-items:center;background:#191929e8;color:#e4d4f0;z-index:10;font-size:26px;letter-spacing:.03em}.ir-reduced .ir-face,.ir-reduced .ir-next{transition:none}.ir-reduced .ir-choice:active .ir-face{transform:none;outline:2px solid #f4dfb2}
@media(max-width:420px){.ir-feel{padding:16px 12px;border-radius:18px;min-height:486px}.ir-title{margin-top:16px}.ir-choices{gap:8px}.ir-choice{min-height:155px}.ir-face{border-radius:15px;gap:6px}.ir-face svg{height:92px}.ir-stage{min-height:210px}.ir-memory{height:43px}.ir-feedback{min-height:106px}}
@media(prefers-reduced-motion:reduce){.ir-feel .ir-face,.ir-feel .ir-next{transition:none}.ir-choice:active .ir-face{transform:none;outline:2px solid #f4dfb2}}
`;
