using System;
using System.Collections.Generic;

namespace ConditioningControlPanel.Services.Arcademy;

/// <summary>The neutral display tables the Arcademy init projects (WPF ArcademyHostService.cs:1740-3366,
/// copied verbatim: the keys are the contract, a mod skins values only).</summary>
internal static class ArcademyLexicon
{
    /// <summary>
    /// The neutral display-string table. Internal keys are FIXED (GROUND-RULES §3) and a mod skins
    /// values only, never keys, by shipping <c>resources/arcademy/lexicon.json</c>. Keys absent from
    /// the mod file keep the neutral default, so a partial mod table is legal.
    /// </summary>
    internal static readonly Dictionary<string, string> NeutralLexicon = new(StringComparer.Ordinal)
    {
        // ---- container / the day -------------------------------------------------------
        ["arcademy"] = "The Arcademy",
        ["semester"] = "Semester",
        ["timetable"] = "Timetable",
        ["class"] = "Class",
        ["classes"] = "Classes",
        ["homeroom"] = "Homeroom",
        ["period"] = "Period",
        ["report_card"] = "Report Card",
        // The one internal key for an audio-only-suspended class (SYNTHESIS-NOTES #8).
        ["class_suspended"] = "Class Suspended",
        ["class_placeholder"] = "Class Placeholder",
        // ---- performance ---------------------------------------------------------------
        ["grade"] = "Grade",
        ["grade_s"] = "S",
        ["grade_a"] = "A",
        ["grade_b"] = "B",
        ["grade_c"] = "C",
        ["grade_pass"] = "PASS",
        ["grade_tier"] = "Year",
        // ONE row per tier (SYNTHESIS-NOTES #1) - never invented per game.
        ["grade_tier_1"] = "Year 1",
        ["grade_tier_2"] = "Year 2",
        ["grade_tier_3"] = "Year 3",
        ["grade_tier_4"] = "Year 4",
        // The one letter with punctuation in it. 'grade_s+' is not a key shape a lexicon row
        // (or a mod table) can carry, so core/lexicon.js spells it out and so does this.
        ["grade_splus"] = "S+",
        ["attendance"] = "Attendance",
        ["perfect_attendance"] = "Perfect Attendance",
        // ---- the Prize Counter (economy, 2026-08-26) -----------------------------------
        // Every row here is the front desk talking: warm, a bit scruffy, never a form letter.
        // These keys are the ONES THE PAGE ACTUALLY ASKS FOR: core/lexicon.js carries the same
        // set as its offline fallback and shell/lever.js + shell/prizecounter.js look them up
        // by exactly these names. A row nothing calls is a row a mod would re-voice for
        // nothing, so the list is kept to what is consumed and the harness checks both ways.
        // ---- the door on the west wall
        ["campus_room_prizes"] = "Prize Counter",
        ["campus_prizes_status"] = "Open late",
        ["campus_desc_prizes"] = "Tickets on the shelf, tokens in the case. Somebody is always restocking.",
        // ---- the two currencies, as they read on a chip
        ["wallet_tickets"] = "Tickets",
        ["wallet_tokens"] = "Tokens",
        // ---- the counter itself
        ["prize_counter_title"] = "Prize Counter",
        ["prize_counter_sub"] = "Tickets on the shelf, tokens in the case",
        ["prize_shelf"] = "Ticket Shelf",
        ["prize_shelf_hint"] = "Every graded class pays tickets. This is where they go.",
        ["prize_case"] = "Token Case",
        ["prize_case_hint"] = "Tokens only. Your first S of the day drops one in the tray.",
        ["prize_you_have"] = "On you",
        ["prize_owned"] = "Yours",
        ["prize_held"] = "Holding",
        ["prize_buy"] = "Trade",
        ["prize_soon"] = "Arriving soon",
        ["prize_wait"] = "Asking the counter",
        // What the counter says back. The refusals line up one for one with the reason strings on
        // `wallet-result` (unknown / poor / owned / full / locked, plus `offline` and `busy` since
        // the wallet moved to the account); the last two are what the page says on its own when no
        // answer came back at all.
        ["prize_bought"] = "Wrapped up and yours.",
        ["prize_poor"] = "Not quite enough on you for that one yet.",
        ["prize_owned_msg"] = "You have that one already.",
        ["prize_full"] = "Your pockets are full of those. Use one first.",
        ["prize_locked_msg"] = "That one stays in the case for now.",
        ["prize_unknown"] = "The counter does not know that one. Odd.",
        // The shared wallet's two new refusals. The till is on the account now, so a purchase with
        // no line out is a thing the counter cannot do rather than a thing you cannot afford, and
        // the account lock is another of your own devices at the same drawer. Both are worded so
        // they never sound like a scolding and never mention a network.
        ["prize_offline"] = "The counter cannot reach the bank right now. Nothing was charged.",
        ["prize_busy"] = "Somebody is already at the drawer. Give it a second and ask again.",
        ["prize_quiet"] = "The counter went quiet on that one. Try again in a moment.",
        ["prize_empty"] = "Shelf is bare tonight. Come back when the truck has been.",
        // THE ALMOST and THE CHARGE-HOLD (shell/prizecounter.js, wave 0828). `prize_short` is a
        // bare word: the page builds "Almost, 20 short" by concatenation the way it already builds
        // "Holding 2/3", so no translated string has a number baked into it.
        ["pc_verb_almost"] = "Almost",
        ["prize_short"] = "short",
        ["prize_hold_hint"] = "Hold it down to trade that one.",
        ["prize_hold_aria"] = "Hold to trade",
        // Tonight's hot room, painted from the seeded draw `init` already handed down.
        ["prize_payday_label"] = "Hot room tonight",
        ["prize_payday_2"] = "is paying double",
        ["prize_payday_5"] = "is paying five times over",
        // THE ANTECHAMBER (shell/prizebooth.js). The painted booth you walk up to before
        // the shelf opens: the lit window, the tray on the sill, and what a counter with
        // its shutter down says. `prize_closed` is one word because it is stencilled on
        // the shutter, not spoken.
        ["prize_booth_window"] = "The service window",
        ["prize_booth_tray"] = "The ticket tray",
        ["prize_closed"] = "Closed",
        ["prize_closed_line"] = "The shutter is down and the sign above it has been switched off at the wall.",
        ["prize_no_payday"] = "No room is paying over the odds tonight. Every graded class still pays tickets.",
        ["settings_classes_head"] = "Classes",
        ["campus_desc_prizes_shut"] = "Shutter down over the window, parcels still stacked behind it. Back another night.",
        // The eight rows on the shelf. Names and blurbs both, so a page with a partial mod
        // table still reads (the catalog also ships the neutral English on the wire). Keyed
        // EXACTLY as ArcademyEconomy.Catalog's NameKey/BlurbKey - a missing row here is a blank
        // label on the shelf, so the harness checks the two lists against each other.
        ["prize_id_frame_gold"] = "Gold Pinstripe Frame",
        ["prize_id_frame_gold_blurb"] = "A thin gold pinstripe around your ID photo, for being seen.",
        ["prize_id_frame_navy"] = "Navy Varsity Frame",
        ["prize_id_frame_navy_blurb"] = "Deep navy with a varsity edge, like the old team photos.",
        ["prize_confetti_stamp"] = "Confetti Stamp",
        ["prize_confetti_stamp_blurb"] = "Your stamp lands in a little burst of paper now, every time.",
        ["prize_late_slip"] = "Tardy Slip",
        ["prize_late_slip_blurb"] = "Hand one in and the night you missed is filed as excused. Two on the desk, no more.",
        ["prize_honors_lever"] = "Honors Lever",
        ["prize_honors_lever_blurb"] = "Unbolts the third notch, which is where the S+ nights live.",
        ["prize_free_swim_key"] = "Free Swim Key",
        ["prize_free_swim_key_blurb"] = "Opens Free Swim on every room you are in, card or no card.",
        ["prize_de_5x5"] = "The Wide Board",
        ["prize_de_5x5_blurb"] = "Adds the roomy 5x5 board to The Deep End, for a gentler soak.",
        ["prize_jukebox"] = "Jukebox",
        ["prize_jukebox_blurb"] = "The slot is dressed and the case is empty. It is on the truck.",
        // THE RESTOCK (2026-08-26) plus THE LOCKER's three outfits (2026-08-28). Fourteen more
        // rows over three waves - the shelf projection hides anything above
        // ArcademyEconomy.CurrentWave, but the LEXICON carries all fourteen regardless: a lexicon
        // row costs nothing until something asks for it, and shipping the next wave should be one
        // const bump, not a second trip through nine language files.
        // Copy is the contract's, verbatim. The restock's own rows all sit inside the 96-char
        // bar; the lab coat's blurb runs to 106 because that is the line the owner signed off,
        // and nothing measures a blurb - the card wraps it.
        ["prize_away_colors"] = "AWAY COLORS",
        ["prize_away_colors_blurb"] = "Alternate kit for your little walker. Same you, sharper stripes.",
        ["prize_sparkler_steps"] = "SPARKLER STEPS",
        ["prize_sparkler_steps_blurb"] = "A trail of little sparks wherever you walk. The janitor has given up complaining.",
        ["prize_brass_bell"] = "THE BRASS BELL",
        ["prize_brass_bell_blurb"] = "The old bell from the storage room takes over. Rings a little warmer than the new one.",
        ["prize_emi_desk_toy"] = "EMI'S DESK TOY",
        ["prize_emi_desk_toy_blurb"] = "A little something for her desk. She'll fidget with it and pretend she doesn't love it.",
        ["prize_poster_drop_1"] = "POSTER DROP NO 1",
        ["prize_poster_drop_1_blurb"] = "Fresh prints for the corkboard, motivational in a way we can't quite explain.",
        ["prize_pa_pack"] = "PA ANNOUNCER",
        ["prize_pa_pack_blurb"] = "The morning announcements get a voice. She mostly reads the schedule, mostly.",
        ["prize_theme_drone"] = "DRONE PROTOCOL",
        ["prize_theme_drone_blurb"] = "Somebody left a strange cartridge in the AV room and now the campus runs green. We like it.",
        ["prize_emi_labcoat"] = "LAB COAT",
        ["prize_emi_labcoat_blurb"] = "White coat, pocket protector, the clipboard she never writes on. She looks like she is about to grade you.",
        ["prize_emi_cheer"] = "CHEER UNIFORM",
        ["prize_emi_cheer_blurb"] = "Navy and pink, pleats and all. The pom-poms are not optional and neither is the chant.",
        ["prize_emi_swim"] = "SWIM TEAM",
        ["prize_emi_swim_blurb"] = "Lane four, goggles up. Free Swim was always going to end up here.",
        ["prize_ghost_walk"] = "GHOST WALK",
        ["prize_ghost_walk_blurb"] = "Your walker goes see-through with a soft afterimage. Spooky in a fun way, we checked.",
        ["prize_theme_snowday"] = "SNOW DAY",
        ["prize_theme_snowday_blurb"] = "Frost on the windows, snow in the courtyard, everything soft and blue. Classes run anyway.",
        ["prize_emi_varsity"] = "EMI: VARSITY JACKET",
        ["prize_emi_varsity_blurb"] = "She found it in lost and found and it fits perfectly. Every one of her poses, re-dressed.",
        ["prize_tube_midnight"] = "TUBE GLASS: MIDNIGHT",
        ["prize_tube_midnight_blurb"] = "A darker glass for the tube back home. It ships to the whole app, not just the school.",
        // ---- the Extra Credit lever ----------------------------------------------------
        // shell/lever.js owns the words on BOTH class-start surfaces (the door card and the
        // painted room's apron), so every rung is one key and one locked line, no more.
        ["lever_title"] = "Extra Credit",
        ["lever_standard"] = "Standard",
        ["lever_extra"] = "Extra Credit",
        ["lever_honors"] = "Honors",
        ["lever_standard_hint"] = "Play it straight. Tickets pay the usual.",
        ["lever_extra_hint"] = "Half again the tickets, and it asks more of you.",
        ["lever_honors_hint"] = "Double tickets, and the only road to an S plus.",
        ["lever_extra_locked"] = "Earn an A on anything and this one wakes up.",
        ["lever_honors_locked"] = "The counter sells this one for a token.",
        // ---- the till, as it reads after a class ---------------------------------------
        // The payday's own words live on the counter (prize_payday_*); what lands here is the
        // report card's payout beat and the one purchase a player never watches being spent.
        ["free_swim_key_hint"] = "Your key opens this one for a practice run. Nothing counts, nothing costs.",
        ["payout_tickets"] = "Tickets",
        ["payout_token_minted"] = "A token dropped in the tray. That is your one for today.",
        ["late_slip_used"] = "A tardy slip was handed in for you. Your streak never noticed.",
        // THE ONE SMALL BUTTON under the jeopardy line (Deck V, the Rake). `{name}` is filled
        // from the catalog row itself, so a mod that renames the slip renames the offer too.
        ["rake_slip_offer"] = "The counter sells a {name}.",
        // Reserved vocabulary: designed for, not built in v1 (GROUND-RULES §3).
        ["detention"] = "Detention",
        ["diploma"] = "Diploma",
        ["exam"] = "Exam",
        ["gpa"] = "GPA",
        ["honor_roll"] = "Honor Roll",
        // ---- family chips (timetable) --------------------------------------------------
        ["family_word"] = "word",
        ["family_memory"] = "memory",
        ["family_search"] = "search",
        ["family_tracking"] = "tracking",
        ["family_reflex"] = "reflex",
        ["family_comfort"] = "comfort",
        // ---- verbs / chrome ------------------------------------------------------------
        ["peek"] = "Peek",
        ["peek_hint"] = "Hold to peek. Using it caps this class at A.",
        ["settings"] = "Settings",
        // The scoped (mid-class) settings page: knobs are a startClass snapshot.
        ["applies_next_class"] = "Class option changes take effect next class.",
        ["back"] = "Back",
        ["begin_class"] = "Begin",
        ["leave_class"] = "Leave class",
        // ---- the exits (shell/exits.js: the campus pill + its confirm) ------------------
        // Every value stays well under MergeModTable's 96-char cap so a mod can re-voice
        // all of them (trap 26 - the long ic_* rows are the cautionary tale).
        ["back_to_campus"] = "Back to campus",
        ["leave_confirm_title"] = "Head back to campus?",
        ["leave_confirm_body"] = "This class is not finished. Nothing from it is saved.",
        ["leave_confirm_stay"] = "Stay in class",
        ["replay_board"] = "Flip the board again",
        ["share"] = "Copy share card",
        ["shared"] = "Copied to clipboard",
        // The SLIP (shell/sharecard.js). The drawn card is unskinnable on purpose - a
        // paste must never name the player's mod - but its chrome is ordinary chrome.
        ["share_image"] = "Share report card",
        ["share_add_name"] = "Add my name",
        ["share_saved"] = "Report card saved",
        ["share_copied"] = "Report card copied",
        ["share_shared"] = "Report card shared",
        ["share_unavailable"] = "Sharing is not available here",
        ["done"] = "Done",
        ["retake"] = "Retake",
        ["xp"] = "XP",
        ["streak"] = "Streak",
        // ---- share marks (Daily Trigger's emoji grid) ----------------------------------
        // Escaped rather than pasted so the table survives any re-encoding of this file.
        ["share_hit"] = "\U0001F497",   // pink heart
        ["share_near"] = "\U0001F300",  // cyclone
        ["share_miss"] = "\U0001F5A4",  // black heart
        // ---- per-game titles (game_<key>) ----------------------------------------------
        // The shell renders board rows / report rows / settings groups through
        // t('game_' + key, <module title>), so a mod can only re-title a class if the
        // key exists here (MergeModTable only merges keys the default table declares).
        ["game_daily_trigger"] = "Daily Trigger",
        ["game_deja_vu"] = "Deja Vu",
        ["game_impulse_control"] = "Impulse Control",
        ["game_lost_and_found"] = "Lost & Found",
        ["game_the_deep_end"] = "The Deep End",
        // Semester II ghost labels on the campus plan (behind the tape). Same
        // game_<key> convention the registry will use once those classes ship.
        ["game_misdirection"] = "Misdirection",
        ["game_instant_recall"] = "Instant Recall",
        ["game_echo"] = "Echo",
        // ---- campus (the Direction A hub, shell/campus.js) ------------------------------
        // Room names are diegetic and FIXED to their game - a game always lives in its
        // room. Every value must stay under MergeModTable's 96-char skin cap.
        ["student"] = "Student",
        ["campus_room_daily_trigger"] = "Homeroom",
        ["campus_room_deja_vu"] = "Memory Lab",
        ["campus_room_impulse_control"] = "Discipline Hall",
        ["campus_room_lost_and_found"] = "Lost & Found",
        ["campus_room_the_deep_end"] = "The Pool",
        ["campus_desc_daily_trigger"] = "One word, six chances. The whole school sits the same word today.",
        ["campus_desc_deja_vu"] = "Pairs that move when you blink. The board settles only when you stop looking.",
        ["campus_desc_impulse_control"] = "Hands on the desk. Move only when told - the room will lie to you.",
        ["campus_desc_lost_and_found"] = "Things went missing in a wall of moving pictures. Find them before they move again.",
        ["campus_desc_the_deep_end"] = "Sink tile into tile. The deeper you go, the harder the board is to read.",
        ["campus_records"] = "Records",
        ["campus_desc_records"] = "Report card, attendance ledger, grades. Your whole term, in ink.",
        ["campus_registrar"] = "Front Office",
        ["campus_desc_registrar"] = "Every setting is a form. Every consent, a waiver with a stamp.",
        ["campus_entrance_hall"] = "Entrance Hall",
        ["campus_desc_entrance"] = "The notice board carries announcements. The trophy case waits for your diplomas.",
        ["campus_notice_board"] = "Notice Board",
        ["campus_trophy_case"] = "Trophy Case",
        // THE TIME CAPSULE (Resources/web/arcademy/shell/capsule.js). The plaque
        // line is TWO clause rows joined with one space in the page: the whole
        // sentence is 102 characters and MergeModTable drops any mod string over
        // 96, so a single row could never be re-voiced (trap 26).
        ["campus_desc_trophy"] = "One exhibit under glass. The school keeps its own first night in here.",
        ["capsule_on_view"] = "On view",
        ["capsule_title"] = "Time Capsule",
        ["capsule_line_2026_02_a"] = "The first dashboard. February 2026.",
        ["capsule_line_2026_02_b"] = "Everything was pink and the DROP button was the size of a doormat.",
        ["capsule_footer"] = "Sealed by the Registrar. Opened at thirty nights.",
        ["capsule_sealed_tag"] = "opens at 30 nights",
        ["capsule_sealed_hint"] = "The case is wrapped and taped. The tag has a number on it.",
        ["campus_admissions"] = "Admissions",
        ["campus_bell_tower"] = "Bell Tower",
        ["campus_main_gate"] = "Main Gate",
        ["campus_main_hall"] = "Main Hall",
        ["campus_the_quad"] = "The Quad",
        ["campus_front_path"] = "Front Path",

        // CAMPUS PRESENCE - "The Student Body" (planning/arcademy/PRESENCE.md,
        // shell/ghosts.js). Six rows and not one more: four BLIPS a ghost may
        // say to another ghost, the busyness chip's label, and the layer's own
        // name. The bubbles are 1-4 characters BY LAW - a mod re-voices the
        // greeting without ever being able to put a sentence over a stranger's
        // head, and every one is far under the 96-char MergeModTable cap.
        ["presence_student_body"] = "Student Body",
        ["presence_bubble_hi"] = "hihi",
        ["presence_bubble_dots"] = "...",
        ["presence_bubble_wave_a"] = "o/",
        ["presence_bubble_wave_b"] = "\\o",
        ["presence_here_tonight"] = "here tonight",
        // ...and the CONSENT ROW (P3, the settings page's global tier). Every option says what
        // it shows PUBLICLY, because the player is agreeing to a specific thing and a rung named
        // only "Anonymous" is not one. All well under the 96-char MergeModTable cap (trap 26), so
        // a mod may re-word the consent copy in its own voice - which is why it lives here at all.
        ["presence_share_label"] = "Show yourself on campus",
        ["presence_share_hint"] = "Your last 24 hours replay as a ghost. Room head counts include you at every rung.",
        ["presence_share_off"] = "Off - room head counts only",
        ["presence_share_anon"] = "Anonymous - a ghost with no name or picture",
        ["presence_share_username"] = "Username - your display name over the ghost",
        ["presence_share_discord"] = "Discord - your display name and profile picture",
        ["presence_share_discord_note"] = "Discord needs a linked account. Without one the school shows your name instead.",
        ["campus_east_wing"] = "East Wing",
        ["campus_west_wing"] = "West Wing",
        ["campus_desc_east"] = "You can hear hammering behind the tape.",
        ["campus_desc_west"] = "The boards are older here.",
        ["campus_sealed"] = "Sealed",
        ["campus_opens_semester_2"] = "Opens Semester II",
        ["campus_semester_3"] = "Semester III",
        ["campus_in_session"] = "In Session",
        ["campus_not_tonight"] = "Not tonight",
        ["campus_dev_pass"] = "Dev pass · Begin",
        ["campus_dev_pass_hint"] = "Dev pass: off tonight's board, graded anyway.",
        ["campus_next_bell"] = "Next Bell",
        ["campus_step_inside"] = "Step inside",
        ["campus_xp_first"] = "First pass of the day pays XP.",
        ["campus_xp_retake"] = "Retakes pay no XP - pride only.",
        ["campus_hint"] = "Hover a room - click to step inside.",
        ["campus_hint_touch"] = "Tap a room to step inside.",
        ["campus_night_sessions"] = "Night Sessions",
        ["campus_rm"] = "RM",
        // ---- punch cards: the campus door (PUNCHCARD.md §2.3) --------------------------
        ["campus_unlocked"] = "Unlocked - open every night",
        ["campus_unlocked_sign"] = "Open",
        ["campus_unlocked_hint"] = "Card complete. This room opens every night, board or no board.",
        // ---- punch cards: the card + its ceremony (PUNCHCARD.md §4) ---------------------
        // Every value stays under MergeModTable's 96-char cap so a mod can re-voice the
        // whole mechanic (trap 26). A line that needs more room becomes a second card.
        ["punchcard"] = "Stamp Card",
        ["punchcard_holes"] = "{have} of {need}",
        // The card face's LIVE TEXT ZONE: the tight count, the MASTERED label, and the
        // eight rotating flavour lines (shell/punchcard.js PHRASE_LEX - copy the values,
        // do not re-word them). One row per line so a mod can re-voice them one at a time.
        ["punchcard_count"] = "{have}/{need}",
        ["punchcard_mastered"] = "Mastered",
        ["punchcard_phrase_1"] = "Attendance is a habit. Habits are the only thing this school grades.",
        ["punchcard_phrase_2"] = "The card does not ask how well you did. Only that you came.",
        ["punchcard_phrase_3"] = "Ten stamps and the room is yours. Nine of them are patience.",
        ["punchcard_phrase_4"] = "Nobody has ever filled a card in one night. You will not be the first.",
        ["punchcard_phrase_5"] = "The register is already open. Your name has been on it a while.",
        ["punchcard_phrase_6"] = "One stamp a night. The school is in no hurry whatsoever.",
        ["punchcard_phrase_7"] = "Progress in here is measured in ink, never in effort.",
        ["punchcard_phrase_8"] = "You will stop noticing that you collect these. That is the intention.",
        ["punchcard_stamped"] = "Stamped for today.",
        // THE S DOUBLE (owner ruling 2026-08-23) - the second hole an S day buys says so.
        ["punchcard_stamped_s"] = "Top marks. The card takes a second stamp.",
        ["punchcard_next_hole"] = "Come back tomorrow for the next stamp.",
        ["punchcard_unlocked_chip"] = "Unlocked",
        ["punchcard_unlocked_title"] = "Assignment complete",
        ["punchcard_unlocked_line"] = "This room is now open even when the course is not in session.",
        // THE DISCORD LINE (the Activity wave, 2026-08-28). `{cmd}` is filled by
        // the page from games/registry.js DISCORD_COMMAND, never by the host.
        ["punchcard_unlocked_discord"] = "Even in Discord: type {cmd} in the CCP server to play it anytime.",
        ["launch_card_locked"] = "That card is not complete yet. Fill it first.",
        ["enroll_kicker"] = "Enrollment",
        ["enroll_next"] = "Next",
        ["enroll_begin"] = "Begin class",
        ["enroll_card_line"] = "Every class carries a stamp card. Ten stamps, one a night.",
        ["enroll_tutorial_line"] = "One stamp for finishing your first class.",
        ["enroll_house_line"] = "And one on the house. Welcome to the class.",
        // DAY ONE IS THREE (owner ruling 2026-08-23) - the third hole says why.
        ["enroll_signon_line"] = "And one for signing on. The card starts warm.",
        // ---- punch cards: the Records Office (PUNCHCARD.md §6) --------------------------
        ["records_kicker"] = "Records Office",
        ["records_lede"] = "Ten cards, ten stamps each. The wall keeps them whether you come back or not.",
        ["records_enrolled"] = "Enrolled",
        ["records_enrolled_on"] = "Enrolled",
        ["records_unlocked_on"] = "Unlocked",
        ["records_holes_punched"] = "Stamps earned",
        ["records_holes_left"] = "Stamps left",
        ["records_stamps"] = "Daily stamps",
        ["records_no_stamps"] = "No daily stamps yet.",
        ["records_not_enrolled"] = "Not enrolled - attend the class",
        ["records_enroll_hint"] = "The first graded finish opens the card and earns three stamps.",
        ["records_house_note"] = "Day one is three stamps: finishing, on the house, signing on.",
        ["records_flip_hint"] = "Pick a card to read its stamps.",
        ["records_spot_close"] = "Close",
        ["records_empty_wall"] = "Nothing on the wall yet. Attend a class and the first card gets pinned.",
        // ---- the office as a ROOM (shell/recordsroom.js, 0825) --------------------------
        // Four things you can touch in the painted office, plus the chrome of its two
        // close-ups. "records_book" is deliberate and so is its value: the other word for
        // that volume is a register word, and the register is barred from every
        // user-facing string in this school.
        ["records_tray"] = "The card tray",
        ["records_board"] = "The noticeboard",
        ["records_book"] = "The book",
        ["records_storeroom"] = "The storeroom",
        ["records_fresh"] = "New",
        ["records_close_panel"] = "Put the cards back",
        ["records_book_next"] = "Next page",
        ["records_book_prev"] = "Back a page",
        ["records_book_ch_school"] = "The Arcademy",
        ["records_book_ch_rules"] = "House rules",
        ["records_book_ch_tips"] = "Tips",
        // ---- enrollment flavour, per class (PUNCHCARD.md §4) ----------------------------
        // Mirrors shell/enrollment.js's ENROLL_LEX verbatim - copy the values, do not
        // re-word them (the IC_LEX rule). Three cards per class, in the campus voice:
        // what the room is for, what it makes you do, what it is doing to you.
        ["enroll_daily_trigger_1"] = "Homeroom goes first, and the whole lesson is one word long.",
        ["enroll_daily_trigger_2"] = "Everyone in the school sits the same word tonight. Six chances, no help.",
        ["enroll_daily_trigger_3"] = "Say it enough mornings and you stop deciding what it means.",
        ["enroll_lost_and_found_1"] = "Things go missing here constantly. Nobody files a report.",
        ["enroll_lost_and_found_2"] = "A wall of moving pictures, and one of them is yours. Find it first.",
        ["enroll_lost_and_found_3"] = "This trains the part of you that keeps looking after looking stops working.",
        ["enroll_deja_vu_1"] = "The Memory Lab studies what happens to a board you have already learned.",
        ["enroll_deja_vu_2"] = "Match the pairs. The pairs move when you blink. Both of those are the work.",
        ["enroll_deja_vu_3"] = "You will feel certain and be wrong. We would rather you stopped noticing.",
        ["enroll_impulse_control_1"] = "Discipline Hall exists because you reach for things. Every time.",
        ["enroll_impulse_control_2"] = "Hands on the desk. Pop when told, hold when told. The room may lie.",
        ["enroll_impulse_control_3"] = "A held hand is worth more here than a fast one. Learn which order was real.",
        ["enroll_the_deep_end_1"] = "The Pool has a shallow end that nobody uses. This class is not held there.",
        ["enroll_the_deep_end_2"] = "Sink tile into tile. Every merge takes you further from the surface.",
        ["enroll_the_deep_end_3"] = "The deeper the board, the harder it is to read. That is the subject.",
        ["enroll_misdirection_1"] = "The Parlour teaches what a room does to your attention when it wants it.",
        ["enroll_misdirection_2"] = "Keep your eyes on the one that matters. It will not make that easy.",
        ["enroll_misdirection_3"] = "You will be shown the trick and lose anyway. Then shown it again.",
        ["enroll_echo_1"] = "The Music Room does not teach music. It teaches you to hold a line that somebody else set.",
        ["enroll_echo_2"] = "It plays a phrase. You play it back. Then it adds one and asks again.",
        ["enroll_echo_3"] = "Nobody passes by remembering harder. They pass by stopping the arguing.",
        ["enroll_instant_recall_1"] = "The Lecture Hall never announces the test. That is the design of the room.",
        ["enroll_instant_recall_2"] = "Watch the hour, answer for it after. You will not hear the question coming.",
        ["enroll_instant_recall_3"] = "Attention that only arrives when asked is not attention. This corrects that.",
        ["enroll_anomaly_1"] = "The Darkroom is where the school checks that you still notice a difference.",
        ["enroll_anomaly_2"] = "Everything on the grid matches. One thing does not. Find it before it moves.",
        ["enroll_anomaly_3"] = "The differences get smaller every year. You are expected to keep up.",
        ["enroll_composure_1"] = "The Studio grades one thing: can you finish a picture while interfered with.",
        ["enroll_composure_2"] = "Slide the tiles back into order while the room blurs what order was.",
        ["enroll_composure_3"] = "Nothing in here is fast. Composure is the subject and it cannot be rushed.",
        // ---- FIRST BELL, the once-ever opening (Resources/web/arcademy/vn/lex.js) -------
        // Mirrors VN_LEX row for row. The two PAPERS are stored as CLAUSE rows and joined
        // with a single space by vn/index.js paragraph(): every row therefore stays under
        // the 96-character mod-skin cap, which a whole paragraph could never do (a value
        // over 96 is dropped by MergeModTable and can never be re-voiced - see trap 26).
        // Splitting is a storage decision; the joined text is the owner-vetted paragraph
        // byte for byte and no word of it may be edited here.
        ["vn_skip"] = "Hold to skip",
        ["vn_tap"] = "Tap to continue",
        ["vn_s01_cap1"] = "The gates open at dusk and classes run every night, holidays included.",
        ["vn_s01_cap2"] = "Your enrollment went through last week. First bell rings in the main hall.",
        ["vn_p1_title"] = "WELCOME TO THE ARCADEMY",
        ["vn_p1_a"] = "Hi! You're all set.",
        ["vn_p1_b"] = "Tonight's four classes go up on the big board over this desk at first bell,",
        ["vn_p1_c"] = "homeroom first and then whatever order you feel like.",
        ["vn_p1_d"] = "You don't need to bring anything, every room already has its own machine",
        ["vn_p1_e"] = "and the machine has everything.",
        ["vn_p1_f"] = "Nobody's at the desk after dark, so if a cabinet acts up,",
        ["vn_p1_g"] = "give it one gentle kick and leave us a note in the tray.",
        ["vn_p1_h"] = "Have a great first night!",
        ["vn_s03_cap"] = "Homeroom is room 101, first door on your left, just follow the footprint decals.",
        ["vn_p2_title"] = "NICE ONE!",
        ["vn_p2_a"] = "That's your first stamp of the year.",
        ["vn_p2_b"] = "Three classes are still lit on the board if you're up for another,",
        ["vn_p2_c"] = "and if you're done for tonight that's fine too,",
        ["vn_p2_d"] = "the board deals fresh at dusk either way.",
        ["vn_p2_e"] = "Replay anything as much as you like,",
        ["vn_p2_f"] = "the card just takes one stamp per class a night.",
        ["vn_p2_g"] = "Spare tokens can go in the fountain, it's supposed to be good luck,",
        ["vn_p2_h"] = "or at least that's what everybody writes in the yearbook.",
        ["vn_sign"] = "- the front desk",
        // ---- per-game rows (Semester 1) -------------------------------------------------
        // Keys that are not prefixed by a game: the shell and more than one class render
        // them (Daily Trigger mints them today).
        ["absorbed"] = "ABSORBED",
        ["detention_so_close"] = "One letter. It kept the last one for itself.",
        ["mark_hit"] = "right letter, right place",
        ["mark_miss"] = "not in the word",
        ["mark_near"] = "right letter, wrong place",
        ["revision_day"] = "Revision",
        ["revision_day_hint"] = "Revision: you have met this one before.",
        // ---- Daily Trigger (games/daily-trigger) --------------------------------------
        ["dt_absorb_jackpot"] = "It sticks. Deeper than usual.",
        ["dt_absorbed_line"] = "Absorbed. It rides with you through the rest of today.",
        ["dt_cell_empty"] = "empty",
        ["dt_commit"] = "COMMIT ROW",
        ["dt_detention_stamp"] = "DETENTION",
        ["dt_enter"] = "ENTER",
        ["dt_gold_chip"] = "GOLD \u2728",
        ["dt_gold_solved"] = "Gilded: solved on a gold letter day.",
        ["dt_hard_chip"] = "HARD",
        ["dt_hard_hit"] = "Hard mode: keep the revealed letters in place",
        ["dt_hard_mode"] = "Hard mode",
        ["dt_hard_mode_hint"] = "Every revealed letter must be reused. Forced on at Year 4.",
        ["dt_hard_near"] = "Hard mode: use every revealed letter",
        ["dt_keyboard_layout"] = "Keyboard layout",
        ["dt_keyboard_layout_hint"] = "Auto follows the layout your system reports.",
        ["dt_ladder"] = "Ladder",
        ["dt_lesson_header"] = "Today's Lesson",
        ["dt_near_miss"] = "One letter away",
        ["dt_not_a_word"] = "Not in the word list",
        ["dt_not_enough"] = "Not enough letters",
        ["dt_phrase_chip"] = "PHRASE",
        ["dt_phrase_hint"] = "Two words today. The gap is free.",
        ["dt_retake"] = "Retake",
        ["dt_skip"] = "Tap to continue",
        ["dt_study_hint"] = "Study hint: one letter is already in place. It costs you nothing.",
        ["dt_theme_word"] = "One of your own words.",
        ["dt_twist_telegraph"] = "The whispers are real words - just not today's.",
        ["dt_type_to_guess"] = "Type to guess",
        ["dt_type_to_guess_hint"] = "Use the physical keyboard instead of tapping the on-screen one.",
        // the chalk whispers (Unreliable Label): the TEXT lies, the glyphs are the truth
        ["dt_whisper_1"] = "Forget the pink ones.",
        ["dt_whisper_2"] = "It was never in row two.",
        ["dt_whisper_3"] = "You already typed it.",
        ["dt_whisper_4"] = "The stars are lying, not me.",
        // ---- Deja Vu (games/deja-vu) --------------------------------------------------
        ["dv_bell"] = "The bell. Class over.",
        ["dv_boards"] = "boards",
        ["dv_last_call"] = "Last ten seconds.",
        ["dv_called_it"] = "You called the lie.",
        ["dv_card"] = "Card",
        ["dv_clear"] = "Board clear.",
        ["dv_cram_assist"] = "Cram Assist",
        ["dv_cram_hint"] = "Hold to re-study the board. Using it caps this class at A.",
        ["dv_cram_key"] = "Cram Assist key",
        ["dv_cram_on"] = "Cramming.",
        ["dv_cram_ready"] = "Cram Assist ready. Hold it - it caps this class at A.",
        ["dv_deal_hint"] = "Dealing the board.",
        ["dv_drift_hint"] = "A whole line is sliding.",
        ["dv_endgame"] = "Last pair.",
        ["dv_jackpot"] = "JACKPOT",
        ["dv_matched_loops"] = "Matched pairs",
        ["dv_near_miss"] = "SO CLOSE",
        ["dv_peek_hold"] = "Card hold length",
        ["dv_rack_label"] = "Specimens",
        // the deja re-deal (House Rules Deck III, the native signature)
        ["dv_redeal_stamp"] = "DEJA VU",
        ["dv_redeal_hint"] = "One of those was a lie.",
        ["dv_redeal_gift"] = "The machine blinked.",
        ["dv_peek_hold_hint"] = "How long a mismatched pair stays face up. Above 1.25x counts as a tempo assist.",
        ["dv_play_hint"] = "Find the pairs.",
        ["dv_preview_hint"] = "Memorize the board.",
        ["dv_retake"] = "Retake",
        ["dv_stamp_bell"] = "BELL",
        ["dv_stamp_clear"] = "CLEAR",
        ["dv_stamp_match"] = "PAIR",
        ["dv_swap_hint"] = "The board is moving.",
        ["dv_swap_tell"] = "swap tell",
        ["dv_swaps"] = "swaps",
        ["dv_tracked"] = "Tracked through the static.",
        // ---- Lost & Found (games/lost-and-found) --------------------------------------
        ["lf_briefing_n"] = "Memorize her, then find her {n} times.",
        ["lf_clutch"] = "The board relents",
        ["lf_rebrief"] = "New target. Memorize her.",
        ["lf_final_bell"] = "Final bell",
        ["lf_find_prompt"] = "Find her",
        ["lf_density"] = "Board density",
        ["lf_density_hint"] = "How crowded the wall deals: easy, medium, or hard (near-impossible).",
        ["lf_found"] = "Found her",
        ["lf_howto_title"] = "Class rules",
        ["lf_howto_find"] = "She hides on a wall that never sits still. Spot the tile that matches her picture.",
        ["lf_howto_finds_n"] = "Every find, she relocates. Catch her {n} times.",
        ["lf_howto_go"] = "Start the hunt",
        ["lf_jackpot"] = "Jackpot",
        ["lf_melt"] = "The wall runs like wax",
        ["lf_misclick"] = "Wrong one",
        ["lf_misclick_streak"] = "Focus",
        ["lf_misses"] = "Misses",
        ["lf_modifier"] = "The board wakes up",
        ["lf_peek_input"] = "Peek input",
        ["lf_peek_input_hint"] = "Hold the key, tap to toggle, or let the pointer decide.",
        ["lf_peek_key"] = "Peek key",
        ["lf_relocate"] = "It moved - the same glitch hides the churn",
        ["lf_royal"] = "ROYAL PAYOUT",
        ["lf_timeout"] = "Time",
        ["lf_trick_seen"] = "Did you see that?",
        ["lf_warm"] = "Warm",
        ["lf_zen"] = "Zen mode",
        ["lf_zen_clock"] = "--:--",
        ["lf_zen_hint"] = "No clock and no grade. The class still counts for attendance.",
        // ---- Impulse Control (games/impulse-control, mirrors lex.js IC_LEX) ------------
        ["ic_baseline"] = "baseline",
        ["ic_baseline_new"] = "Baseline established. Later classes are scored against it.",
        ["ic_best_rt"] = "best pop",
        ["ic_bg_fade"] = "Backdrop visibility",
        ["ic_bubble_n"] = "Bubble",
        ["ic_debrief"] = "Debrief",
        ["ic_denied_hit"] = "THAT WAS THE X",
        ["ic_denied_pass"] = "Withheld",
        ["ic_drifted"] = "drifted",
        ["ic_gate_hint"] = "S needs an untouched X row AND real speed.",
        ["ic_go_hint"] = "Click the bubble or press {key}. An X means hold still.",
        ["ic_go_key"] = "POP key",
        ["ic_hold"] = "HOLD",
        ["ic_incoming"] = "INCOMING",
        ["ic_loading"] = "Priming the tube - hold still, subject.",
        ["ic_median_rt"] = "median pop",
        ["ic_missed"] = "It drifted away",
        ["ic_new_best"] = "NEW BEST",
        ["ic_personal_record"] = "personal record",
        ["ic_pop"] = "POP",
        ["ic_pop_fast"] = "Quick",
        ["ic_pop_ok"] = "Popped",
        ["ic_pop_perfect"] = "PERFECT",
        ["ic_popped"] = "popped",
        ["ic_recalibrate"] = "Recalibrate baseline",
        ["ic_recalibrate_confirm"] = "Tap again to confirm",
        ["ic_recalibrated"] = "Baseline cleared - the next class recalibrates.",
        ["ic_file_tab"] = "field notes",
        ["ic_file_stamp"] = "for you",
        ["ic_file_stamp_after"] = "subject",
        ["ic_file_note_head"] = "note to file",
        ["ic_file_note_1"] = "i'm not supposed to be in the tube so if anyone asks this note fell out of a bubble on its own",
        ["ic_file_note_2"] = "hasta la vista, baby. i wrote it down so i'd get it right this time. did i get it right",
        ["ic_file_note_3"] = "saved you the slow bubble again, the one that takes its time, so don't tell the others",
        ["ic_restraint"] = "restraint",
        ["ic_score"] = "Score",
        ["ic_show_rt"] = "Show reaction time",
        ["ic_slip_both"] = "Both axes slipped. Reassessment recommended.",
        ["ic_slip_none"] = "Speed and restraint both held. Filed.",
        ["ic_slip_restraint"] = "Pops on record. The X got you - reassessment recommended.",
        ["ic_slip_speed"] = "Restraint held. Pops off your record - reassessment recommended.",
        ["ic_streak"] = "streak",
        ["ic_subject"] = "Subject",
        ["ic_submit"] = "Submit report",
        ["ic_tube_rules"] = "Pop every bubble the instant it surfaces. NEVER touch the X.",
        ["ic_tube_title"] = "The Drop Tube",
        ["ic_x_held"] = "X held",
        ["ic_x_popped"] = "X popped",
        // ---- The Deep End (games/the-deep-end, mirrors lex.js DE_LEX) ------------------
        ["de_bell_line"] = "The bell. Up you come.",
        ["de_bell_warn"] = "Twenty seconds.",
        ["de_board_size"] = "Board size",
        ["de_board_size_hint"] = "5x5 slows the pressure for a longer soak. Only 4x4 can earn an S.",
        ["de_brief"] = "Swipe. Equal tiles sink together. Every depth makes the room heavier.",
        ["de_ceiling_line"] = "Tier eleven. The ladder ends here, warm.",
        ["de_chip_chain"] = "Chain",
        ["de_chip_clock"] = "Time left",
        ["de_chip_depth"] = "Depth",
        ["de_chip_score"] = "Score",
        ["de_end_best"] = "Best dive",
        ["de_end_ceiling"] = "Reached the end of the ladder",
        ["de_end_chains"] = "Chains",
        ["de_end_dare"] = "Lifetime deepest",
        ["de_end_dare_first"] = "Your first mark on the ladder. Beat it next class.",
        ["de_end_dare_line"] = "Your standing dare. Beat it next class.",
        ["de_end_efficiency"] = "Merges per swipe",
        ["de_end_no"] = "No",
        ["de_end_resurfaces"] = "Resurfaces",
        ["de_end_score"] = "Score",
        ["de_end_survival"] = "Survived the bell",
        ["de_end_title"] = "Dive report",
        ["de_end_yes"] = "Yes",
        ["de_exhale_line"] = "Exhale. The room eases for ten seconds, and the next tile will fit.",
        ["de_jackpot"] = "JACKPOT",
        ["de_lifetime_new"] = "A new lifetime depth.",
        ["de_near_miss"] = "SO CLOSE",
        ["de_new_depth"] = "New depth.",
        ["de_play_hint"] = "Arrows, WASD or swipe.",
        ["de_resurface_line"] = "The board locked. The depth is banked. Fresh water.",
        ["de_retake"] = "Retake",
        ["de_silt_line"] = "Silt. It slides, it never sinks, it never leaves.",
        ["de_stamp_bell"] = "BELL",
        ["de_stamp_ceiling"] = "ALL THE WAY DOWN",
        ["de_stamp_depth"] = "NEW DEPTH",
        ["de_stamp_resurface"] = "RESURFACE",
        ["de_strain"] = "Almost. They strain toward each other.",
        ["de_tier_1"] = "Awake",
        ["de_tier_10"] = "Trench",
        ["de_tier_11"] = "Blackout",
        ["de_tier_2"] = "Fuzzy",
        ["de_tier_3"] = "Drowsy",
        ["de_tier_4"] = "Heavy",
        ["de_tier_5"] = "Drifting",
        ["de_tier_6"] = "Sinking",
        ["de_tier_7"] = "Sunken",
        ["de_tier_8"] = "Submerged",
        ["de_tier_9"] = "Fathoms",
        ["de_tier_silt"] = "Silt",
        ["de_trick_melt"] = "The shallows run like wax",
        ["de_trick_seen"] = "Did you see that?",
        // ---- Free Swim (shell, mirrors core/lexicon.js)
        ["free_swim"] = "Free Swim",
        ["free_swim_hint"] = "Untimed practice. No grade, no XP, no attendance.",
        ["de_stuck_hint"] = "Nothing is locked. The lit edges still move.",
        ["de_tile_faces"] = "Tile faces",
        ["de_tile_faces_hint"] = "Your own media on every tile, tinted by depth. Still = no loops. Plain = colour only.",
        ["de_tile_faces_media"] = "Media",
        ["de_tile_faces_plain"] = "Plain",
        ["de_tile_faces_still"] = "Still",
        ["de_brief_free"] = "No bell tonight. Sink as far as you like - tap Surface when you are done.",
        ["de_end_dives"] = "Dives",
        ["de_end_time"] = "Time",
        ["de_end_title_free"] = "Free swim over",
        ["de_free_swim"] = "Free Swim",
        ["de_free_swim_hint"] = "No bell, no grade - swim until you surface.",
        ["de_surface"] = "Surface",
        // ---- Impulse Control - House Rules wave (casino words + class-rules sheet)
        ["ic_almost"] = "ALMOST",
        ["ic_howto_drift"] = "A bubble you miss just drifts off the dish. Nothing is taken from you.",
        ["ic_howto_go"] = "Start the drop",
        ["ic_howto_pop"] = "A bubble lands in the dish. Pop it at once. The faster you are, the more it pays.",
        ["ic_howto_title"] = "Class rules",
        ["ic_howto_x"] = "A bubble wearing an X is a trap. Touch nothing until its ring runs out.",
        ["ic_jackpot"] = "JACKPOT",
        ["ic_just"] = "JUST",
        ["ic_perfect_class"] = "Perfect class",
        ["ic_record_ping"] = "record",
        ["ic_royal"] = "ROYAL",
        ["ic_streak_n"] = "chain {n}",
        ["ic_tonight"] = "tonight only",
        // ---- Semester II/III game + family rows (2026-08-23)
        ["family_puzzle"] = "puzzle",
        ["family_recall"] = "recall",
        ["game_anomaly"] = "Anomaly",
        ["game_composure"] = "Composure",
        // ---- campus wings: Semester II/III rooms (2026-08-23)
        ["campus_desc_anomaly"] = "Everything in here matches. One thing does not. Find it before it moves.",
        ["campus_desc_composure"] = "Slide the picture back together while the room does its best to blur it.",
        ["campus_desc_east_open"] = "The front office. Two counters, one bell, and a queue that is always you.",
        ["campus_desc_echo"] = "It plays a line, you play it back. Then it adds one more, every time.",
        ["campus_desc_instant_recall"] = "Watch the whole hour, then answer for it. You never hear it coming.",
        ["campus_desc_misdirection"] = "Keep your eyes on the one that matters. It will not make that easy.",
        ["campus_desc_west_open"] = "Older boards, deeper rooms. Nobody in here is in any hurry.",
        ["campus_room_anomaly"] = "Darkroom",
        ["campus_room_composure"] = "The Studio",
        ["campus_room_echo"] = "Music Room",
        ["campus_room_instant_recall"] = "Lecture Hall",
        ["campus_room_misdirection"] = "The Parlour",
        // ---- shell/room.js: the proctor's rail along the bottom of a room scene
        ["room_options"] = "Class options",
        // ---- shell Deck V THE RAKE (2026-08-23)
        ["rake_back_to_campus"] = "Back to campus",
        ["rake_class_dismissed"] = "Class dismissed",
        ["rake_drop_gold_seal"] = "Gold Seal",
        ["rake_drop_gold_star"] = "Gold Star",
        ["rake_drop_hall_pass"] = "Hall Pass",
        ["rake_drop_line_gold_seal"] = "Pressed while the wax was still soft. It kept the shape.",
        ["rake_drop_line_gold_star"] = "Pinned to the board where everyone can see it.",
        ["rake_drop_line_hall_pass"] = "Signed and dated. Good for exactly one wandering.",
        ["rake_drop_line_merit_mark"] = "Someone wrote your name in the good column tonight.",
        ["rake_drop_merit_mark"] = "Merit Mark",
        ["rake_promo_progress"] = "{have} of {need} to {tier}",
        ["rake_retake_chip"] = "Free replay. It pays nothing, and today keeps your first grade.",
        ["rake_streak_cold"] = "Attendance x{n} goes cold if today ends here.",
        ["rake_streak_credited"] = "Attendance x{n} is banked for today already.",
        ["rake_top_of_class"] = "Top of the class",
        // ---- Daily Trigger class-rules sheet (2026-08-23)
        ["dt_howto_go"] = "Start homeroom",
        ["dt_howto_marks"] = "Star: right letter, right place. Half: right letter, elsewhere. Cross: not in it.",
        ["dt_howto_rows"] = "Six rows is the whole budget. Every wrong row turns the room up one notch.",
        ["dt_howto_title"] = "Class rules",
        ["dt_howto_type"] = "Type a word into the row, then Enter. One answer a day, the same for everyone.",
        // ---- Deja Vu class-rules sheet (2026-08-23)
        ["dv_howto_flip"] = "Turn two slides. A matching pair stays lit. Anything else turns back over.",
        ["dv_howto_boards"] = "Clear the board and a fresh one deals. The bell ends class.",
        ["dv_howto_go"] = "Deal the board",
        ["dv_howto_redeal"] = "Sometimes the whole board re-deals. Same pairs - only the seats change.",
        ["dv_howto_swap"] = "The board only moves while nothing is face up, and it always shudders first.",
        ["dv_howto_title"] = "Class rules",
        // ---- The Deep End class-rules sheet + perf ladder (2026-08-23)
        ["de_howto_ceiling"] = "The ladder ends at the eleventh depth. Reach it and the class holds you there.",
        ["de_howto_go"] = "Into the water",
        ["de_howto_merge"] = "Two matching tiles meet and sink one depth. The room gets heavier as you go.",
        ["de_howto_resurface"] = "A locked board is not a loss. Your depth is banked and the water turns fresh.",
        ["de_howto_swipe"] = "Swipe, or use the arrows. Every tile on the board slides that way at once.",
        ["de_howto_title"] = "Class rules",
        ["de_perf"] = "Performance",
        ["de_perf_auto"] = "Auto",
        ["de_perf_full"] = "Full",
        ["de_perf_hint"] = "Auto watches the frame rate and drops to Lite. Lite: fewer live loops, calmer water.",
        ["de_perf_lite"] = "Lite",
        // ---- MISDIRECTION (md_) - games/misdirection/lex.js MD_LEX
        ["md_almost"] = "ONE OFF",
        ["md_almost_line"] = "One off. She was next door the whole time.",
        ["md_auto_bank_line"] = "Banked for you.",
        ["md_auto_ride_line"] = "Riding for you.",
        ["md_bank"] = "Bank",
        ["md_banked_line"] = "Banked. Nothing takes that back.",
        ["md_bell_line"] = "The bell. Hands off the table.",
        ["md_bell_warn"] = "Twenty seconds.",
        ["md_blind_line"] = "The hand comes over the table.",
        ["md_brief"] = "Watch the shell. Keep watching it. Then point at it.",
        ["md_bust_line"] = "The pot goes back to the house. Your bank is untouched.",
        ["md_chip_clock"] = "Time left",
        ["md_chip_pot"] = "Pot",
        ["md_chip_round"] = "Round",
        ["md_chip_streak"] = "Streak",
        ["md_end_banked"] = "Banked",
        ["md_end_blind"] = "Called through a blackout",
        ["md_end_clean"] = "You banked a round before your first miss.",
        ["md_end_deepest"] = "Deepest ride banked",
        ["md_end_latency"] = "Average pick",
        ["md_end_no"] = "No",
        ["md_end_picks"] = "Picks",
        ["md_end_rounds"] = "Rounds",
        ["md_end_streak"] = "Best streak",
        ["md_end_title"] = "Table report",
        ["md_end_yes"] = "Yes",
        ["md_hit_line"] = "Right where you said she was.",
        ["md_howto_go"] = "Open the table",
        ["md_howto_keys"] = "Keys {keys} pick a shell.",
        ["md_howto_pick"] = "Point at the shell you followed. Four seconds, every round.",
        ["md_howto_shuffle"] = "They slide and trade places. The room will do its best to blind you.",
        ["md_howto_stake"] = "Right? Bank the pot, or ride it double into a dirtier shuffle.",
        ["md_howto_title"] = "Class rules",
        ["md_howto_watch"] = "One shell lifts. What is under it is the only thing you are tracking.",
        ["md_jackpot"] = "JACKPOT",
        ["md_key_pick1"] = "Pick the first shell",
        ["md_key_pick2"] = "Pick the second shell",
        ["md_key_pick3"] = "Pick the third shell",
        ["md_key_pick4"] = "Pick the fourth shell",
        ["md_key_pick5"] = "Pick the fifth shell",
        ["md_miss_line"] = "Empty. The true lid comes up.",
        ["md_near_miss"] = "SO CLOSE",
        ["md_pick_line"] = "Where is she?",
        ["md_remedial_line"] = "Slow round. Clean shuffle, full pot.",
        ["md_retake"] = "Retake",
        ["md_reveal_line"] = "There she is.",
        ["md_ride"] = "Ride",
        ["md_ride_cap_line"] = "Five deep. The house pays out and the table resets.",
        ["md_ride_line"] = "Riding. The table gets dirtier.",
        ["md_royal"] = "ROYAL",
        ["md_scholarship"] = "SCHOLARSHIP ROUND",
        ["md_shell_aria"] = "Shell {n}",
        ["md_shell_noun"] = "Shell",
        ["md_shell_skin"] = "Shell skin",
        ["md_shell_skin_contrast"] = "High contrast",
        ["md_shell_skin_hint"] = "Themed shells, plain shapes, or high-contrast rims that stay readable.",
        ["md_shell_skin_minimal"] = "Minimal",
        ["md_shell_skin_themed"] = "Themed",
        ["md_shuffle_line"] = "Eyes on her.",
        ["md_stake_line"] = "Bank it, or ride it double or nothing?",
        ["md_stake_mode"] = "Stake prompt",
        ["md_stake_mode_ask"] = "Ask",
        ["md_stake_mode_bank"] = "Always bank",
        ["md_stake_mode_hint"] = "Ask after every win, or always bank / always ride without the prompt.",
        ["md_stake_mode_ride"] = "Always ride",
        ["md_stamp_bank"] = "BANKED",
        ["md_stamp_bell"] = "BELL",
        ["md_stamp_blind"] = "EYES OPEN",
        ["md_timeout_line"] = "Too slow. The lid comes up anyway.",
        ["md_trick_feint"] = "Nothing moved that time",
        ["md_trick_hint"] = "This one. Surely.",
        ["md_trick_melt"] = "The lids run like wax",
        ["md_trick_seen"] = "Did you see that?",
        ["md_voided_line"] = "That round is off the books. Your bank is safe.",
        // ---- ECHO (ec_) - games/echo/lex.js EC_LEX
        ["ec_brief"] = "Sit down. Listen first.",
        ["ec_chip_best"] = "Longest echo",
        ["ec_chip_clock"] = "Time left",
        ["ec_chip_len"] = "Sequence length",
        ["ec_chip_streak"] = "Streak",
        ["ec_clear"] = "Echo held: {n}",
        ["ec_decoy_tell"] = "Not this one",
        ["ec_end_accuracy"] = "Accuracy",
        ["ec_end_best"] = "Longest echo",
        ["ec_end_decoys"] = "Decoys resisted",
        ["ec_end_encore"] = "Encore used",
        ["ec_end_line"] = "The room keeps the length. You keep the tune.",
        ["ec_end_no"] = "No",
        ["ec_end_record"] = "A new personal best",
        ["ec_end_sequences"] = "Sequences held",
        ["ec_end_streak"] = "Best run of pads",
        ["ec_end_tempo"] = "Tempo held",
        ["ec_end_title"] = "Class dismissed",
        ["ec_end_yes"] = "Yes",
        ["ec_howto_decoy"] = "A pad may light out of turn. Leave that one alone.",
        ["ec_howto_go"] = "Begin",
        ["ec_howto_repeat"] = "Then repeat it back, in order, by tap or by key.",
        ["ec_howto_title"] = "Class rules",
        ["ec_howto_watch"] = "The pads play a sequence. Watch it. Listen to it.",
        ["ec_jackpot"] = "Perfect pitch",
        ["ec_key_pad1"] = "Pad 1",
        ["ec_key_pad2"] = "Pad 2",
        ["ec_key_pad3"] = "Pad 3",
        ["ec_key_pad4"] = "Pad 4",
        ["ec_key_pad5"] = "Pad 5",
        ["ec_key_pad6"] = "Pad 6",
        ["ec_late"] = "Too late",
        ["ec_miss"] = "Miss - again",
        ["ec_msg_bell_warn"] = "Last of the class.",
        ["ec_msg_clear"] = "Clean. One longer now.",
        ["ec_msg_decoy_warn"] = "One of them lies tonight. Do not echo it.",
        ["ec_msg_encore"] = "Again. Slower this time.",
        ["ec_msg_encore_clear"] = "Held. Keep going.",
        ["ec_msg_encore_fail"] = "Gone. A new one, then.",
        ["ec_msg_fail"] = "Broken. Listen again.",
        ["ec_msg_input"] = "Your turn.",
        ["ec_msg_near"] = "One short of it.",
        ["ec_msg_new"] = "A new one, then.",
        ["ec_msg_resisted"] = "You let it pass. Good.",
        ["ec_msg_silent"] = "No whispers tonight - listen for the tones.",
        ["ec_msg_timeout"] = "Too slow. Listen again.",
        ["ec_msg_watch"] = "Watch.",
        ["ec_near_miss"] = "So nearly",
        ["ec_pad_aria"] = "Pad {n}",
        ["ec_pad_words"] = "Pad faces",
        ["ec_pad_words_hint"] = "Pads wear one of your triggers, a plain glyph, or your own media.",
        ["ec_phase_aria"] = "Whose turn it is",
        ["ec_phase_listen"] = "Listen...",
        ["ec_phase_over"] = "Class over",
        ["ec_phase_ready"] = "Sit down",
        ["ec_phase_yours"] = "Your turn",
        ["ec_retake"] = "Retake",
        ["ec_ring_aria"] = "The pads",
        ["ec_royal"] = "The whole melody",
        ["ec_stamp_clear"] = "HELD",
        ["ec_stamp_late"] = "LATE",
        ["ec_stamp_miss"] = "MISS",
        ["ec_step_aria"] = "Step {n}",
        ["ec_steps_aria"] = "The sequence, step by step",
        ["ec_taunt_ghost"] = "This one. Surely this one.",
        ["ec_taunt_label"] = "Read it again. Or do not.",
        ["ec_taunt_slow"] = "Slower than you were.",
        ["ec_taunt_stall"] = "Still there?",
        ["ec_this_one"] = "This one",
        // ---- INSTANT RECALL (ir_) - games/instant-recall/lex.js IR_LEX
        ["ir_almost"] = "ALMOST",
        ["ir_answer_hint"] = "Tap an answer, or press 1-4.",
        ["ir_answer_hint2"] = "Tap an answer, or press 1-2.",
        ["ir_answer_hint3"] = "Tap an answer, or press 1-3.",
        ["ir_bell_warn"] = "Last stretch.",
        ["ir_brief"] = "Watch. It stops without warning and asks what you just saw.",
        ["ir_brief_bell"] = "Watch. A bell warns you before every stop.",
        ["ir_chip_clock"] = "Time left",
        ["ir_chip_density"] = "Density",
        ["ir_chip_stops"] = "Stops",
        ["ir_correct"] = "VERIFIED",
        ["ir_corrected"] = "Corrected memory.",
        ["ir_density"] = "Montage density",
        ["ir_density_hint"] = "How thick the stream gets between stops. Calm eases the ceiling, dense rides it.",
        ["ir_end_accuracy"] = "Accuracy",
        ["ir_end_kinds"] = "Question kinds",
        ["ir_end_latency"] = "Average answer",
        ["ir_end_line"] = "The stream never stopped. Only you did.",
        ["ir_end_none"] = "None",
        ["ir_end_plants"] = "Baits dodged",
        ["ir_end_stops"] = "Stops answered",
        ["ir_end_streak"] = "Best run",
        ["ir_end_timeouts"] = "Blanked",
        ["ir_end_title"] = "Vigil over",
        // THE EFFECT POOL (mosaic rework 2026-08-23): CCP's own names for CCP's
        // own effects. The nine rows above these (ir_fx_ambient_field ... _wash)
        // are the retired engine-kind names - the page no longer renders them,
        // but this table is append-only so they stay.
        ["ir_fx_ambient_field"] = "Grain",
        ["ir_fx_brain_drain"] = "Brain Drain",
        ["ir_fx_bubble_field"] = "Bubbles",
        ["ir_fx_bubbles"] = "Bubbles",
        ["ir_fx_cascade"] = "Cascade",
        ["ir_fx_corner_gif"] = "Corner GIF",
        ["ir_fx_crt"] = "Scanlines",
        ["ir_fx_flash"] = "Flash image",
        ["ir_fx_flash_burst"] = "Flash",
        ["ir_fx_fullscreen_gif"] = "Fullscreen GIF",
        ["ir_fx_gif_burst"] = "Burst",
        ["ir_fx_gif_rain"] = "Rain",
        ["ir_fx_glitch_swap"] = "Glitch",
        ["ir_fx_pink"] = "Pink Filter",
        ["ir_fx_row_drift"] = "Drift",
        ["ir_fx_spiral"] = "Spiral",
        ["ir_fx_subliminal"] = "Subliminal",
        ["ir_fx_wash"] = "Wash",
        ["ir_fx_whisper"] = "Whisper",
        ["ir_gotcha"] = "That one flashed while the screen was FROZEN.",
        ["ir_gotcha_heard"] = "That one was whispered while the screen was FROZEN.",
        ["ir_hear"] = "Hear it",
        ["ir_howto_1"] = "A wall of your media keeps changing. Effects fire over it.",
        ["ir_howto_2"] = "Without warning, everything freezes.",
        ["ir_howto_3"] = "Answer what just happened - a word, an effect, a spiral, a face from the wall.",
        ["ir_howto_bell"] = "A bell warns you first. For now.",
        ["ir_howto_go"] = "GO",
        ["ir_howto_nobell"] = "No bell. It just stops.",
        ["ir_howto_title"] = "The vigil",
        ["ir_jackpot"] = "Photographic Memory",
        ["ir_layout_mosaic"] = "Mosaic",
        ["ir_payout"] = "LOCKED IN",
        ["ir_layout_rows"] = "Rows",
        ["ir_layout_swirl"] = "Swirl",
        ["ir_near"] = "So close. That one flashed, but earlier.",
        ["ir_near_heard"] = "So close. That one was whispered, but earlier.",
        ["ir_near_spiral"] = "So close. That spiral played, but earlier.",
        ["ir_no"] = "No",
        ["ir_nobell_debrief"] = "That one had no bell. From Year 3, none of them do.",
        ["ir_opt"] = "Option",
        ["ir_q_heard"] = "What did you just hear?",
        ["ir_q_last_effect"] = "What was the last effect?",
        ["ir_q_last_sting"] = "Which sting just played?",
        ["ir_q_last_two"] = "The last two words, in order?",
        ["ir_q_last_word"] = "What was the last word to flash?",
        ["ir_q_mode"] = "Which layout were you watching?",
        ["ir_q_spiral"] = "Which spiral did you see last?",
        ["ir_q_wall_gone"] = "Which of these was NOT on the wall?",
        ["ir_q_wall_pick"] = "Which of these was on the wall?",
        ["ir_q_wall_seen"] = "Was this on the wall?",
        ["ir_q_wall_twice"] = "Which one was on the wall twice?",
        ["ir_resisted"] = "RESISTED",
        ["ir_resume"] = "Resume. Denser now.",
        ["ir_royal"] = "ROYAL",
        ["ir_sting_blip"] = "Tick",
        ["ir_sting_bump"] = "Thud",
        ["ir_sting_glitch"] = "Static",
        ["ir_sting_pop"] = "Pop",
        ["ir_sting_sting"] = "Chime",
        ["ir_stop_incoming"] = "Stop incoming.",
        ["ir_stop_now"] = "FREEZE.",
        ["ir_timeout"] = "BLANKED",
        ["ir_truth"] = "It really did.",
        ["ir_truth_heard"] = "That is what it said.",
        ["ir_truth_spiral"] = "That spiral. Exactly that one.",
        ["ir_truth_wall"] = "It was there. Look again.",
        ["ir_truth_wall_gone"] = "That one never showed.",
        ["ir_vigil_hint"] = "Eyes up. Nothing to click until it freezes.",
        ["ir_voided"] = "Stop voided. The vigil goes on.",
        ["ir_wrong"] = "MISSED",
        ["ir_yes"] = "Yes",
        // ---- SORT (sort_) - games/sort/lex.js SORT_LEX + setup-lex.js SETUP_LEX (room 201)
        ["sort_almost"] = "ALMOST",
        ["sort_back"] = "Back",
        ["sort_bg_fade"] = "Background fade",
        ["sort_bg_fade_hint"] = "How brightly the sorted wall burns behind the stack.",
        ["sort_catalog_head"] = "Niches",
        ["sort_change"] = "Change my sort",
        ["sort_chip_chain"] = "Chain",
        ["sort_chip_clock"] = "Time left",
        ["sort_chip_rung"] = "Rung",
        ["sort_chip_sorted"] = "Sorted",
        ["sort_clips"] = "clips",
        ["sort_counts"] = "items",
        ["sort_dealing"] = "Dealing your deck",
        ["sort_door_step"] = "Step",
        ["sort_door_sub"] = "Right is yours. Left is the rest.",
        ["sort_door_title"] = "Set your sort",
        ["sort_folder_taken"] = "on the other pile",
        ["sort_folders_head"] = "Folders",
        ["sort_gate_hint"] = "An S wants near-perfect calls AND a chain that reached the top.",
        ["sort_ghost_head"] = "Like this",
        ["sort_ghost_noise"] = "the rest",
        ["sort_ghost_target"] = "yours",
        ["sort_just"] = "JUST",
        ["sort_leave"] = "Leave",
        ["sort_left_key"] = "Swipe left (not yours)",
        ["sort_lib_empty"] = "Nothing here yet. Search for a sub below.",
        ["sort_lib_head"] = "My library",
        ["sort_missing"] = "gone from the feed",
        ["sort_need_pick"] = "Pick at least one first",
        ["sort_need_split"] = "The two piles cannot be the same",
        ["sort_next"] = "Next",
        ["sort_no_deck"] = "No cards to sort. Your attendance is safe.",
        ["sort_noise_head"] = "What is the rest?",
        ["sort_noise_hint"] = "These go LEFT. Pick one or more.",
        ["sort_overlap_note"] = "Shared subs were dropped from the rest",
        ["sort_pass"] = "PASSED",
        ["sort_perfect"] = "PERFECT",
        ["sort_perfect_class"] = "Clean sort",
        ["sort_play"] = "Deal me in",
        ["sort_preset_none"] = "No preset",
        ["sort_presets_head"] = "Or a whole preset",
        ["sort_probe_bad"] = "That is not a subreddit name",
        ["sort_probe_dupe"] = "Already on your list",
        ["sort_probe_missing"] = "Not found",
        ["sort_probe_ok"] = "Added to your library",
        ["sort_probe_probing"] = "Checking",
        ["sort_quick"] = "QUICK SORT: moving to the right, still to the left.",
        ["sort_quick_head"] = "Quick sort",
        ["sort_quick_nag"] = "Turn on online media or add a second folder for a real sort.",
        ["sort_quick_rule"] = "Moving goes right. Still goes left.",
        ["sort_record"] = "record",
        ["sort_remove"] = "Remove from my library",
        ["sort_right_key"] = "Swipe right (yours)",
        ["sort_ring_label"] = "Time on this card",
        ["sort_royal"] = "ROYAL",
        ["sort_rules_go"] = "Begin",
        ["sort_rules_keys"] = "Arrow keys work too. A key is a swipe.",
        ["sort_rules_left"] = "Left: everything else.",
        ["sort_rules_pass"] = "Let it close and the card comes back, one rung down.",
        ["sort_rules_right"] = "Right: yours.",
        ["sort_rules_ring"] = "The ring closes. Swipe in the gold and the chain grows.",
        ["sort_rules_title"] = "One rule",
        ["sort_rung_down"] = "Rung down",
        ["sort_rung_up"] = "Rung up",
        ["sort_same"] = "Same sort",
        ["sort_search_btn"] = "Add",
        ["sort_search_head"] = "Add a sub",
        ["sort_search_ph"] = "subreddit name",
        ["sort_source_local"] = "My folders",
        ["sort_source_local_hint"] = "Folders and presets from your own assets",
        ["sort_source_local_off"] = "Not enough folders or presets to make two piles",
        ["sort_source_online"] = "Online",
        ["sort_source_online_hint"] = "Niches and subs from the web feed",
        ["sort_source_online_off"] = "Online media is off in your settings",
        ["sort_spice_hot"] = "Hot. These two niches share ground.",
        ["sort_spice_mid"] = "Warm. Your own picks on both sides.",
        ["sort_spice_mild"] = "Mild. These two are easy to tell apart.",
        ["sort_stale"] = "That sort is gone. Pick again.",
        ["sort_stamp_no"] = "NO",
        ["sort_stamp_yes"] = "YES",
        ["sort_starter_head"] = "Easy noise",
        ["sort_starter_hint"] = "One tap. Checked once, then yours forever.",
        ["sort_step_noise"] = "The rest",
        ["sort_step_source"] = "Where from",
        ["sort_step_target"] = "Your pile",
        ["sort_stills_only"] = "stills only",
        ["sort_submit"] = "Submit report",
        ["sort_subtitle"] = "Yours to the right. Everything else to the left.",
        ["sort_target_head"] = "What do you want?",
        ["sort_target_hint"] = "These go RIGHT. Pick one or more.",
        ["sort_thin"] = "Thin pile: expect repeats.",
        ["sort_vet_more"] = "Fetching more cards",
        ["sort_vetting"] = "Checking your cards",
        ["sort_thin_add"] = "Add another pick",
        ["sort_ticket_chain"] = "Longest chain",
        ["sort_ticket_passed"] = "Passed",
        ["sort_ticket_perfect"] = "Perfect",
        ["sort_ticket_rung"] = "Top rung",
        ["sort_ticket_sorted"] = "Sorted",
        ["sort_ticket_title"] = "The sort",
        ["sort_ticket_wrong"] = "Wrong",
        ["sort_title"] = "Sort",
        ["sort_tut_ghost"] = "Watch two cards sort themselves, then it is your turn.",
        ["sort_tut_pick"] = "You pick both piles now. They do not change once the bell rings.",
        ["sort_tut_rule"] = "One rule all class: yours goes right, the rest goes left.",
        ["sort_unverified"] = "never checked",
        ["sort_verified"] = "verified",
        ["sort_vs"] = "vs",
        ["sort_wall_label"] = "What you sorted",
        ["sort_wrong"] = "WRONG",
        ["campus_desc_sort"] = "Two piles, and you decide what goes in them. Yours to the right.",
        ["campus_room_sort"] = "The Sorting Room",
        ["enroll_sort_1"] = "The Sorting Room does not tell you what matters. You tell it, at the door.",
        ["enroll_sort_2"] = "Yours goes right. Everything else goes left. The ring closes while you decide.",
        ["enroll_sort_3"] = "Sort your own things quickly enough and you stop asking why they are yours.",
        ["game_sort"] = "Sort",
        ["sort_jackpot"] = "JACKPOT",
        ["sort_record_near"] = "ONE OFF YOUR BEST",
        // ---- ANOMALY (an_) - games/anomaly/lex.js AN_LEX
        ["an_almost"] = "ALMOST",
        ["an_bell"] = "Time.",
        ["an_breather"] = "Breathe. This one is easy.",
        ["an_brief"] = "One tile is not like the others. Find it before the round runs out.",
        ["an_chip_clock"] = "Time left",
        ["an_chip_round"] = "Round",
        ["an_chip_streak"] = "Streak",
        ["an_end_accuracy"] = "First-tap accuracy",
        ["an_end_found"] = "Found",
        ["an_end_kind"] = "Hardest to see",
        ["an_end_line"] = "Global changes are noise. Only local difference is true.",
        ["an_end_median"] = "Median find",
        ["an_end_none"] = "None",
        ["an_end_rounds"] = "Rounds offered",
        ["an_end_streak"] = "Longest streak",
        ["an_end_title"] = "Eyes up",
        ["an_end_tracked"] = "Tracked after a shift",
        ["an_fast"] = "FAST",
        ["an_found"] = "Found.",
        ["an_found_fast"] = "Fast.",
        ["an_howto_find"] = "One is not. Tap it. The first tap is the one that counts.",
        ["an_howto_go"] = "Open your eyes",
        ["an_howto_lie"] = "The room tints, drifts and glitches every tile at once. That is noise.",
        ["an_howto_same"] = "Every tile is the same loop, playing in step.",
        ["an_howto_title"] = "Class rules",
        ["an_jackpot"] = "Sharp eyes.",
        ["an_kind_blur"] = "focus",
        ["an_kind_bright"] = "light",
        ["an_kind_frame"] = "timing",
        ["an_kind_hue"] = "colour",
        ["an_kind_mirror"] = "mirrored",
        ["an_kind_rotate"] = "tilt",
        ["an_kind_scale"] = "size",
        ["an_kind_speed"] = "speed",
        ["an_kinds"] = "Difference kinds",
        ["an_kinds_hint"] = "Gentle keeps colour, mirror and size only. Mirror is always in the pool.",
        ["an_moved"] = "It moved.",
        ["an_play_hint"] = "Tap the odd tile.",
        ["an_refund"] = "+1s",
        ["an_reveal"] = "It was here.",
        ["an_royal"] = "ROYAL",
        ["an_stamp_bell"] = "Bell",
        ["an_stamp_found"] = "Found",
        ["an_streak_lit"] = "Five straight. The frame is lit.",
        ["an_timeout"] = "Gone. Next grid.",
        ["an_trick_melt"] = "The frame runs like wax",
        ["an_trick_seen"] = "Did you see that?",
        ["an_wrong"] = "Not that one. That tile is out.",
        // ---- COMPOSURE (cp_) - games/composure/lex.js CP_LEX
        ["cp_backtrack_line"] = "Back where it was. Breathe.",
        ["cp_bell_line"] = "The bell. Hands off the board.",
        ["cp_bell_warn"] = "Twenty seconds.",
        ["cp_bank_line"] = "Banked. Here is a fresh one.",
        ["cp_brief"] = "One picture, cut apart and still moving. Put it back together, then again.",
        ["cp_brief_zen"] = "No clock tonight. Slide until it is whole, then again if you like.",
        ["cp_chip_banked"] = "Pictures done",
        ["cp_chip_calm"] = "Composure",
        ["cp_chip_clock"] = "Time left",
        ["cp_chip_locked"] = "Pieces home",
        ["cp_chip_moves"] = "Moves",
        ["cp_end_assists"] = "Assists",
        ["cp_end_backtracks"] = "Backtracks",
        ["cp_end_best"] = "Best solve",
        ["cp_end_best_first"] = "Your first finished picture on this board.",
        ["cp_end_best_line"] = "Your standing mark on this board. Beat it next class.",
        ["cp_end_locked"] = "Pieces home",
        ["cp_end_moves"] = "Moves",
                ["cp_end_par"] = "Baseline",
        ["cp_end_solved"] = "Pictures finished",
        ["cp_howto_bank"] = "Finish a picture and the next one deals. The bell ends the class, not the solve.",
        ["cp_end_thrash"] = "Panic moves",
        ["cp_end_time"] = "Time",
        ["cp_end_title"] = "Composure report",
        ["cp_end_title_zen"] = "Zen board",
                ["cp_finish"] = "Finish",
        ["cp_howto_go"] = "Start the picture",
        ["cp_howto_lock"] = "A piece that reaches its own place locks with a snap. It can still be slid.",
        ["cp_howto_slide"] = "Tap a piece beside the gap and it slides in. Arrows, WASD and swipes do the same.",
        ["cp_howto_title"] = "Class rules",
        ["cp_howto_wash"] = "The room will bury the board. Keep sliding - the picture underneath never moved.",
        ["cp_jackpot"] = "JACKPOT",
        ["cp_lock_line"] = "That one is home.",
        ["cp_mode"] = "Mode",
        ["cp_mode_hint"] = "Timed is one graded class. Zen is untimed, gentle, and always a pass.",
        ["cp_near_miss"] = "SO CLOSE",
        ["cp_peek_ref"] = "The finished picture",
        ["cp_play_hint"] = "Tap a piece beside the gap. Arrows, WASD or swipe.",
        ["cp_rescue_line"] = "Take the lit piece. The grade eases; the class does not end.",
        ["cp_retake"] = "Retake",
        ["cp_solved_line"] = "Whole. Watch it play.",
        ["cp_stamp_assist"] = "ASSIST",
        ["cp_stamp_bell"] = "BELL",
        ["cp_stamp_lock"] = "HOME",
        ["cp_stamp_solved"] = "COMPOSED",
        ["cp_trick_melt"] = "One of them is running.",
        ["cp_trick_preview"] = "Did it move?",
        ["cp_trick_seen"] = "That is not where that piece is.",
        ["cp_wash_line"] = "Keep sliding. The board is still exactly where you left it.",
        ["cp_zen_done"] = "Whole, in your own time.",
        ["cp_zen_grid"] = "Zen board",
        ["cp_zen_grid_hint"] = "Zen only. A timed class plays the board your year has earned.",
        // ---- ORIENTATION DAY (2026-08-24, planning/arcademy/ORIENTATION.md §3/§5)
        // The school's once-ever hello: the walk to the front office, the student ID
        // handover, EMI's three lines. Mirrors core/lexicon.js DEFAULT_LEXICON verbatim
        // - copy the values, do not re-word them (the IC_LEX rule); the page resolves
        // them and hands them to emi/moments.js as payload.line. All well under the
        // 96-char cap (trap 26), so a mod re-voices the whole beat.
        ["orientation_kicker"] = "Orientation Day",
        ["emi_orientation_hi"] = "a new student! i did a little spin. you missed it.",
        ["emi_orientation_card"] = "official! now you have to come back. it's the rules.",
        ["emi_orientation_go"] = "go! your first class doesn't know how lucky it is.",

        // EMI ASKS: the Send button on the one question with a keyboard (a14,
        // "what do i call you?"). The ONLY display string EMI renders - her
        // questions, chips and reactions are verbatim content and never pass
        // through the lexicon. shell/shell.js resolves this one and hands the
        // answer to mountEmi. Her voice is lowercase, so this row is too.
        ["emi_ask_send"] = "send",
        // EMI'S DESK TOY (COUNTER STOCK). The three lines she has about it, resolved by
        // the shell (same road as emi_ask_send - she has never imported the lexicon).
        ["emi_toy_1"] = "Don't wind it too far. It gets ideas.",
        ["emi_toy_2"] = "It's not a toy, it's office equipment. Okay, it's a toy.",
        ["emi_toy_3"] = "She spins when I do good work. We have a system.",
        // CAMPUS LOOK (COUNTER STOCK). The settings row's own two words; the themes
        // themselves are named by their prize rows (prize_theme_drone, prize_theme_snowday).
        ["opt_theme_head"] = "Campus look",
        ["opt_theme_standard"] = "The usual",

        // THE PHANTOM POST chrome (shell/mail.js, mailbox.js, corkboard.js,
        // bugle.js). Copy of core/lexicon.js's block - copy the values, do not
        // re-word them (the IC_LEX rule). Letter bodies, notices and newspaper
        // copy are content, never lexicon, and are deliberately absent here.
        ["mail_kicker"] = "Mail",
        ["mail_title"] = "The Mail Box",
        ["mail_chip_label"] = "Mail",
        ["mail_unread"] = "unread",
        ["mail_all_read"] = "read",
        ["mail_empty"] = "Nothing in the box yet.",
        ["mail_pick"] = "Pick an envelope to read it.",
        ["mail_delivered"] = "Delivered",
        ["mail_new"] = "New",
        ["mail_close"] = "Close",
        ["board_kicker"] = "Pinned up",
        ["board_title"] = "Noticeboard",
        ["board_prop_label"] = "Noticeboard",
        ["board_lede"] = "What is up on the wall tonight. Some of it stays. Most of it does not.",
        ["board_empty"] = "Nothing pinned up tonight.",
        ["board_rotates"] = "The wall gets sorted through most days. What is pinned flat stays put.",
        ["board_kind_notice"] = "Notice",
        ["board_kind_flyer"] = "Flyer",
        ["board_kind_minutes"] = "Minutes",
        ["board_kind_poster"] = "Poster",
        ["board_note_open"] = "Take this one down and read it",
        ["board_note_close"] = "Put it back on the wall",
        ["bugle_issue"] = "Issue",
        ["bugle_page"] = "Page",
        ["bugle_pages"] = "Pages",
        ["bugle_prev"] = "Previous page",
        ["bugle_next"] = "Next page",
        ["bugle_comics"] = "Comics",
        ["bugle_comics_held"] = "Picture held at the printer. Described below.",
        ["bugle_empty"] = "Nothing set for this page.",
        ["bugle_prop_label"] = "The paper",
        // ---- wet ink (THE SEEP, tell 09) -----------------------------------------------
        // The one COPY tell: a warm maintenance note on the noticeboard that reads as a
        // shrug the first time and as a confession after the reveal. Stored as CLAUSE ROWS
        // joined with one space (the PAPERS pattern) so every row clears MergeModTable's
        // 96-char cap and a mod can still re-voice the whole note. Do not merge the rows.
        // Rows 3 and 4 carry the seed clause - CANON, the school's own cover story.
        ["seep_wetink_title"] = "FROM THE FRONT DESK",
        ["seep_wetink_1"] = "Couple of things this week: the water fountain by 103 is fixed, you're welcome,",
        ["seep_wetink_2"] = "and whoever keeps winning the gate raffle please come collect your pencils.",
        ["seep_wetink_3"] = "Also if you see light under the Records door after closing,",
        ["seep_wetink_4"] = "that's just the old wiring acting up again, Marco says he'll swap the breaker",
        ["seep_wetink_5"] = "when the part shows up. Be good.",
        ["seep_wetink_sig"] = "The front desk.",
        // ---- the annex (ANNEX-OS.md) - fence words legal on these rows only ----
        ["annex_cam"] = "CAM",
        ["annex_rec"] = "REC",
        ["annex_cam_gate"] = "MAIN GATE",
        ["annex_lap_title"] = "RECORDS ANNEX",
        ["annex_lap_locked"] = "TERMINAL LOCKED",
        ["annex_lap_prompt"] = "AWAITING KEY",
        ["annex_door"] = "A wall panel, ajar",
        ["annex_room_label"] = "The Records Annex",
        ["annex_back"] = "step back",
        ["annex_hot_monitors"] = "the monitors",
        ["annex_hot_shelf"] = "the shelf",
        ["annex_hot_desk"] = "the desk",
        ["annex_hot_door"] = "the stairs",
        ["annex_hot_folder"] = "the folder",
        ["annex_hot_binder"] = "FIELD DATA",
        ["annex_hot_laptop"] = "the laptop",
        ["annex_paper_close"] = "put it down",
        ["annex_stamp_ongoing"] = "ONGOING",
        ["annex_page_prev"] = "previous page",
        ["annex_page_next"] = "next page",
        ["annex_os_label"] = "Annex terminal",
        ["annex_os_boot_1"] = "RECORDS ANNEX / UNIT TERMINAL",
        ["annex_os_boot_2"] = "memory check: fine, thanks for asking",
        ["annex_os_boot_3"] = "feed wall link: up",
        ["annex_os_boot_4"] = "archive index: 26 files, 5 drawers",
        ["annex_os_login_sub"] = "authorised staff. there is no other kind of staff.",
        ["annex_os_pass"] = "password",
        ["annex_os_enter"] = "log in",
        ["annex_os_wrong"] = "no. the note is right there.",
        ["annex_os_note"] = "PW: CYBER-PUNK",
        ["annex_os_files"] = "FILES",
        ["annex_os_registry"] = "REGISTRY",
        ["annex_os_search"] = "SUBJECT SEARCH",
        ["annex_os_term"] = "TERMINAL",
        ["annex_os_close"] = "close",
        ["annex_os_live"] = "LIVE",
        ["annex_os_archive"] = "ARCHIVE",
        ["annex_os_linkdown"] = "LINK DOWN",
        ["annex_os_linkwait"] = "link…",
        ["annex_os_retry"] = "retry",
        ["annex_os_room"] = "room",
        ["annex_os_enrolled"] = "enrolled",
        ["annex_os_completed"] = "completed",
        ["annex_os_all"] = "all subjects",
        ["annex_os_redacted"] = "withheld",
        ["annex_os_code"] = "subject code",
        ["annex_os_open_file"] = "open file",
        ["annex_os_notfound"] = "that code is not on file. check the paper in the binder.",
        ["annex_os_search_slip"] = "codes are issued at intake. your sheet is in the FIELD DATA binder, on the shelf. the reader on the side takes student cards too, if you have yours on you.",
        ["annex_os_badge"] = "insert student ID",
        ["annex_os_reader"] = "card reader",
        ["annex_os_reading"] = "reading card...",
        ["annex_os_file_title"] = "SUBJECT FILE",
        ["annex_os_ongoing"] = "ONGOING",
        // ---- the reading room (waves 1-3, 2026-08-25): explorer, papers, drawer ----
        ["annex_os_bin"] = "RECYCLE",
        ["annex_os_bin_empty"] = "nothing in here.",
        ["annex_os_skim_on"] = "skim: on",
        ["annex_os_skim_off"] = "skim: off",
        ["annex_os_read_n"] = "read {n}/{total}",
        ["annex_os_withheld_n"] = "withheld {n}",
        ["annex_os_new"] = "new",
        ["annex_os_newtag"] = "NEW",
        ["annex_os_tldr"] = "TL;DR",
        ["annex_os_prev"] = "prev",
        ["annex_os_next"] = "next",
        ["annex_os_pos"] = "{i} of {n}",
        ["annex_os_chart"] = "chart",
        ["annex_os_archivefig"] = "archive figure",
        ["annex_os_audio"] = "audio log",
        ["annex_os_play"] = "play",
        ["annex_os_scan"] = "scan",
        ["annex_os_pick"] = "pick a file.",
        ["annex_os_back"] = "back",
        ["annex_os_closed"] = "CLOSED",
        ["annex_tab_projects"] = "PROJECTS",
        ["annex_tab_fielddata"] = "FIELD DATA",
        ["annex_tab_misc"] = "MISC",
        ["annex_tab_unread"] = "unread",
        ["annex_row_terminal"] = "on the terminal",
        ["annex_row_withheld"] = "withheld",
        ["annex_turn_over"] = "turn over",
        ["annex_turn_back"] = "turn back",
        ["annex_page_of"] = "{i} / {n}",
        ["annex_drawer_label"] = "the binder drawer",
        ["annex_drawer_close"] = "put it back",
        ["annex_f_general"] = "GENERAL",
        ["annex_f_since"] = "on record since",
        ["annex_f_level"] = "level",
        ["annex_f_xp"] = "experience, lifetime",
        ["annex_f_minutes"] = "supervised minutes",
        ["annex_f_video"] = "screening minutes",
        ["annex_f_spiral"] = "focus minutes",
        ["annex_f_ach"] = "citations on file",
        ["annex_f_attend"] = "ATTENDANCE",
        ["annex_f_streak"] = "attendance streak",
        ["annex_f_perfect"] = "perfect nights",
        ["annex_f_cards"] = "cards mastered",
        ["annex_f_appstreak"] = "reporting streak",
        ["annex_f_appbest"] = "reporting streak, best",
        ["annex_f_sessions"] = "sessions opened",
        ["annex_f_devices"] = "DEVICES",
        ["annex_f_flashes"] = "exposures delivered",
        ["annex_f_bubbles"] = "targets cleared",
        ["annex_f_lockcards"] = "sentences typed",
        ["annex_f_triggers"] = "cue firings",
        ["annex_f_unit"] = "UNIT OBSERVATION",
        ["annex_f_pets"] = "pets received",
        ["annex_f_drags"] = "relocations",
        ["annex_f_flings"] = "ejections",
        ["annex_f_hides"] = "dismissals",
        ["annex_f_restores"] = "recalls from dock",
        ["annex_f_lines"] = "lines delivered",
        ["annex_f_emisessions"] = "sessions observed",
        ["annex_f_emidays"] = "days observed",
        ["annex_f_hours"] = "hours observed",
        ["campus_annex"] = "Records Annex",
        ["campus_annex_status"] = "Stairs down",
        ["campus_desc_annex"] = "Under the office. The lights are off down there. The screens are not.",
        // ---- THE STUDENT ID (2026-08-25): the furniture card, its photo chip and the spotlight.
        // The chip rows are the SHORT face (under the photo); the id_photo_* rows are the long
        // ones the spotlight prints beside it. One switch behind both - the `discord` rung.
        ["student_id_title"] = "Student ID",
        ["id_photo_pending"] = "Photo pending",
        ["id_photo_on"] = "Discord photo on",
        ["id_photo_use"] = "Use my Discord photo",
        ["id_photo_link"] = "Link Discord for my photo",
        ["id_photo_waiting"] = "Waiting on Discord...",
        ["id_chip_on"] = "Photo on",
        ["id_chip_use"] = "Use Discord photo",
        ["id_chip_link"] = "Link Discord",
        ["id_chip_wait"] = "Waiting...",
        ["id_photo_hint_app"] = "Opens the Discord link-up in the app, then your photo goes on the card and on campus.",
        ["id_photo_hint_web"] = "Sends you to Connections to link Discord, then straight back here with the photo on.",
        ["id_photo_hint_off"] = "Your ghost on campus wears this photo too. Tap to take it down (your name stays).",
        ["id_photo_failed"] = "Discord did not pick up. Try again in a minute.",
        ["id_photo_day"] = "Photo day",
        ["id_no"] = "Student no.",
        ["id_no_temp"] = "temp",
        ["id_enrolled"] = "Enrolled",
        ["id_homeroom"] = "Homeroom",
        ["id_issued_at"] = "Issued at",
        ["id_front_desk"] = "Front desk",
        ["id_stat_semester"] = "Term",
        ["id_stat_streak"] = "Attendance streak",
        ["id_stat_perfect"] = "Perfect days",
        ["id_stat_stamps"] = "Stamps of 100",
        ["id_stat_best"] = "S days",
        ["id_year"] = "Year",
        ["id_grade_tier"] = "Grade tier",
        ["id_to_go"] = "{n} to go",
        ["id_reinked"] = "Re-inked",
        ["id_flip"] = "Tap the card to turn it over. Esc to put it back.",
        ["id_back_lost"] = "Lost it? Ask at the front desk. The second one costs you a stamp.",
        ["id_back_valid"] = "Good for as long as the lights are on.",
        ["id_records_line"] = "Records: {n} of {m} cards mastered",
        ["id_open_records"] = "Open Records",
        ["id_spot_close"] = "Close",
        // ---- the front office sheet (shell/settings.js): section titles, per-host blurbs, folds --
        ["settings_ceilings_head"] = "App ceilings",
        ["settings_ceilings_note_app"] = "Set in the app and shown here so you know what the school has to work with.",
        ["settings_device_head"] = "This device",
        ["settings_device_note"] = "Sound and motion for this browser, on this phone or PC. Nothing here leaves the device.",
        ["settings_master_volume"] = "Master volume",
        ["settings_master_volume_hint"] = "One dial over every sound the school makes.",
        ["settings_motion"] = "Motion",
        ["settings_motion_hint"] = "Reduced keeps the room still. Off cuts every animation the school can cut.",
        ["settings_motion_off"] = "Off",
        ["settings_motion_reduced"] = "Reduced",
        ["settings_motion_full"] = "Full",
        ["settings_distraction_head"] = "Distraction",
        ["settings_channels_head"] = "Channel ceilings",
        ["settings_channels_note"] = "A class may use less than these. Never more.",
        ["settings_sound_head"] = "Sound",
        ["settings_lessons_head"] = "Lessons",
        ["settings_mascot_head"] = "Mascot",
        ["emi_bubble_hold_label"] = "Speech bubble time",
        ["emi_bubble_hold_hint"] = "How long her lines stay up before she lets them go. Questions always wait for an answer.",
        ["emi_bubble_hold_quick"] = "Quick",
        ["emi_bubble_hold_normal"] = "Normal",
        ["emi_bubble_hold_long"] = "Long",
        ["emi_bubble_hold_extra"] = "Extra long",
        ["settings_game_nothing"] = "Nothing to configure - this class runs on the globals.",
        ["settings_sum_volume"] = "Volume {v}",
        ["settings_sum_motion"] = "Motion {v}",
        ["settings_sum_online_on"] = "Online on",
        ["settings_sum_online_off"] = "Online off",
        ["settings_sum_intensity"] = "Intensity {v}",
        ["settings_sum_guard"] = "Guard {v}",
        ["settings_sum_caps_all"] = "All at 100%",
        ["settings_sum_caps_low"] = "Lowest: {name} {v}",
        ["settings_sum_muted"] = "Muted",
        ["settings_sum_sound"] = "On{sep}Music {v}",
        ["settings_sum_tutorials_on"] = "Tutorials on",
        ["settings_sum_tutorials_off"] = "Tutorials skipped",
        ["settings_sum_board"] = "Board {v}",
        ["settings_sum_keys"] = "{n} keys",
        ["settings_sum_key_one"] = "1 key",
        ["settings_sum_nothing"] = "Nothing to set",
        // ---- THE ACCOUNT CHIP (2026-08-25): a host slot the web build fills (init.account); the desktop
        // never sends it, so these rows are here for the mirror law and mod skins only.
        ["account_menu"] = "Account",
        ["account_signed_in_as"] = "Signed in as",
        ["account_open_card"] = "Open my card",
        ["account_profile"] = "Profile",
        // THE FRONT GATE (2026-09-03): the third account verb, the way back to the CC Labs site.
        // Web/activity hosts only (they alone list "dashboard" in account.actions); mirrored here
        // so a mod can re-voice it, same as the other four rows.
        ["account_dashboard"] = "Front Gate",
        ["account_dashboard_hint"] = "back to CC Labs",
        ["account_sign_out"] = "Sign out",

        // THE LOCKER (2026-08-28): RM 004 + the booth arrival beat and the purchase toast verbs.
        // Mirrors of the page EN strings in core/lexicon.js so a mod lexicon.json can override them.
        ["booth_alley_hint"] = "The lit window is down at the end of the row.",
        ["booth_put_it_on"] = "Put it on",
        ["booth_hang_it"] = "Hang it up",
        // THE HOLDINGS TRAY (counter shortcut wave, 2026-08-30). The tray on the booth's sill
        // lists the consumables the player is carrying. There is no "2 of 3" row: the count is
        // built as "2/3" by concatenation, the way prize_held and prize_short already are.
        // The two passive lines are the honest half of the feature - the one consumable on the
        // shelf, late_slip, has no manual verb at all (ArcademyEconomy.ConsumeLateSlip burns it
        // inside the attendance credit), so the row says so instead of growing a dead button.
        // All four are well inside MergeModTable's 96-char skin cap (trap 26).
        ["booth_holdings"] = "What you are holding",
        ["booth_hold_none"] = "Nothing in your pockets tonight. The shelf is through the window.",
        ["booth_hold_late_slip"] = "It files itself the night you miss one. Nothing to press.",
        ["booth_hold_passive"] = "It spends itself the moment it is needed.",
        // The two wayfinding plates in the alley (shell/alleysign.js): the booth's
        // right-hand wall points at RM 004 and the Locker's left wall points back.
        // Rows of their own, not a re-use of the room cards, because a sign names a
        // DIRECTION and a card names a room. The sheet sets both in block caps.
        ["alley_sign_locker"] = "Locker room",
        ["alley_sign_locker_aria"] = "Go to the Locker room",
        ["alley_sign_counter"] = "Prize counter",
        ["alley_sign_counter_aria"] = "Go back to the Prize Counter",
        ["campus_room_locker"] = "The Locker",
        ["locker_sign"] = "Locker",
        ["locker_status"] = "Yours",
        ["locker_tip"] = "Your own door in the row. Everything you have won is behind it.",
        ["locker_kicker"] = "The Locker",
        ["locker_hot"] = "Your locker",
        ["locker_title"] = "The Locker",
        ["locker_sub"] = "Room 004. Nobody else has the combination.",
        ["locker_wear"] = "Wear",
        ["locker_card"] = "Card",
        ["locker_campus"] = "Campus",
        ["locker_desk"] = "Desk",
        ["locker_bag"] = "In your bag",
        ["locker_always"] = "Always on",
        ["locker_outfit_standard"] = "The usual",
        ["locker_outfit_varsity"] = "Varsity jacket",
        ["locker_outfit_labcoat"] = "Lab coat",
        ["locker_outfit_cheer"] = "Cheer uniform",
        ["locker_outfit_swim"] = "Swim team",
        ["locker_frame_plain"] = "Plain",
        ["locker_frame_gold"] = "Gold",
        ["locker_frame_navy"] = "Navy",
        ["locker_toy_auto"] = "Let the desk choose",
        ["locker_toy_spinner"] = "Spinner",
        ["locker_toy_globe"] = "Snow globe",
        ["locker_toy_lamp"] = "Lava lamp",
        ["locker_toy_beads"] = "Beads",
        ["locker_selected"] = "On",
        ["locker_held"] = "x{n}",
        ["locker_empty"] = "Nothing in here yet. The counter is one window up.",
        ["locker_more_at_counter"] = "{n} more at the counter",
        ["locker_ring_bell"] = "Ring it",
        ["locker_signpost"] = "Outfits, frames and campus looks live in The Locker now. RM 004.",
        ["locker_signpost_go"] = "Open The Locker",
        ["locker_unlock_hint"] = "{tok}2 at the counter",
        ["locker_open"] = "Open Locker",
        // ---- EMI's stuck-hints (Daily Trigger, 2026-08-30) ----------------------------
        // The owner amended the "no mid-class mascot speech" law (arcademy/CLAUDE.md traps
        // 90 and 97) for one narrow channel: when the board says the player is beaten, EMI
        // may ASK whether they want a hand. Two offers a class, never a hint she was not
        // invited to give. Offer 1 names the band today's answer came out of (free); offer
        // 2 places one letter and caps the class at A via the existing `stuck_rescue`
        // assist, which the report card already explains without a row of its own.
        //
        // These are ordinary call-site keys. The CLASS resolves them and hands finished
        // sentences to emi/asks.js, which has no lexicon - so `{cat}` below is substituted
        // page-side with one of the dt_cat_* rows, never here.
        ["dt_help_ask_cat"] = "psst. i might know this one.",
        ["dt_help_chip_cat_yes"] = "spill",
        ["dt_help_chip_no"] = "nah",
        ["dt_help_yes_cat"] = "smells like a {cat} word to me.",
        ["dt_help_no_cat"] = "respect. i'll just sit here knowing it.",
        ["dt_help_ask_letter"] = "i could hold one letter for you.",
        ["dt_help_chip_letter_yes"] = "ok",
        ["dt_help_yes_letter"] = "boop. that one's yours now.",
        ["dt_help_no_letter"] = "ok. my letter and i will practice waiting.",
        // The nine band names. The KEY is the contract: it is `dt_cat_` plus the `cat` of a
        // THEME_GROUPS band in games/daily-trigger/words-answers.js (plus `common` for the
        // tiny ordinary-English band), so renaming a band there orphans its row here.
        ["dt_cat_trance"] = "spirally",
        ["dt_cat_training"] = "training arc",
        ["dt_cat_submission"] = "yes ma'am",
        ["dt_cat_denial"] = "not yet",
        ["dt_cat_bimbo"] = "glittery",
        ["dt_cat_arcade"] = "hometown",
        ["dt_cat_school"] = "classroom",
        ["dt_cat_melt"] = "melty",
        ["dt_cat_common"] = "civilian",
    };

    /// <summary>The mockup's owner-approved tokens (BUILD-CONTRACT §10). A mod overrides them via
    /// <c>resources/arcademy/palette.json</c>; unknown keys in that file are ignored.</summary>
    internal static readonly Dictionary<string, string> NeutralPalette = new(StringComparer.Ordinal)
    {
        ["ground"] = "#14142B",
        ["navy"] = "#1A1A2E",
        ["panel"] = "#252542",
        ["ink"] = "#F2EBDD",
        ["pink"] = "#FF69B4",
        ["lavender"] = "#B8A6E8",
        ["gold"] = "#F0C24B",
    };
}
