#!/usr/bin/env node
// SP-127 — the structural walk. Committed BEFORE any counting (plan.md §1.2).
//
// WHY THIS FILE EXISTS. This port has been wrong about an upstream count five times
// (haptic sites 8 -> 13 -> 14 -> 18, For You Feed 3 -> 9) and every correction came from
// WIDENING THE UNIVERSE, never from reading harder. Each of the five searches ran over a file
// LIST somebody assembled by hand. SP-125's own plan forbade hand-assembled lists and then
// contained one, because a prose promise is not a control: the author who writes the promise is
// the author who then writes the list.
//
// So the walk is code, not a promise. The reviewer can re-run it.
//
// THE TWO STRUCTURAL PROPERTIES, and they are the whole point:
//   1. The ONLY positional input is a ROOT DIRECTORY. There is no file-list parameter, so a
//      hand-assembled list is NOT EXPRESSIBLE here.
//   2. The ONLY exclusions are the frozen GENERATED_BYTES patterns below. There is no
//      --exclude flag and no name-based exclusion, so no source file can be dropped by name.
//      The pattern set is printed on every run, so a reader always sees what was skipped.
//
// Usage (all paths are repo-relative; run from the repo root):
//   node spine-tasks/SP-127-trainer-card-census/walk.mjs <root> [--lines] [--ext] [--bytes]
//   node spine-tasks/SP-127-trainer-card-census/walk.mjs <root> --match <regex> [--flags gi]
//   node spine-tasks/SP-127-trainer-card-census/walk.mjs <root> --match <regex> --hits
//
// Every count printed by this script is reported in the census beside the exact invocation that
// produced it. A number with no invocation beside it is a defect in the census.

import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, relative, sep, extname } from 'node:path';

// Frozen. Every entry is a pattern over GENERATED bytes. No source file is excluded by name.
const GENERATED_BYTES = {
  directories: ['bin', 'obj', '.git', '__pycache__', 'node_modules'],
  // `.git` also appears as a FILE in a git worktree (it holds `gitdir: ...`). That is git's own
  // metadata, not source, so it is named exactly rather than by suffix — a `.git` suffix rule
  // would be a name-based exclusion that could reach a real file.
  exactFileNames: ['.git'],
  fileSuffixes: ['.log', '.binlog', '.etlx', '.speedscope.json'],
  fileContains: ['.nettrace'],
};

function isExcludedDirectory(name) {
  return GENERATED_BYTES.directories.includes(name);
}

function isExcludedFile(name) {
  if (GENERATED_BYTES.exactFileNames.includes(name)) return true;
  if (GENERATED_BYTES.fileSuffixes.some((s) => name.endsWith(s))) return true;
  if (GENERATED_BYTES.fileContains.some((s) => name.includes(s))) return true;
  return false;
}

/** Recursive walk. The root is a DIRECTORY; every file under it is visited unless a frozen
 *  generated-bytes pattern matches. Returns repo-relative POSIX paths, sorted. */
function walk(repoRoot, absRoot) {
  const out = [];
  const symlinks = [];
  const stack = [absRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      throw new Error(`unreadable directory ${dir}: ${err.message}`);
    }
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isSymbolicLink()) {
        // NOT FOLLOWED: a link pointing out of the tree would corrupt the count. It is RECORDED
        // and printed in the summary of every run, so a skipped entry is never silent. The
        // earlier comment here promised a summary that did not exist — a comment that overstates
        // its code is the exact defect class three of the last four waves were about.
        symlinks.push(relative(repoRoot, full).split(sep).join('/'));
        continue;
      }
      if (entry.isDirectory()) {
        if (!isExcludedDirectory(entry.name)) stack.push(full);
        continue;
      }
      if (!entry.isFile()) continue;
      if (isExcludedFile(entry.name)) continue;
      out.push(relative(repoRoot, full).split(sep).join('/'));
    }
  }
  out.sort();
  symlinks.sort();
  return { files: out, symlinks };
}

/** Second, independent count for the same root: what git tracks. A disagreement means untracked
 *  bytes (or ignored bytes) and is REPORTED, never silently reconciled. */
function gitTracked(repoRoot, rootRel) {
  try {
    const raw = execFileSync('git', ['ls-files', '--', rootRel], {
      cwd: repoRoot,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
    return raw.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
  } catch (err) {
    return null;
  }
}

function looksBinary(buf) {
  const n = Math.min(buf.length, 8192);
  for (let i = 0; i < n; i += 1) if (buf[i] === 0) return true;
  return false;
}

function findRepoRoot(start) {
  let dir = start;
  for (;;) {
    if (existsSync(join(dir, 'client', 'CcpClient.sln'))) return dir;
    const parent = join(dir, '..');
    if (parent === dir) throw new Error('repo root not found (anchor: client/CcpClient.sln)');
    dir = parent;
  }
}

function main(argv) {
  const positional = [];
  const opts = { lines: false, ext: false, bytes: false, match: null, flags: 'i', hits: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--lines') opts.lines = true;
    else if (a === '--ext') opts.ext = true;
    else if (a === '--bytes') opts.bytes = true;
    else if (a === '--hits') opts.hits = true;
    else if (a === '--match') { opts.match = argv[i + 1]; i += 1; }
    else if (a === '--flags') { opts.flags = argv[i + 1]; i += 1; }
    else if (a.startsWith('--')) throw new Error(`unknown option ${a} (there is deliberately no --exclude and no file-list option)`);
    else positional.push(a);
  }
  if (positional.length !== 1) {
    throw new Error('exactly one positional argument is accepted, and it must be a DIRECTORY root');
  }

  const repoRoot = findRepoRoot(process.cwd());
  const rootRel = positional[0].replace(/\\/g, '/').replace(/\/+$/, '');
  const absRoot = join(repoRoot, rootRel);

  if (!existsSync(absRoot)) {
    console.log(`ROOT           ${rootRel}`);
    console.log('RESULT         ABSENT — this root does not exist in the tree');
    process.exitCode = 2;
    return;
  }
  if (!statSync(absRoot).isDirectory()) {
    throw new Error(`${rootRel} is not a directory; this script counts DIRECTORIES, never files`);
  }

  const { files, symlinks } = walk(repoRoot, absRoot);
  const tracked = gitTracked(repoRoot, rootRel);

  console.log(`REPO ROOT      ${repoRoot}`);
  console.log(`ROOT           ${rootRel}  (walked recursively)`);
  console.log(`EXCLUSIONS     dirs=${GENERATED_BYTES.directories.join(',')}  ` +
              `names=${GENERATED_BYTES.exactFileNames.join(',')}  ` +
              `suffixes=${GENERATED_BYTES.fileSuffixes.join(',')}  ` +
              `contains=${GENERATED_BYTES.fileContains.join(',')}   [generated bytes only]`);
  console.log(`SYMLINKS       ${symlinks.length} not followed` +
              (symlinks.length > 0 ? `: ${symlinks.join(' ')}` : ''));

  if (opts.match) {
    const re = new RegExp(opts.match, opts.flags);
    let scanned = 0;
    let binariesSkipped = 0;
    const matched = [];
    for (const f of files) {
      const buf = readFileSync(join(repoRoot, f));
      if (looksBinary(buf)) { binariesSkipped += 1; continue; }
      scanned += 1;
      const text = buf.toString('utf8');
      const lines = text.split(/\r?\n/);
      const hitLines = [];
      for (let i = 0; i < lines.length; i += 1) {
        re.lastIndex = 0;
        if (re.test(lines[i])) hitLines.push(i + 1);
      }
      if (hitLines.length > 0) matched.push({ f, hitLines });
    }
    console.log(`PATTERN        /${opts.match}/${opts.flags}`);
    console.log(`TEXT SCANNED   ${scanned} files   BINARY SKIPPED ${binariesSkipped}`);
    console.log(`MATCHED FILES  ${matched.length}`);
    console.log(`MATCHED LINES  ${matched.reduce((a, m) => a + m.hitLines.length, 0)}`);
    console.log('---');
    for (const m of matched) {
      if (opts.hits) console.log(`${m.f}:${m.hitLines.join(',')}`);
      else console.log(m.f);
    }
    return;
  }

  console.log(`FILES (walk)   ${files.length}`);
  if (tracked === null) console.log('FILES (git)    git ls-files unavailable');
  else {
    console.log(`FILES (git)    ${tracked.length}`);
    const walkSet = new Set(files);
    const gitSet = new Set(tracked);
    const untracked = files.filter((f) => !gitSet.has(f));
    const missing = tracked.filter((f) => !walkSet.has(f));
    if (untracked.length === 0 && missing.length === 0) console.log('AGREEMENT      the two counts agree — no untracked bytes in this tree');
    else {
      console.log(`DISAGREEMENT   walk-only=${untracked.length} git-only=${missing.length}  [reported, never reconciled]`);
      for (const f of untracked) console.log(`  walk-only  ${f}`);
      for (const f of missing) console.log(`  git-only   ${f}`);
    }
  }

  if (opts.ext) {
    const byExt = new Map();
    for (const f of files) {
      const e = extname(f).toLowerCase() || '(none)';
      byExt.set(e, (byExt.get(e) ?? 0) + 1);
    }
    console.log('BY EXTENSION   ' + [...byExt.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([e, n]) => `${e}=${n}`).join(' '));
  }

  if (opts.bytes) {
    let total = 0;
    for (const f of files) total += statSync(join(repoRoot, f)).size;
    console.log(`TOTAL BYTES    ${total}`);
  }

  console.log('---');
  if (opts.lines) {
    let total = 0;
    for (const f of files) {
      const buf = readFileSync(join(repoRoot, f));
      if (looksBinary(buf)) { console.log(`${f}\t(binary)`); continue; }
      const text = buf.toString('utf8');
      const n = text.length === 0 ? 0 : text.replace(/\n$/, '').split('\n').length;
      total += n;
      console.log(`${f}\t${n}`);
    }
    console.log(`TOTAL LINES    ${total}   (text files only)`);
  } else {
    for (const f of files) console.log(f);
  }
}

try {
  main(process.argv.slice(2));
} catch (err) {
  console.error(`walk.mjs: ${err.message}`);
  process.exitCode = 1;
}
