using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Xunit;

namespace CcpClient.Tests;

/// <summary>
/// The pin under <c>client/docs/goon-game-census.md</c>.
///
/// <para><b>Why this exists.</b> The board row for the Goon Game claimed 25 files in
/// <c>Services/GoonGame/</c> and 184 in <c>Resources/web/goon/</c>, and <b>both numbers are exactly
/// right</b>. The census's finding is about what they COUNT: the duel a user plays is the JavaScript
/// in the payload, and 20 of the 25 C# files are a parallel reference implementation reachable only
/// from two developer CLI flags. A guard that only checked the document against itself would have
/// passed on that, so — following <see cref="HapticSiteCensusTests"/>'s rule rather than inventing a
/// second convention — the document is the DATA and this file is the LOGIC. The directory roots and
/// the needles live HERE and every count is RE-DERIVED from the shipping bytes on every run.</para>
///
/// <para><b>What this guard does that the trainer-card pin did not, and why.</b>
/// <c>TrainerCardCensusTests</c> pinned citation PATHS and matched an expression anywhere in the
/// file, so its suite was green while three of its own citations were wrong by 3 and 5 lines. Here
/// <see cref="EveryPinnedCitation_IsOnTheExactLineItClaims"/> reads <b>the exact line</b> the census
/// claims and requires the needle to be on it, so a citation that drifts by ONE line reds the suite.
/// <see cref="EveryNumberInTheCensus_IsPinnedOrDisclaimed"/> then closes the other half: every
/// numeric token in the document must appear in a §10 pin table or be named in §9's "does not prove"
/// section. Its exclusions are enumerated CLASSES (citation forms, section refs, divergence ids,
/// packet ids, ISO dates, versions, hex) — never a list of individual literals, because a literal
/// list is an escape hatch that eats the property the fact exists for.</para>
///
/// <para><b>Non-vacuous design.</b> The repo root is anchored on <c>client/CcpClient.sln</c>. A
/// missing root, a missing census and a missing <c>ConditioningControlPanel/</c> are hard FAILURES,
/// never skips; a half-present reference tree fails too. Every filesystem predicate lives in a
/// helper rather than in a fact body, so no fact carries a silencing shape. The fixture facts at the
/// bottom pin the walker, the parser, the comment stripper and the number sweep against synthetic
/// inputs, so none of this rests on today's tree happening to agree.</para>
/// </summary>
public sealed class GoonGameCensusTests
{
    private const string CensusRelativePath = "client/docs/goon-game-census.md";

    private static readonly string[] RepoAnchorParts = ["client", "CcpClient.sln"];
    private static readonly string[] CensusParts = ["client", "docs", "goon-game-census.md"];
    private static readonly string[] WpfRootParts = ["ConditioningControlPanel"];
    private static readonly string[] PortRootParts = ["client", "src", "CcpClient.Desktop"];

    /// <summary>The surface, as DIRECTORIES searched whole and recursively, every extension. NOT a
    /// file list — a file list is exactly how the haptic census lost <c>VideoService.Browser.cs</c>
    /// twice and how five upstream counts went wrong before this one.</summary>
    private static readonly string[] SurfaceDirectory = ["Services/GoonGame"];

    /// <summary>Generated bytes, skipped by the walker. Every entry is a pattern over BUILD OUTPUT.
    /// No source file is excluded by name, anywhere, for any reason.</summary>
    private static readonly HashSet<string> GeneratedDirectories =
        new(StringComparer.OrdinalIgnoreCase) { "bin", "obj", ".git", "__pycache__", "node_modules" };

    /// <summary>Where the closure starts. The user-facing entry points both call
    /// <c>GoonHostService.Launch()</c>, so this file is the whole seed set (census §1.3).</summary>
    private const string ShippedPathSeed = "GoonHostService.cs";

    /// <summary>The four privacy verdicts (census §6.6), pinned at the START of the answer with
    /// inline-code spans stripped. Counting non-blank answers would leave Q3 and Q4 — the two
    /// owner-flagged findings — free to be softened to NO while staying green.</summary>
    private static readonly (string Id, string Verdict)[] PrivacyVerdicts =
    [
        ("Q1", "YES"),
        ("Q2", "YES"),
        ("Q3", "YES"),
        ("Q4", "THE MICROPHONE"),
    ];

    /// <summary>The closed label vocabulary from the census's §4 decision rule.</summary>
    private static readonly string[] Labels = ["COVERED", "PARTIAL", "GAP", "OWNER-GATED"];

    /// <summary>Every owner-flagged section the census must carry. An owner decision that quietly
    /// loses its section is the failure this packet was told to prevent.</summary>
    private static readonly string[] OwnerFlaggedHeadings =
    [
        "### 6.1", "### 6.2", "### 6.3", "### 6.4", "### 6.5", "### 6.6", "### 6.7",

        // §6.8 is deliberately NOT a decision section — it is the contract-silent roots question,
        // which is why DecisionSections below counts §6.1-§6.5 only. Pinned here so it cannot be
        // dropped silently: it is the one item in §6 the owner queue would otherwise lose.
        "### 6.8",
    ];

    private readonly ITestOutputHelper _output;

    public GoonGameCensusTests(ITestOutputHelper output) => _output = output;

    // ======================================================================================
    // Counts, re-derived from the shipping bytes.
    // ======================================================================================

    [Fact]
    public void EveryDirectoryCount_IsRederivedFromTheShippingBytes_NotReadOutOfTheCensus()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 10.1");
        Assert.NotEmpty(declared);

        var mismatches = new List<string>();
        foreach (var (relative, claimed) in declared)
        {
            var actual = CountFilesUnder(reference.Wpf, relative);
            _output.WriteLine($"{relative}: census {claimed}, walked {actual}");
            if (!int.TryParse(claimed, out var expected) || expected != actual)
                mismatches.Add($"{relative}: census says {claimed}, the tree holds {actual}");
        }

        Assert.True(mismatches.Count == 0,
            "census §10.1 disagrees with the shipping bytes:" + Environment.NewLine
            + string.Join(Environment.NewLine, mismatches));
    }

    [Fact]
    public void TheSurfaceFileSet_IsExactlyWhatTheWalkFinds()
    {
        var reference = RequireReference();
        var declared = ParseIdPathTable(reference.Census, "### 10.2");
        var walked = RelativeFilesUnder(reference.Wpf, SurfaceDirectory[0]);

        Assert.Equal(walked.OrderBy(p => p, StringComparer.Ordinal).ToList(),
                     declared.Keys.OrderBy(p => p, StringComparer.Ordinal).ToList());
    }

    /// <summary>
    /// THE HEADLINE, re-derived. The census claims five of the twenty-five files sit behind the
    /// user-facing door and twenty are reachable only from two developer flags. This recomputes the
    /// transitive closure from <c>GoonHostService.cs</c> over DECLARED TYPE NAMES — not over file
    /// names and not over the token "Goon", both of which under-report: a file-name sweep misses
    /// <c>ConsentSheetMsg</c>, which is what made an earlier draft of the census say FOUR.
    /// </summary>
    [Fact]
    public void TheShippedUserPathSplit_IsRederivedByAClosureOverDeclaredTypes()
    {
        var reference = RequireReference();
        var declared = ParseIdPathTable(reference.Census, "### 10.2");
        var closure = ShippedPathClosure(reference.Wpf);

        _output.WriteLine("closure: " + string.Join(", ", closure.OrderBy(c => c, StringComparer.Ordinal)));

        var claimedHost = declared.Where(kv => kv.Value.Equals("host", StringComparison.OrdinalIgnoreCase))
                                  .Select(kv => kv.Key)
                                  .OrderBy(p => p, StringComparer.Ordinal)
                                  .ToList();

        Assert.Equal(closure.OrderBy(c => c, StringComparer.Ordinal).ToList(), claimedHost);
    }

    [Fact]
    public void TheLocationsOutsideTheRowsTwoDirectories_AllExistInTheShippingTree()
    {
        var reference = RequireReference();
        var declared = ParseIdPathTable(reference.Census, "### 10.3");
        Assert.NotEmpty(declared);

        var missing = MissingShippingPaths(reference.Wpf, declared.Keys);
        Assert.True(missing.Count == 0,
            "census §10.3 names paths that are not in the shipping tree: " + string.Join(", ", missing));

        // COMPLETE, not merely existent. Four numbers in §10.4.1 and §10.6 — dev-cockpit-files,
        // design-doc-files, surface-csharp-total-files and row-share-of-surface-percent — are
        // COUNTS OF THESE ROWS, so an omitted row would understate every one of them and the
        // existence check could never notice. The set is therefore re-derived from the bytes:
        // every tracked path under ConditioningControlPanel/ whose PATH carries the surface's
        // token, minus the two directories the board row already names, minus the intake
        // voice-over family the census attributes as FOREIGN (§2.1) and counts separately as
        // intake-vo-goon-named-files.
        var derived = WalkFiles(reference.Wpf)
            .Select(f => Path.GetRelativePath(reference.Wpf, f).Replace(Path.DirectorySeparatorChar, '/'))
            .Where(rel => rel.Contains("goon", StringComparison.OrdinalIgnoreCase))
            .Where(rel => !rel.StartsWith("Services/GoonGame/", StringComparison.Ordinal)
                       && !rel.StartsWith("Resources/web/goon/", StringComparison.Ordinal)
                       && !rel.StartsWith("Resources/web/intake/", StringComparison.Ordinal))
            .OrderBy(rel => rel, StringComparer.Ordinal)
            .ToList();

        _output.WriteLine("§10.3 derived from the bytes: " + string.Join(", ", derived));

        Assert.Equal(derived, declared.Keys.OrderBy(k => k, StringComparer.Ordinal).ToList());
    }

    // ======================================================================================
    // THE REPAIR: a pin that watches the NUMBER, not the path.
    // ======================================================================================

    [Fact]
    public void EveryPinnedCitation_IsOnTheExactLineItClaims()
    {
        var reference = RequireReference();
        var rows = ParseCitationTable(reference.Census, "### 10.4", out var unparsed);
        Assert.NotEmpty(rows);
        Assert.True(unparsed.Count == 0,
            "§10.4 holds a table row that is not a citation — a narrative row in a pin table still "
            + "feeds the vocabulary, which is how §10.4 and §10.5 leaked:" + Environment.NewLine
            + string.Join(Environment.NewLine, unparsed));

        var wrong = CitationDrift(rows, relative => ReadShippingFile(reference.Wpf, relative));
        Assert.True(wrong.Count == 0,
            "census §10.4 citations that are NOT on the line they claim (this is the exact defect "
            + "that survived the earlier path-only pin):" + Environment.NewLine
            + string.Join(Environment.NewLine, wrong));
    }

    [Fact]
    public void EveryPortAnchor_IsOnTheExactLineItClaims()
    {
        var reference = RequireReference();
        var rows = ParseCitationTable(reference.Census, "### 10.5", out var unparsed);
        Assert.NotEmpty(rows);
        Assert.True(unparsed.Count == 0,
            "§10.5 holds a table row that is not a citation:" + Environment.NewLine
            + string.Join(Environment.NewLine, unparsed));

        var wrong = CitationDrift(rows, relative => ReadRepoFile(reference.Root, Path.Combine(PortRootParts) + "/" + relative));
        Assert.True(wrong.Count == 0,
            "census §10.5 port anchors that are NOT on the line they claim:" + Environment.NewLine
            + string.Join(Environment.NewLine, wrong));
    }

    /// <summary>
    /// A port anchor cited in the BODY must use the line §10.5 pins for it.
    ///
    /// <para><b>Why this exists, and why it is scoped to §10.5.</b> The pin table said
    /// <c>DtrhCapabilityProbes.cs:22</c> while three body citations still said <c>:21</c> — the
    /// same off-by-one, corrected in the pin and not swept into the prose. Neither the number sweep
    /// nor the label tally can see that: a citation is a class the number sweep deliberately
    /// EXCLUDES, so it is invisible to the one mechanism that would otherwise catch a stale
    /// restatement. A hand sweep found these; this fact means the next one does not have to.</para>
    ///
    /// <para>Scoped to §10.5 (port anchors) rather than §10.4 (WPF citations) because a port anchor
    /// is single-purpose — one declaration per file — so every body citation of it means the same
    /// thing. <c>GoonHostService.cs</c> is legitimately cited at many different lines (the census pins
    /// the count as <c>census-cites-goonhostservice-lines</c>), so the same rule over §10.4 would be
    /// noise. <b>That asymmetry is a real residual, stated rather than hidden:</b> a stale WPF
    /// citation in body prose is still only caught by pinning it.</para>
    /// </summary>
    [Fact]
    public void EveryBodyCitationOfAPortAnchor_UsesTheLineThePinTableClaims()
    {
        var census = RequireReference().Census;
        var pinned = ParseCitationTable(census, "### 10.5");
        Assert.NotEmpty(pinned);

        var allowed = pinned
            .GroupBy(r => Path.GetFileName(r.Path), StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.Select(r => r.Line).ToHashSet(), StringComparer.Ordinal);

        var wrong = new List<string>();
        var lineNumber = 0;
        foreach (var raw in census.Split('\n'))
        {
            lineNumber++;
            foreach (Match m in Regex.Matches(raw, @"(?<file>[A-Za-z0-9_.\-]+\.(?:cs|axaml)):(?<line>\d+)"))
            {
                var file = m.Groups["file"].Value;
                if (!allowed.TryGetValue(file, out var lines)) continue;
                var cited = int.Parse(m.Groups["line"].Value, CultureInfo.InvariantCulture);
                if (!lines.Contains(cited))
                    wrong.Add($"census:{lineNumber} cites {file}:{cited}, but §10.5 pins that anchor at "
                        + string.Join("/", lines.OrderBy(l => l)));
            }
        }

        Assert.True(wrong.Count == 0,
            "a port anchor is cited in the body at a line the pin table does not claim:" + Environment.NewLine
            + string.Join(Environment.NewLine, wrong));
    }

    [Fact]
    public void TheFractionsThatCarryTheFindings_RederiveExactly_WithNoThreshold()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 10.6");
        Assert.NotEmpty(declared);

        var surfaceFiles = RelativeFilesUnder(reference.Wpf, SurfaceDirectory[0]);
        var closure = ShippedPathClosure(reference.Wpf);
        var hostLines = closure.Sum(f => LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/{f}"));
        var totalLines = surfaceFiles.Sum(f => LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/{f}"));

        var outside = ParseIdPathTable(reference.Census, "### 10.3").Keys
            .Count(p => p.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                     || p.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase));
        var transfer = CountFilesUnder(reference.Wpf, "Services/Media/Transfer");
        var payload = RelativeFilesUnder(reference.Wpf, "Resources/web/goon");
        var vendored = payload.Count(p => p.StartsWith("vendor/", StringComparison.Ordinal));
        var harness = payload.Count(p => p.StartsWith("test/", StringComparison.Ordinal)
                                      || p.Equals("package.json", StringComparison.Ordinal));

        var actual = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["goongame-total-files"] = surfaceFiles.Count.ToString(),
            ["goongame-host-path-files"] = closure.Count.ToString(),
            ["goongame-reference-files"] = (surfaceFiles.Count - closure.Count).ToString(),
            ["goongame-host-path-share-percent"] = Percent(closure.Count, surfaceFiles.Count),
            ["goongame-total-lines"] = totalLines.ToString(),
            ["goongame-host-path-lines"] = hostLines.ToString(),
            ["goongame-host-path-line-share-percent"] = Percent(hostLines, totalLines),
            ["surface-csharp-total-files"] = (surfaceFiles.Count + outside + transfer).ToString(),
            ["row-share-of-surface-percent"] = Percent(surfaceFiles.Count, surfaceFiles.Count + outside + transfer),
            ["payload-total-files"] = payload.Count.ToString(),
            ["payload-this-surface-files"] = (payload.Count - vendored).ToString(),
            ["payload-vendored-files"] = vendored.ToString(),
            ["payload-this-surface-share-percent"] = Percent(payload.Count - vendored, payload.Count),
            ["payload-served-files"] = (payload.Count - harness).ToString(),
            ["payload-harness-files"] = harness.ToString(),
            ["payload-total-bytes"] = TotalBytes(reference.Wpf, "Resources/web/goon").ToString(),

            // §10.6's last two keys. EveryDuelElement_HasAShippedPortModule also derives them, for
            // a different property (that the two counts are EQUAL). They are derived here as well
            // rather than excused from the reverse check: an exclusion list is the escape hatch,
            // and a second independent derivation of the same number is redundancy, not waste.
            ["duel-elements"] = DuelElementCodes(reference.Wpf).Count.ToString(),
            ["duel-elements-with-port-module"] = PortElementAnchors(reference.Census, reference.Wpf).ToString(),
        };

        // THROUGH THE SHARED HELPER, and the reason is a hole that shipped. This fact used to
        // hand-roll its own mismatch loop over `actual` only, so a row DECLARED in §10.6 that
        // nothing re-derives passed silently — and §10.6 is the largest pin table, holding the
        // headline fractions. AssertAgrees already carried the reverse check ("census pins it,
        // nothing re-derives it"), which is exactly why §10.4.1 caught the same injection and this
        // one did not. The property existed and was lost by re-implementing instead of reusing.
        AssertAgrees(declared, actual, "§10.6");
    }

    /// <summary>The line totals and group counts the census states in PROSE. The earlier pin covered
    /// its tables and left its prose numbers free; these are the ones a reader quotes. All but one
    /// re-derive from the shipping tree; <c>census-cites-goonhostservice-lines</c> re-derives from
    /// the census, because its subject IS the document (the same justification as the label
    /// tally).</summary>
    [Fact]
    public void EveryDerivedLineCountStatedInProse_RederivesFromTheBytes()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 10.4.1");
        Assert.NotEmpty(declared);

        var surfaceFiles = RelativeFilesUnder(reference.Wpf, SurfaceDirectory[0]);
        var closure = ShippedPathClosure(reference.Wpf);
        var totalLines = surfaceFiles.Sum(f => LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/{f}"));
        var hostLines = closure.Sum(f => LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/{f}"));

        var outside = ParseIdPathTable(reference.Census, "### 10.3").Keys.ToList();
        var cockpit = outside.Where(p => p.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                                      || p.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase)).ToList();
        var docs = outside.Where(p => p.EndsWith(".md", StringComparison.OrdinalIgnoreCase)).ToList();
        var transferLines = SumLinesUnder(reference.Wpf, "Services/Media/Transfer");
        var payload = RelativeFilesUnder(reference.Wpf, "Resources/web/goon");
        var harness = payload.Count(p => p.StartsWith("test/", StringComparison.Ordinal)
                                      || p.Equals("package.json", StringComparison.Ordinal));

        var actual = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["goongame-reference-lines"] = (totalLines - hostLines).ToString(),
            ["goongame-reference-share-percent"] = Percent(surfaceFiles.Count - closure.Count, surfaceFiles.Count),
            ["rounds-lines"] = SumLinesUnder(reference.Wpf, $"{SurfaceDirectory[0]}/Rounds").ToString(),
            ["goon-cache-bridge-lines"] = LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/GoonCacheBridge.cs").ToString(),
            ["goon-signaling-client-lines"] = LineCount(reference.Wpf, $"{SurfaceDirectory[0]}/GoonSignalingClient.cs").ToString(),
            ["dev-cockpit-files"] = cockpit.Count.ToString(),
            ["dev-cockpit-lines"] = cockpit.Sum(p => LineCount(reference.Wpf, p)).ToString(),
            ["media-transfer-lines"] = transferLines.ToString(),
            ["design-doc-files"] = docs.Count.ToString(),
            ["design-doc-lines"] = docs.Sum(p => LineCount(reference.Wpf, p)).ToString(),
            ["discord-contract-lines"] = LineCount(reference.Wpf, "docs/GOON_DISCORD_CONTRACT.md").ToString(),
            ["surface-csharp-total-lines"] =
                (totalLines + cockpit.Sum(p => LineCount(reference.Wpf, p)) + transferLines).ToString(),
            ["payload-served-share-percent"] = Percent(payload.Count - harness, payload.Count),
            ["shared-vendor-tree-files"] = CountFilesUnder(reference.Wpf, "Resources/web/vendor").ToString(),
            ["intake-vo-goon-named-files"] = RelativeFilesUnder(reference.Wpf, "Resources/web/intake")
                .Count(p => p.Contains("goon", StringComparison.OrdinalIgnoreCase)).ToString(),
            ["ice-timeout-seconds"] = (MillisecondConstant(reference.Wpf,
                "Services/GoonGame/GoonContracts.cs", "IceTimeoutMs") / 1000).ToString(),
            ["voice-note-max-seconds"] = (MillisecondConstant(reference.Wpf,
                "docs/GOON_VOICE_PLAN.md", "VN_MAX_MS") / 1000).ToString(),

            // The one key here derived from the CENSUS rather than the shipping tree, and it is
            // legitimate for the same reason the label tally is: its subject IS the document. It
            // backs §10.7's justification for scoping the port-anchor rule to §10.5, and an earlier
            // draft stated it as "forty" — unpinned, imprecise and wrong, in the one document whose
            // whole subject is that failure.
            ["census-cites-goonhostservice-lines"] = Regex
                .Matches(reference.Census, @"GoonHostService\.cs:\d+")
                .Select(m => m.Value)
                .Distinct(StringComparer.Ordinal)
                .Count()
                .ToString(),
        };

        AssertAgrees(declared, actual, "§10.4.1");
    }

    [Fact]
    public void ThePayloadExtensionHistogram_RederivesFromTheBytes()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 10.4.2");
        Assert.NotEmpty(declared);

        var payload = RelativeFilesUnder(reference.Wpf, "Resources/web/goon");
        string Bucket(string p)
        {
            var ext = Path.GetExtension(p).ToLowerInvariant();
            return ext.Length == 0 ? "payload-no-extension" : "payload-" + ext[1..];
        }

        var actual = payload.GroupBy(Bucket)
            .ToDictionary(g => g.Key, g => g.Count().ToString(), StringComparer.Ordinal);

        AssertAgrees(declared, actual, "§10.4.2");
        Assert.Equal(payload.Count, actual.Values.Sum(int.Parse));
    }

    /// <summary>The nine duel elements, re-derived on both sides: the frozen upstream enum and a
    /// shipped port module for each. Counting only the census's own rows would let the claim
    /// survive an element being added upstream with no port answer.</summary>
    [Fact]
    public void EveryDuelElement_HasAShippedPortModule()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 10.6");
        var codes = DuelElementCodes(reference.Wpf);
        var elements = codes.Count;
        var anchors = PortElementAnchors(reference.Census, reference.Wpf);

        _output.WriteLine($"GoonElement members: {elements}; port anchors in §10.5: {anchors}");
        Assert.Equal(declared["duel-elements"], elements.ToString());
        Assert.Equal(declared["duel-elements-with-port-module"], anchors.ToString());
        Assert.Equal(elements, anchors);

        // The FROZEN wire codes. The protocol calls them append-only, so a renumbering upstream is a
        // wire break and must red the suite rather than drift quietly through this document.
        AssertAgrees(
            ParseKeyValueTable(reference.Census, "### 10.4.4"),
            codes.ToDictionary(kv => $"element-code-{kv.Key}", kv => kv.Value, StringComparer.Ordinal),
            "§10.4.4");
    }

    // ======================================================================================
    // THE OTHER HALF OF THE PIN: no number in the census escapes.
    // ======================================================================================

    /// <summary>
    /// Every numeric token in the census must be pinned in §10 or named in §9. This is the property
    /// the earlier census lost — it published 96.5% while its guard asserted only <c>&gt; 0.90</c> — and it is
    /// the only mechanism that would have caught it.
    ///
    /// <para><b>The exclusions are CLASSES, enumerated here in code, never a list of literals.</b>
    /// A literal-exclusion list is an escape hatch that eats the property, so the day a class cannot
    /// be kept honest is the day this fact is reported as a finding rather than weakened.</para>
    /// </summary>
    [Fact]
    public void EveryNumberInTheCensus_IsPinnedOrDisclaimed()
    {
        var reference = RequireReference();
        var pinned = PinnedNumbers(reference.Census);
        Assert.NotEmpty(pinned);

        var escapees = UnpinnedNumbers(reference.Census, pinned);
        _output.WriteLine($"pinned or disclaimed vocabulary: {pinned.Count} distinct numbers");
        Assert.True(escapees.Count == 0,
            "census numbers that are neither pinned in §10 nor named in §9:" + Environment.NewLine
            + string.Join(Environment.NewLine, escapees));
    }

    // ======================================================================================
    // Document shape. Legitimately document-only: the subject IS the document.
    // ======================================================================================

    [Fact]
    public void EveryBehaviourRow_CarriesOneOfTheFourLabelsAndAPlatformCell()
    {
        var rows = BehaviourRows(RequireReference().Census);
        Assert.NotEmpty(rows);

        var bad = rows.Where(r => !Labels.Any(l => r.Contains(l, StringComparison.Ordinal))
                               || !r.Contains("Windows:", StringComparison.Ordinal)
                               || !r.Contains("Linux:", StringComparison.Ordinal)).ToList();

        Assert.True(bad.Count == 0,
            "behaviour rows missing a label or a platform cell:" + Environment.NewLine
            + string.Join(Environment.NewLine, bad));
    }

    [Fact]
    public void EveryLinuxCell_IsUnproven_BecauseThisMachineHasNoDistro()
    {
        var rows = BehaviourRows(RequireReference().Census);
        Assert.NotEmpty(rows);

        var claimed = rows.Where(r => Regex.IsMatch(r, @"Linux:\s*\**\s*proven", RegexOptions.IgnoreCase)).ToList();
        Assert.True(claimed.Count == 0,
            "a Linux cell claims proven; there is no WSL distro on this machine, so every Linux "
            + "claim is a named gate:" + Environment.NewLine + string.Join(Environment.NewLine, claimed));
    }

    [Fact]
    public void TheFourPrivacyVerdicts_ArePinnedAtTheStartOfTheAnswer()
    {
        var census = RequireReference().Census;
        var wrong = new List<string>();

        foreach (var (id, verdict) in PrivacyVerdicts)
        {
            var row = census.Split('\n')
                .Select(l => l.Trim())
                .FirstOrDefault(l => Regex.IsMatch(l, $@"^\|\s*{id}\s*\|"));
            if (row is null) { wrong.Add($"{id}: no privacy row"); continue; }

            var cells = SplitRow(row);
            if (cells.Count < 3) { wrong.Add($"{id}: malformed row"); continue; }

            var answer = Regex.Replace(cells[2], "`[^`]*`", " ").Trim().TrimStart('*', ' ');
            if (!answer.StartsWith(verdict, StringComparison.OrdinalIgnoreCase))
                wrong.Add($"{id}: answer opens \"{answer[..Math.Min(40, answer.Length)]}\", pinned verdict is \"{verdict}\"");
        }

        Assert.True(wrong.Count == 0,
            "privacy verdicts changed:" + Environment.NewLine + string.Join(Environment.NewLine, wrong));
    }

    [Fact]
    public void EveryOwnerFlaggedSection_ExistsAndIsNeverPriced()
    {
        var census = RequireReference().Census;

        var missing = OwnerFlaggedHeadings.Where(h => !census.Contains(h, StringComparison.Ordinal)).ToList();
        Assert.True(missing.Count == 0,
            "owner-flagged sections missing from the census: " + string.Join(", ", missing));

        Assert.Contains("deliberately not priced", census, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("never priced", census, StringComparison.OrdinalIgnoreCase);

        // The §6 heading states a DECISION count in words, and §8 restates it. A seven-row residue
        // resolving to five decisions is legitimate, but the two tallies must agree with the
        // sections that exist — an earlier draft said "six" and matched neither.
        var decisionSections = OwnerFlaggedHeadings
            .Count(h => Regex.IsMatch(h, @"^### 6\.[1-5]$"));
        var heading = Regex.Match(census, @"^## 6\. OWNER-FLAGGED — (?<count>[a-z]+) decisions", RegexOptions.Multiline);
        Assert.True(heading.Success, "§6's heading no longer states a decision count");
        Assert.Equal(NumberWord(decisionSections), heading.Groups["count"].Value);

        foreach (Match m in Regex.Matches(census, @"resolving to (?<count>[A-Z]+) owner decisions"))
            Assert.Equal(NumberWord(decisionSections).ToUpperInvariant(), m.Groups["count"].Value);
    }

    /// <summary>The bytes are linked read-only out of the legacy tree and never forked. A census
    /// that proposed copying them would be proposing a second owner for one set of files.</summary>
    [Fact]
    public void ThePayloadIsNeverProposedForForking()
    {
        var census = RequireReference().Census;
        Assert.Contains("never forked", census, StringComparison.OrdinalIgnoreCase);

        var offenders = census.Split('\n')
            .Where(l => Regex.IsMatch(l, @"(copy|fork)\w*\s+(the\s+)?(bytes|payload)", RegexOptions.IgnoreCase))
            .Where(l => !Regex.IsMatch(l, @"\bnever\b|\bno proposal\b|\bnot\b", RegexOptions.IgnoreCase))
            .ToList();

        Assert.True(offenders.Count == 0,
            "the census appears to propose forking payload bytes:" + Environment.NewLine
            + string.Join(Environment.NewLine, offenders));
    }

    /// <summary>
    /// Every table in the census is well-formed, and no pipe-row sits outside one.
    ///
    /// <para><b>Why this exists.</b> This document has thirty facts pinning its CONTENT and, until
    /// this one, nothing checking its STRUCTURE. A sub-subsection inserted into the middle of the
    /// §7.1 inventory table split it in two, and the four rows after the split — including
    /// <c>Owner decisions required | none</c>, the line that prices the buildable unit — lost their
    /// header and delimiter and rendered as lazy continuation lines of the preceding paragraph.
    /// <b>Markdown fails SILENTLY</b>: a malformed table is not an error, it is invisible prose.
    /// That is why it survived four review rounds, two hand sweeps and thirty content facts.</para>
    ///
    /// <para>Under GFM a table needs a delimiter row immediately after its header, so the rule is
    /// exactly that: every maximal run of pipe-rows must have a delimiter as its SECOND line. A run
    /// of one is an orphan row and fails the same way. Fenced code blocks are skipped — a fence can
    /// legitimately contain a line starting with a pipe.</para>
    /// </summary>
    [Fact]
    public void EveryTableInTheCensusIsWellFormed_AndNoPipeRowSitsOutsideOne()
    {
        var malformed = MalformedTables(RequireReference().Census);

        Assert.True(malformed.Count == 0,
            "the census holds pipe-rows that are not a well-formed table — under GFM these render "
            + "as prose, silently, which is how the inventory table's pricing row was lost:"
            + Environment.NewLine + string.Join(Environment.NewLine, malformed));
    }

    [Fact]
    public void TheTableStructureCheck_CatchesASplitTableAndAnOrphanRow()
    {
        const string good = """
            | Key | Value |
            |---|---|
            | a | 1 |
            """;
        Assert.Empty(MalformedTables(good));

        // A table interrupted by a paragraph, resuming without a header — the §7.1 defect.
        const string split = """
            | Key | Value |
            |---|---|
            | a | 1 |

            Some prose about something else.
            | b | 2 |
            | c | 3 |
            """;
        Assert.Single(MalformedTables(split));

        // A lone pipe-row with no table at all.
        const string orphan = """
            text

            | orphan | row |
            """;
        Assert.Single(MalformedTables(orphan));

        // A fence may legitimately open a line with a pipe.
        const string fenced = """
            ```
            | not | a | table |
            ```
            """;
        Assert.Empty(MalformedTables(fenced));
    }

    [Fact]
    public void NoTableCellHidesAnUnescapedPipeInsideACodeSpan()
    {
        var offenders = UnescapedPipesInCodeSpans(RequireReference().Census);
        Assert.True(offenders.Count == 0,
            "an unescaped pipe in a code span silently truncates its table row (how D197 and D209 "
            + "lost their disposition):" + Environment.NewLine + string.Join(Environment.NewLine, offenders));
    }

    // ======================================================================================
    // Fixtures. Nothing above rests on today's tree happening to agree with the parsers.
    // ======================================================================================

    [Fact]
    public void TheWalker_SkipsGeneratedBytesAndNothingElse()
    {
        var walked = WalkTempTreeFixture().Select(Path.GetFileName).ToList();

        Assert.Contains("a.cs", walked);
        Assert.Contains("b.xaml", walked);
        Assert.Contains(".gitkeep", walked);
        Assert.DoesNotContain("generated.cs", walked);
        Assert.DoesNotContain("dep.js", walked);
    }

    [Fact]
    public void TheCommentStripper_KeepsCodeBeforeAComment_AndNeverCutsInsideAString()
    {
        Assert.Equal("var x = new Foo();   ", CodeOf("var x = new Foo();   // see Bar"));
        Assert.Equal("", CodeOf("        // GoonDraft is only mentioned here"));
        Assert.Equal("", CodeOf("        /// <summary>GoonRng</summary>"));
        Assert.Equal("", CodeOf("         * GoonScoring in a block comment"));

        // The string-aware half: a URL must not be read as the start of a comment, or a real
        // reference after it would vanish and the closure would silently UNDER-report.
        const string url = "private const string P = \"https://x.example\"; var y = new Bar();";
        Assert.Equal(url, CodeOf(url));
    }

    [Fact]
    public void TheClosure_FollowsATypeDeclaredInAnotherFile_NotJustAFileName()
    {
        // This is the exact shape that made an earlier draft of the census say FOUR: the seed names
        // ConsentSheetMsg, which carries neither the surface token nor its file's name.
        var files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Seed.cs"] = "class Seed { void M() { var c = new ConsentSheetMsg(); } }",
            ["Contracts.cs"] = "public sealed class ConsentSheetMsg { }",
            ["Unrelated.cs"] = "public sealed class Unrelated { }",
            ["MentionedOnlyInAComment.cs"] = "public sealed class Ghost { }",
        };
        files["Seed.cs"] += "\n// Ghost is only named here";

        var closure = CloseOver(files, "Seed.cs");

        Assert.Equal(["Contracts.cs", "Seed.cs"], closure.OrderBy(c => c, StringComparer.Ordinal).ToList());
    }

    [Fact]
    public void TheCitationPin_FailsOnAnOffByOne()
    {
        const string file = "line one\nline two\nline three\n";
        var rows = new List<CitationRow>
        {
            new("right", "F.cs", 2, "line two"),
            new("off-by-one", "F.cs", 3, "line two"),
            new("out-of-range", "F.cs", 99, "line two"),
        };

        var drift = CitationDrift(rows, _ => file);

        Assert.Equal(2, drift.Count);
        Assert.Contains(drift, d => d.Contains("off-by-one", StringComparison.Ordinal));
        Assert.Contains(drift, d => d.Contains("out-of-range", StringComparison.Ordinal));
    }

    [Fact]
    public void TheNumberSweep_ExcludesByClassAndStillCatchesABareNumber()
    {
        const string doc = """
            # Doc

            Filed 2026-08-04 for v6.7.4, recorded as D240, see §10.4 and
            `GoonHostService.cs:310`, sha `460c9355`. The tree holds 25 files.
            Somebody later wrote that it holds 77 files.

            ## 9. What this does NOT prove

            - the 25 is a directory total

            ## 10. Pinned enumeration

            ### 10.1 Directory counts

            | Key | Value |
            |---|---|
            | Services/GoonGame | 25 |
            """;

        var pinned = PinnedNumbers(doc);
        var escapees = UnpinnedNumbers(doc, pinned);

        // The excluded CLASSES all pass: ISO date, version, divergence id, section
        // reference, File.cs:line citation, hex sha.
        Assert.Single(escapees);
        Assert.Contains("77", escapees[0], StringComparison.Ordinal);
    }

    /// <summary>
    /// THE SECOND HOLE, pinned so it cannot come back. The vocabulary side used to harvest digit
    /// runs raw while the checking side stripped <see cref="ExcludedNumberClasses"/>, so a row id
    /// or a citation line number silently whitelisted its own integer across the whole document.
    /// Both sides now strip the same classes.
    /// </summary>
    [Fact]
    public void TheNumberSweep_DoesNotAdmitRowIdsOrCitationLineNumbersToTheVocabulary()
    {
        const string doc = """
            # Doc

            ## 9. What this does NOT prove

            - the server is private (`GoonSignalingClient.cs:16-17`)

            ## 10. Pinned enumeration

            ### 10.2 The split

            | Id | Path | Reached |
            |---|---|---|
            | G7 | x.cs | reference |
            | G12 | y.cs | reference |
            | G24 | z.cs | reference |
            """;

        var pinned = PinnedNumbers(doc);

        // The row ids and the citation range must contribute NOTHING to the vocabulary.
        Assert.DoesNotContain("7", pinned);
        Assert.DoesNotContain("12", pinned);
        Assert.DoesNotContain("16", pinned);
        Assert.DoesNotContain("17", pinned);
        Assert.DoesNotContain("24", pinned);

        // ...and the checking side therefore still catches a body claim that reuses them.
        var escapees = UnpinnedNumbers(doc + "\nBody prose: 7 of the 24 files, 16 percent.\n", pinned);
        Assert.Equal(3, escapees.Count);
    }

    /// <summary>
    /// THE FIFTH HOLE, and the one whose shape is worth remembering: <b>the table documenting this
    /// guard's defects re-created one of them.</b> §10.7 is narrative prose in table form, it sits
    /// inside §10, and the previous rule admitted any table row inside §10 to the vocabulary — so
    /// the axis row reading "injected 7, 12, 16 and 24" put 16 and 24 straight back in, and it was
    /// the ONLY source of 16. Vocabulary admissibility is now scoped to pin subsections.
    /// </summary>
    [Fact]
    public void TheNumberSweep_DoesNotAdmitNarrativeTableRowsInsideThePinSection()
    {
        const string doc = """
            # Doc

            ## 10. Pinned enumeration

            ### 10.1 Directory counts

            | Key | Value |
            |---|---|
            | a | 25 |

            ### 10.7 What the guard enforces beyond the tables

            | Axis | Divergence | State |
            |---|---|---|
            | Class filtering | injected 16 and 24 into the vocabulary | both sides strip |
            """;

        var pinned = PinnedNumbers(doc);

        Assert.Contains("25", pinned);          // the pin subsection still pins
        Assert.DoesNotContain("16", pinned);    // the narrative table does not
        Assert.DoesNotContain("24", pinned);

        // ...so a body claim reusing them is still caught, which is the whole point.
        var escapees = UnpinnedNumbers(doc + "\nAUDIT: 16 percent of it, over 24 rounds.\n", pinned);
        Assert.Equal(2, escapees.Count(e => e.Contains("AUDIT", StringComparison.Ordinal)));

        // And the narrative row's OWN digits are now checked like any prose, which is the other
        // half of the repair: §10.7 is no longer a place a number can hide.
        Assert.Contains(escapees, e => e.Contains("both sides strip", StringComparison.Ordinal));
    }

    /// <summary>
    /// The stale-restatement class, closed mechanically. Three numbers in the first draft of this
    /// census were correct in one section and stale in another, and the verdict paragraph cited an
    /// OWNER-GATED tally its own behaviour map contradicted. The label counts are re-derived from
    /// the map's rows and compared against EVERY restatement of them in the document, so a
    /// correction that does not propagate reds the suite instead of surviving in a summary.
    /// </summary>
    [Fact]
    public void TheLabelTally_MatchesTheBehaviourMap_EverywhereItIsRestated()
    {
        var census = RequireReference().Census;
        var rows = BehaviourRows(census);
        Assert.NotEmpty(rows);

        var derived = Labels.ToDictionary(
            label => label,
            label => rows.Count(r => Regex.IsMatch(r, $@"\*\*{Regex.Escape(label)}\b")),
            StringComparer.Ordinal);

        _output.WriteLine(string.Join(", ", derived.Select(kv => $"{kv.Key}={kv.Value}")));
        Assert.Equal(rows.Count, derived.Values.Sum());

        var pinned = ParseKeyValueTable(census, "### 10.4.3");
        AssertAgrees(
            pinned,
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["behaviour-rows"] = rows.Count.ToString(),
                ["label-covered"] = derived["COVERED"].ToString(),
                ["label-partial"] = derived["PARTIAL"].ToString(),
                ["label-gap"] = derived["GAP"].ToString(),
                ["label-owner-gated"] = derived["OWNER-GATED"].ToString(),
            },
            "§10.4.3");

        // Every "<LABEL>: N of M" restatement in the document, wherever it sits.
        var mismatches = new List<string>();
        foreach (Match m in Regex.Matches(census, @"\*\*(?<label>COVERED|PARTIAL|GAP|OWNER-GATED):\s*(?<n>\d+) of (?<m>\d+)\*\*"))
        {
            var label = m.Groups["label"].Value;
            if (int.Parse(m.Groups["n"].Value) != derived[label])
                mismatches.Add($"\"{label}: {m.Groups["n"].Value} of {m.Groups["m"].Value}\" but the map holds {derived[label]}");
            if (int.Parse(m.Groups["m"].Value) != rows.Count)
                mismatches.Add($"\"{label}: … of {m.Groups["m"].Value}\" but the map has {rows.Count} rows");
        }

        // ...and the verdict paragraph's own tally, which is where the stale six survived.
        foreach (Match m in Regex.Matches(census, @"clause 1 fails \((?<count>[a-z]+) OWNER-GATED rows\)"))
        {
            var spelled = NumberWord(derived["OWNER-GATED"]);
            if (!m.Groups["count"].Value.Equals(spelled, StringComparison.OrdinalIgnoreCase))
                mismatches.Add($"the verdict says \"{m.Groups["count"].Value} OWNER-GATED rows\" but the map holds {derived["OWNER-GATED"]} (\"{spelled}\")");
        }

        Assert.True(mismatches.Count == 0,
            "a label tally is restated somewhere it does not match the behaviour map:" + Environment.NewLine
            + string.Join(Environment.NewLine, mismatches));
    }

    /// <summary>
    /// The append hole, pinned so it cannot come back. §10 is the LAST section of the census, so a
    /// tracker that treated every line after its heading as "pinned" swallowed anything added to the
    /// end of the document. The red demonstration for the number sweep passed on exactly this, and
    /// finding out why is the reason the sweep is now table-row-scoped inside §10.
    /// </summary>
    [Fact]
    public void TheNumberSweep_StillSeesProseAppendedAfterThePinSection()
    {
        const string doc = """
            # Doc

            ## 10. Pinned enumeration

            ### 10.1 Directory counts

            | Key | Value |
            |---|---|
            | a | 25 |

            A note somebody appended later, mentioning 4242.
            """;

        var escapees = UnpinnedNumbers(doc, PinnedNumbers(doc));

        Assert.Single(escapees);
        Assert.Contains("4242", escapees[0], StringComparison.Ordinal);
    }

    [Fact]
    public void TheKeyValueParser_StopsAtTheNextHeading()
    {
        const string doc = """
            ### 10.1

            | Key | Value |
            |---|---|
            | a | 1 |

            ### 10.2

            | Key | Value |
            |---|---|
            | b | 2 |
            """;

        var first = ParseKeyValueTable(doc, "### 10.1");
        Assert.Equal("1", first["a"]);
        Assert.False(first.ContainsKey("b"));
    }

    [Fact]
    public void TheBehaviourRowReader_SeesOnlyLabelledBehaviourRows()
    {
        const string doc = """
            | # | Owner's phrase | Label | Platform |
            |---|---|---|---|
            | B1 | a thing | **COVERED by x** | Windows: unproven. Linux: unproven |
            | B2 | another | **GAP: y** | Windows: unproven. Linux: unproven |
            | G1 | not a behaviour row | host | |
            """;

        var rows = BehaviourRows(doc);
        Assert.Equal(2, rows.Count);
        Assert.All(rows, r => Assert.Contains("Linux:", r, StringComparison.Ordinal));
    }

    // ======================================================================================
    // Machinery. Every filesystem predicate lives HERE, never in a fact body, so no fact carries
    // a silencing shape and none of them can be satisfied by an absent tree.
    // ======================================================================================

    private sealed record Reference(string Root, string Census, string Wpf);

    private sealed record CitationRow(string Key, string Path, int Line, string Needle);

    /// <summary>Resolves the repo root, the census and the shipping tree. All three are hard
    /// requirements: this guard FAILS rather than skipping on any of them, so there is no branch
    /// that can be permanently unreachable and pass forever.</summary>
    private static Reference RequireReference()
    {
        var root = FindRepoRoot();
        Assert.True(root is not null,
            $"repo root not found (anchor: {string.Join('/', RepoAnchorParts)}); this guard never skips");

        var censusPath = Path.Combine(root!, Path.Combine(CensusParts));
        RequirePath(censusPath, isDirectory: false, $"{CensusRelativePath} is missing; this guard never skips");

        var wpf = Path.Combine(root!, Path.Combine(WpfRootParts));
        RequirePath(wpf, isDirectory: true,
            $"{WpfRootParts[0]}/ is missing. The reference tree is IN THIS REPOSITORY, so its absence is a "
            + "corrupt checkout, not an environment this guard may pass in.");

        return new Reference(root!, File.ReadAllText(censusPath), wpf);
    }

    private static void RequirePath(string path, bool isDirectory, string because) =>
        Assert.True(isDirectory ? Directory.Exists(path) : File.Exists(path), because);

    private static string? FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, Path.Combine(RepoAnchorParts)))) return dir.FullName;
            dir = dir.Parent;
        }

        return null;
    }

    private static string Resolve(string root, string relative) =>
        Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar));

    /// <summary>A censused directory that has gone missing is a HALF-PRESENT reference tree, i.e. a
    /// corrupt checkout, and fails.</summary>
    private static int CountFilesUnder(string wpf, string relative) =>
        RelativeFilesUnder(wpf, relative).Count;

    private static List<string> RelativeFilesUnder(string wpf, string relative)
    {
        var dir = Resolve(wpf, relative);
        RequirePath(dir, isDirectory: true,
            $"HALF-PRESENT reference tree: {WpfRootParts[0]}/ exists but {relative} does not. Corrupt checkout.");

        return WalkFiles(dir)
            .Select(p => Path.GetRelativePath(dir, p).Replace(Path.DirectorySeparatorChar, '/'))
            .OrderBy(p => p, StringComparer.Ordinal)
            .ToList();
    }

    private static long TotalBytes(string wpf, string relative)
    {
        var dir = Resolve(wpf, relative);
        RequirePath(dir, isDirectory: true, $"HALF-PRESENT reference tree: {relative} is missing");
        return WalkFiles(dir).Sum(p => new FileInfo(p).Length);
    }

    /// <summary>Which of these paths are absent from the shipping tree. The <c>File.Exists</c> lives
    /// HERE rather than in the fact body: <c>VacuousShapeDetector</c> classes a filesystem predicate
    /// inside a fact as a silencing shape, and the ledger that would disposition it is outside this
    /// packet's write scope — so the shape is removed rather than excused.</summary>
    private static List<string> MissingShippingPaths(string wpf, IEnumerable<string> relatives) =>
        relatives.Where(p => !File.Exists(Resolve(wpf, p))).ToList();

    private static string ReadShippingFile(string wpf, string relative)
    {
        var path = Resolve(wpf, relative);
        RequirePath(path, isDirectory: false, $"HALF-PRESENT reference tree: {relative} is missing");
        return File.ReadAllText(path);
    }

    private static string ReadRepoFile(string root, string relative)
    {
        var path = Resolve(root, relative);
        RequirePath(path, isDirectory: false, $"{relative} is required by this pin and is missing");
        return File.ReadAllText(path);
    }

    /// <summary>Newline count, which is what <c>wc -l</c> and <c>walk.mjs --lines</c> both report for
    /// a file that ends in a newline. Every file in these trees does.</summary>
    private static int LineCount(string wpf, string relative) =>
        ReadShippingFile(wpf, relative).Split('\n').Length is var n && n > 0 ? n - 1 : 0;

    /// <summary>The frozen <c>GoonElement</c> wire codes, name -&gt; code, read from the enum.</summary>
    private static Dictionary<string, string> DuelElementCodes(string wpf)
    {
        var contracts = ReadShippingFile(wpf, "Services/GoonGame/GoonContracts.cs");
        var body = Regex.Match(contracts, @"enum\s+GoonElement\s*\{(?<body>[^}]*)\}", RegexOptions.Singleline);
        Assert.True(body.Success, "GoonContracts.cs no longer declares enum GoonElement");

        var codes = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (Match m in Regex.Matches(body.Groups["body"].Value,
                     @"^\s*(?<name>[A-Z][A-Za-z0-9_]*)\s*=\s*(?<code>\d+)", RegexOptions.Multiline))
            codes[m.Groups["name"].Value] = m.Groups["code"].Value;

        return codes;
    }

    /// <summary>
    /// §10.5's rows that are per-element port modules, identified by DERIVING the element names
    /// from the upstream enum rather than by listing the anchors that are not elements.
    ///
    /// <para>The first version excluded two anchors BY NAME, which meant every new port anchor
    /// added to §10.5 silently inflated the element count and broke an unrelated pin — a literal
    /// exclusion list wearing a different hat, and the same escape-hatch shape this guard has been
    /// drilled on five times. Keying off the enum makes the set self-maintaining: an element added
    /// upstream demands an anchor, and an anchor that is not an element is simply not counted.</para>
    /// </summary>
    private static int PortElementAnchors(string census, string wpf)
    {
        var elements = DuelElementCodes(wpf).Keys
            .Select(n => n.ToLowerInvariant())
            .ToHashSet(StringComparer.Ordinal);

        return ParseCitationTable(census, "### 10.5")
            .Count(r => elements.Contains(r.Key.ToLowerInvariant()));
    }

    /// <summary>A millisecond constant re-derived from the shipping bytes, so a "10 s" in prose is
    /// the source's own number divided by a thousand rather than a figure somebody typed.</summary>
    private static int MillisecondConstant(string wpf, string relative, string name)
    {
        var text = ReadShippingFile(wpf, relative);
        var m = Regex.Match(text, Regex.Escape(name) + @"\s*=\s*(?<v>[\d_]+)");
        Assert.True(m.Success, $"{name} not found in {relative}");
        return int.Parse(m.Groups["v"].Value.Replace("_", ""), CultureInfo.InvariantCulture);
    }

    private static int SumLinesUnder(string wpf, string relative) =>
        RelativeFilesUnder(wpf, relative).Sum(p => LineCount(wpf, $"{relative}/{p}"));

    /// <summary>Compares a declared table against re-derived values, reporting every disagreement
    /// rather than the first. Shared by the count facts so none of them can drift apart.</summary>
    private void AssertAgrees(
        IReadOnlyDictionary<string, string> declared, IReadOnlyDictionary<string, string> actual, string section)
    {
        var mismatches = new List<string>();
        foreach (var (key, value) in actual)
        {
            var claimed = declared.TryGetValue(key, out var c) ? c : "<absent>";
            _output.WriteLine($"{key}: census {claimed}, derived {value}");
            if (claimed != value) mismatches.Add($"{key}: census says {claimed}, the bytes say {value}");
        }

        foreach (var key in declared.Keys.Where(k => !actual.ContainsKey(k)))
            mismatches.Add($"{key}: census pins it, nothing re-derives it");

        Assert.True(mismatches.Count == 0,
            $"census {section} does not re-derive:" + Environment.NewLine
            + string.Join(Environment.NewLine, mismatches));
    }

    /// <summary>Recursive directory walk. Generated-byte directories are skipped; nothing is skipped
    /// by source-file name. Symlinked directories are not followed.</summary>
    private static List<string> WalkFiles(string root)
    {
        var found = new List<string>();
        var stack = new Stack<string>();
        stack.Push(root);

        while (stack.Count > 0)
        {
            var dir = stack.Pop();
            foreach (var child in Directory.GetDirectories(dir))
            {
                if (GeneratedDirectories.Contains(Path.GetFileName(child))) continue;
                if (new DirectoryInfo(child).LinkTarget is not null) continue;
                stack.Push(child);
            }

            found.AddRange(Directory.GetFiles(dir));
        }

        return found;
    }

    private static List<string> WalkTempTreeFixture()
    {
        var temp = Path.Combine(Path.GetTempPath(), "sp129-" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(Path.Combine(temp, "sub"));
            Directory.CreateDirectory(Path.Combine(temp, "obj"));
            Directory.CreateDirectory(Path.Combine(temp, "node_modules"));
            File.WriteAllText(Path.Combine(temp, "a.cs"), "");
            File.WriteAllText(Path.Combine(temp, "sub", "b.xaml"), "");
            File.WriteAllText(Path.Combine(temp, "sub", ".gitkeep"), "");
            File.WriteAllText(Path.Combine(temp, "obj", "generated.cs"), "");
            File.WriteAllText(Path.Combine(temp, "node_modules", "dep.js"), "");

            return WalkFiles(temp);
        }
        finally
        {
            Directory.Delete(temp, recursive: true);
        }
    }

    // ------------------------------------------------------------------------------------
    // The closure over declared types.
    // ------------------------------------------------------------------------------------

    /// <summary>A type DECLARATION: the keyword preceded only by modifiers, on a code line, with an
    /// upper-case name. Deliberately narrow — a looser pattern matched prose ("record is…", "for",
    /// "code") and polluted the index with tokens that matched everywhere.</summary>
    private static readonly Regex Declaration = new(
        @"^\s*(?:(?:public|internal|private|protected|sealed|static|abstract|partial|readonly|file|new)\s+)*"
        + @"(?:class|struct|interface|enum|record(?:\s+struct)?)\s+([A-Z][A-Za-z0-9_]*)",
        RegexOptions.Compiled);

    /// <summary>
    /// Strips a trailing <c>//</c> comment, respecting string and char literals, and drops lines
    /// that are wholly comment. A block-comment continuation line that does not start with
    /// <c>*</c> is left as CODE: the bias is deliberate, because an over-reported edge is visible
    /// in the closure while an under-reported one is silent, and this census's headline is a claim
    /// that a set of files is NOT reachable.
    /// </summary>
    private static string CodeOf(string line)
    {
        var trimmed = line.TrimStart();
        if (trimmed.StartsWith("//", StringComparison.Ordinal)
            || trimmed.StartsWith("*", StringComparison.Ordinal)
            || trimmed.StartsWith("/*", StringComparison.Ordinal)) return string.Empty;

        var inString = false;
        var inChar = false;
        var verbatim = false;

        for (var i = 0; i < line.Length; i++)
        {
            var c = line[i];
            if (inString)
            {
                if (verbatim)
                {
                    if (c == '"' && i + 1 < line.Length && line[i + 1] == '"') i++;
                    else if (c == '"') { inString = false; verbatim = false; }
                }
                else if (c == '\\') i++;
                else if (c == '"') inString = false;
                continue;
            }

            if (inChar)
            {
                if (c == '\\') i++;
                else if (c == '\'') inChar = false;
                continue;
            }

            if (c == '"')
            {
                inString = true;
                verbatim = i > 0 && (line[i - 1] == '@' || (line[i - 1] == '$' && i > 1 && line[i - 2] == '@'));
                continue;
            }

            if (c == '\'') { inChar = true; continue; }
            if (c == '/' && i + 1 < line.Length && line[i + 1] == '/') return line[..i];
        }

        return line;
    }

    private static HashSet<string> ShippedPathClosure(string wpf)
    {
        var dir = Resolve(wpf, SurfaceDirectory[0]);
        RequirePath(dir, isDirectory: true, $"HALF-PRESENT reference tree: {SurfaceDirectory[0]} is missing");

        var files = RelativeFilesUnder(wpf, SurfaceDirectory[0])
            .ToDictionary(p => p, p => ReadShippingFile(wpf, $"{SurfaceDirectory[0]}/{p}"), StringComparer.Ordinal);

        return CloseOver(files, ShippedPathSeed);
    }

    /// <summary>Transitive closure from <paramref name="seed"/> over the type names each file
    /// declares. Kept separate from the filesystem so the fixture can drive it with synthetic
    /// sources.</summary>
    private static HashSet<string> CloseOver(IReadOnlyDictionary<string, string> files, string seed)
    {
        var typeToFile = new Dictionary<string, string>(StringComparer.Ordinal);
        var codeLines = new Dictionary<string, string[]>(StringComparer.Ordinal);

        foreach (var (path, text) in files)
        {
            var lines = text.Split('\n').Select(l => CodeOf(l.TrimEnd('\r'))).ToArray();
            codeLines[path] = lines;

            var baseName = Path.GetFileNameWithoutExtension(path);
            typeToFile.TryAdd(baseName, path);
            foreach (var line in lines)
            {
                var m = Declaration.Match(line);
                if (m.Success) typeToFile.TryAdd(m.Groups[1].Value, path);
            }
        }

        var needles = typeToFile
            .Select(kv => (Owner: kv.Value, Pattern: new Regex($@"\b{Regex.Escape(kv.Key)}\b", RegexOptions.Compiled)))
            .ToList();

        var closure = new HashSet<string>(StringComparer.Ordinal) { seed };
        var queue = new Queue<string>();
        queue.Enqueue(seed);

        while (queue.Count > 0)
        {
            var current = queue.Dequeue();
            if (!codeLines.TryGetValue(current, out var lines)) continue;

            foreach (var line in lines)
            {
                if (line.Length == 0) continue;
                foreach (var (owner, pattern) in needles)
                {
                    if (owner == current || closure.Contains(owner)) continue;
                    if (!pattern.IsMatch(line)) continue;
                    closure.Add(owner);
                    queue.Enqueue(owner);
                }
            }
        }

        return closure;
    }

    // ------------------------------------------------------------------------------------
    // Citation pinning.
    // ------------------------------------------------------------------------------------

    private static List<string> CitationDrift(IEnumerable<CitationRow> rows, Func<string, string> read)
    {
        var wrong = new List<string>();
        foreach (var row in rows)
        {
            var line = LineAt(read(row.Path), row.Line);
            if (!line.Contains(row.Needle, StringComparison.Ordinal))
                wrong.Add($"{row.Key}: {row.Path}:{row.Line} should carry \"{row.Needle}\" but the line reads \"{line.Trim()}\"");
        }

        return wrong;
    }

    /// <summary>The 1-based line, or empty when out of range. Empty never contains a needle, so an
    /// off-by-one fails rather than silently passing.</summary>
    private static string LineAt(string text, int oneBasedLine)
    {
        var lines = text.Split('\n');
        return oneBasedLine >= 1 && oneBasedLine <= lines.Length ? lines[oneBasedLine - 1] : string.Empty;
    }

    // ------------------------------------------------------------------------------------
    // The number sweep.
    // ------------------------------------------------------------------------------------

    /// <summary>Contexts a number may legitimately live in WITHOUT being a claim about this
    /// surface. Each is a CLASS, and each is here in code rather than as a list of literals.</summary>
    private static readonly Regex[] ExcludedNumberClasses =
    [
        new(@"[A-Za-z0-9_.\-]+\.(?:cs|js|mjs|json|xaml|axaml|csproj|md|html|css|webmanifest):\d+(?:-\d+)?", RegexOptions.Compiled), // File.ext:NNN citations
        new(@"(?<![A-Za-z0-9]):\d+(?:-\d+)?", RegexOptions.Compiled),                                                 // bare :NNN continuations
        new(@"§\s*\d+(?:\.\d+)*", RegexOptions.Compiled),                                                             // section references
        new(@"\bD\d+\b", RegexOptions.Compiled),                                                                      // divergence ids
        new(@"\b\d{4}-\d{2}-\d{2}\b", RegexOptions.Compiled),                                                         // ISO dates
        new(@"\bv\d+(?:\.\d+)*\b", RegexOptions.Compiled),                                                            // versions
        new(@"\bsha-?\d+\b", RegexOptions.Compiled | RegexOptions.IgnoreCase),                                        // hash algorithm names
        // A hex sha, and NOT a long decimal. The first version was `[0-9a-f]{7,}` flat, which also
        // matched 12471900 — the payload's own byte total — and quietly dropped it from the
        // vocabulary the moment both sides started stripping classes. At least one a-f is required.
        new(@"\b(?=[0-9a-f]{7,}\b)[0-9a-f]*[a-f][0-9a-f]*\b", RegexOptions.Compiled),                                 // hex shas
        new(@"\bB\d+\b|\bG\d+\b|\bX\d+\b|\bR\d+\b|\bQ\d+\b", RegexOptions.Compiled),                                  // row ids
        new(@"^#{1,6}\s.*$", RegexOptions.Compiled | RegexOptions.Multiline),                                         // headings
    ];

    /// <summary>
    /// The numbers the census is entitled to state: the ones in a §10 pin TABLE ROW, plus the ones
    /// named in §9's "does not prove" section.
    ///
    /// <para><b>Only table rows count inside §10, and this is a repair.</b> The first version
    /// treated every line after the <c>## 10.</c> heading as pinned. §10 is the last section, so
    /// anything appended to the document landed inside it and had its numbers silently added to the
    /// vocabulary. <b>The red demonstration this fact was built with PASSED because of exactly
    /// that</b> — the guard was looking somewhere the claim was not, which is the same shape of hole
    /// the earlier path-only pin had.</para>
    /// </summary>
    private static HashSet<string> PinnedNumbers(string census)
    {
        var vocabulary = new HashSet<string>(StringComparer.Ordinal);

        foreach (var (line, section) in Sections(census))
        {
            // Pins now means a PIN SUBSECTION (§10.1-§10.6), never "anywhere inside §10" — see
            // Sections(). A narrative table inside §10 contributes nothing to the vocabulary.
            var admissible = section == DocumentSection.Disclaimer
                          || (section == DocumentSection.Pins && line.TrimStart().StartsWith('|'));
            if (!admissible) continue;

            // THE SAME CLASS FILTER THE CHECKING SIDE USES, and the reason it is here is a hole
            // this guard shipped once. Harvesting digit runs RAW while UnpinnedNumbers strips
            // classes is an ASYMMETRY, and an asymmetry is the literal-exclusion escape hatch by
            // another route: row ids (G7, G12, G24) and citation line numbers
            // (GoonSignalingClient.cs:16-17) injected 7, 12, 16 and 24 into the vocabulary and
            // whitelisted those integers EVERYWHERE in the document. That is how a stale "16%"
            // survived a green suite. The two sides must strip the same classes or neither does.
            var admitted = line;
            foreach (var excluded in ExcludedNumberClasses) admitted = excluded.Replace(admitted, " ");

            foreach (Match m in Regex.Matches(admitted, @"\d[\d,_ ]*(?:\.\d+)?"))
                vocabulary.Add(Normalize(m.Value));
        }

        return vocabulary;
    }

    private enum DocumentSection { Body, Disclaimer, Pins }

    /// <summary>
    /// Walks the census once, tagging each line with the section it sits in. Shared by both halves
    /// of the number sweep so they can never disagree about where a section ends.
    ///
    /// <para><b><c>Pins</c> means a PIN SUBSECTION, not "anywhere inside §10".</b> §10.7 is
    /// narrative prose that happens to use tables, and it sits inside §10 — so under the previous
    /// rule its own axis table, <i>the table documenting this guard's holes</i>, re-injected the
    /// very integers it was describing back into the pinned vocabulary. The documentation of the
    /// defect recreated the defect. Only <c>### 10.1</c>-<c>### 10.6</c> and their <c>.N</c>
    /// children are pin subsections; everything else inside §10 is Body and is CHECKED like any
    /// other prose.</para>
    /// </summary>
    private static IEnumerable<(string Line, DocumentSection Section)> Sections(string census)
    {
        var section = DocumentSection.Body;
        var inPinSubsection = false;

        foreach (var raw in census.Split('\n'))
        {
            var line = raw.TrimEnd('\r');
            if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                section = Regex.IsMatch(line, @"^##\s+10\.\s") ? DocumentSection.Pins
                        : Regex.IsMatch(line, @"^##\s+9\.\s") ? DocumentSection.Disclaimer
                        : DocumentSection.Body;
                inPinSubsection = false;
            }
            else if (line.StartsWith("### ", StringComparison.Ordinal))
            {
                inPinSubsection = Regex.IsMatch(line, @"^###\s+10\.[1-6](\.\d+)*\b");
            }

            var effective = section == DocumentSection.Pins && !inPinSubsection
                ? DocumentSection.Body
                : section;

            yield return (line, effective);
        }
    }

    /// <summary>Every number outside §9, and inside §10 every number that is NOT in a pin table row,
    /// must already be in the pinned vocabulary. Checking §10's prose as well as the body is what
    /// makes text appended to the end of the document reachable by this fact.</summary>
    private static List<string> UnpinnedNumbers(string census, HashSet<string> pinned)
    {
        var escapees = new List<string>();
        var lineNumber = 0;

        foreach (var (raw, section) in Sections(census))
        {
            lineNumber++;
            if (section == DocumentSection.Disclaimer) continue;
            if (section == DocumentSection.Pins && raw.TrimStart().StartsWith('|')) continue;

            var line = raw;
            foreach (var excluded in ExcludedNumberClasses) line = excluded.Replace(line, " ");

            foreach (Match m in Regex.Matches(line, @"\d[\d,_ ]*(?:\.\d+)?"))
            {
                var value = Normalize(m.Value);
                if (value.Length == 0 || pinned.Contains(value)) continue;
                var trimmed = raw.Trim();
                escapees.Add($"line {lineNumber}: {value} — in \"{trimmed[..Math.Min(110, trimmed.Length)]}\"");
            }
        }

        return escapees;
    }

    /// <summary>Small integers spelled out, so a tally restated in words is comparable with one
    /// re-derived as a number. The census writes verdict tallies in words.</summary>
    private static string NumberWord(int value) => value switch
    {
        0 => "zero", 1 => "one", 2 => "two", 3 => "three", 4 => "four", 5 => "five", 6 => "six",
        7 => "seven", 8 => "eight", 9 => "nine", 10 => "ten", 11 => "eleven", 12 => "twelve",
        _ => value.ToString(CultureInfo.InvariantCulture),
    };

    private static string Normalize(string number) =>
        number.Replace(",", "").Replace("_", "").Replace(" ", "").TrimEnd('.');

    // ------------------------------------------------------------------------------------
    // Table parsing.
    // ------------------------------------------------------------------------------------

    /// <summary>Reads the first two-column table after <paramref name="heading"/>, stopping at the
    /// next heading so sections cannot leak into each other.</summary>
    private static Dictionary<string, string> ParseKeyValueTable(string document, string heading) =>
        ParseTable(document, heading, 2, cells => (cells[0], cells[1]));

    /// <summary>Reads an id/path/kind table, keyed by PATH so the census's own ids never become the
    /// thing under test.</summary>
    private static Dictionary<string, string> ParseIdPathTable(string document, string heading) =>
        ParseTable(document, heading, 2, cells => (cells[1], cells.Count >= 3 ? cells[2] : string.Empty));

    private static Dictionary<string, string> ParseTable(
        string document, string heading, int minimumCells, Func<List<string>, (string Key, string Value)> select)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        var lines = document.Split('\n');
        var index = Array.FindIndex(lines, l => l.TrimEnd('\r').StartsWith(heading, StringComparison.Ordinal));
        if (index < 0) return result;

        for (var i = index + 1; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (line.StartsWith("##", StringComparison.Ordinal)) break;
            if (!line.StartsWith('|')) continue;

            var cells = SplitRow(line);
            if (cells.Count < minimumCells) continue;
            if (cells[0] is "Key" or "#" or "Id") continue;
            if (cells[0].Length > 0 && cells[0].All(c => c is '-' or ':')) continue;

            var (key, value) = select(cells);
            result[key] = value;
        }

        return result;
    }

    private static List<CitationRow> ParseCitationTable(string document, string heading) =>
        ParseCitationTable(document, heading, out _);

    private static List<CitationRow> ParseCitationTable(
        string document, string heading, out List<string> unparsed)
    {
        var rows = new List<CitationRow>();
        unparsed = [];
        var lines = document.Split('\n');
        var index = Array.FindIndex(lines, l => l.TrimEnd('\r').StartsWith(heading, StringComparison.Ordinal));
        if (index < 0) return rows;

        for (var i = index + 1; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (line.StartsWith("##", StringComparison.Ordinal)) break;
            if (!line.StartsWith('|')) continue;

            var cells = SplitRow(line);
            if (cells[0] is "Key") continue;
            if (cells[0].Length > 0 && cells[0].All(c => c is '-' or ':')) continue;

            // A ROW THAT DOES NOT PARSE IS REPORTED, NEVER SKIPPED. Skipping is how §10.4 and §10.5
            // leaked: a two-cell narrative row dropped out here silently while its digits still
            // reached the pinned vocabulary — hole five's shape, in the two subsections a
            // three-subsection probe did not reach. Every table row inside a citation pin table
            // must BE a citation.
            if (cells.Count < 4 || !int.TryParse(cells[2], out var lineNumber))
            {
                unparsed.Add($"line {i + 1}: {line}");
                continue;
            }

            // Markdown escapes inside a needle are the DOCUMENT's syntax, not the source's. `\|`
            // would truncate the row and `\*` would italicise the cell, so both are written escaped
            // in the census and unescaped here before the needle is matched against real bytes.
            rows.Add(new CitationRow(cells[0], cells[1], lineNumber,
                cells[3].Replace("\\|", "|").Replace("\\*", "*")));
        }

        return rows;
    }

    private static List<string> SplitRow(string line)
    {
        var trimmed = line.Trim();
        if (trimmed.StartsWith('|')) trimmed = trimmed[1..];
        if (trimmed.EndsWith('|')) trimmed = trimmed[..^1];

        return trimmed.Split('|')
            .Select(c => c.Trim().Trim('`', '*').Trim())
            .ToList();
    }

    private static List<string> BehaviourRows(string document) =>
        document.Split('\n')
            .Select(l => l.Trim())
            .Where(l => Regex.IsMatch(l, @"^\|\s*B\d+\s*\|"))
            .ToList();

    /// <summary>Maximal runs of pipe-rows whose second line is not a GFM delimiter row. Fenced
    /// code blocks are skipped.</summary>
    private static List<string> MalformedTables(string document)
    {
        var bad = new List<string>();
        var lines = document.Split('\n');
        var fenced = false;
        var i = 0;

        while (i < lines.Length)
        {
            var trimmed = lines[i].Trim();
            if (trimmed.StartsWith("```", StringComparison.Ordinal)) { fenced = !fenced; i++; continue; }
            if (fenced || !trimmed.StartsWith('|')) { i++; continue; }

            var start = i;
            while (i < lines.Length)
            {
                var t = lines[i].Trim();
                if (t.StartsWith("```", StringComparison.Ordinal) || !t.StartsWith('|')) break;
                i++;
            }

            var run = i - start;
            var delimiter = run >= 2 && IsDelimiterRow(lines[start + 1]);
            if (!delimiter)
                bad.Add($"line {start + 1}: a run of {run} pipe-row(s) with no delimiter row after the "
                    + $"header — first row reads \"{lines[start].Trim()[..Math.Min(90, lines[start].Trim().Length)]}\"");
        }

        return bad;
    }

    private static bool IsDelimiterRow(string line)
    {
        var cells = SplitRow(line.Trim());
        return cells.Count > 0
            && cells.All(c => c.Length > 0 && c.Contains('-', StringComparison.Ordinal)
                              && c.All(ch => ch is '-' or ':'));
    }

    private static List<string> UnescapedPipesInCodeSpans(string document)
    {
        var offenders = new List<string>();
        var lineNumber = 0;
        foreach (var line in document.Split('\n'))
        {
            lineNumber++;
            if (!line.TrimStart().StartsWith('|')) continue;
            foreach (Match span in Regex.Matches(line, "`[^`]*`"))
                if (span.Value.Contains('|') && !span.Value.Contains("\\|", StringComparison.Ordinal))
                    offenders.Add($"line {lineNumber}: {span.Value}");
        }

        return offenders;
    }

    /// <summary>One decimal place, INVARIANT culture. The first version used the ambient culture and
    /// produced "20,0" on this machine — a guard that would have passed on an en-US box and failed on
    /// a comma-locale one, which is the same class of latent defect this census reports upstream.</summary>
    private static string Percent(long numerator, long denominator) =>
        denominator == 0
            ? "0.0"
            : Math.Round(numerator * 100.0 / denominator, 1).ToString("0.0", CultureInfo.InvariantCulture);
}
