using System.Text.RegularExpressions;
using Xunit;

namespace CcpClient.Tests;

/// <summary>
/// SP-127 — the pin under <c>client/docs/trainer-card-census.md</c>.
///
/// <para><b>Why this exists.</b> The port has been wrong about an upstream count five times
/// (haptic sites 8 → 13 → 14 → 18, For You Feed 3 → 9) and every correction came from WIDENING THE
/// SEARCH, never from re-reading the same lines. <see cref="HapticSiteCensusTests"/> says in its own
/// words that "a guard that only checked the document against itself would have passed on all four
/// numbers", so this file follows that rule rather than inventing a second convention for the same
/// job: the document is the DATA and this file is the LOGIC. The directory roots, the needles and
/// the expression patterns live HERE, and every count and every quoted expression is RE-DERIVED from
/// the shipping bytes on every run. Editing the census document can never shrink the search.</para>
///
/// <para><b>What this census found that makes the re-derivation load-bearing.</b> The board row's
/// five directory counts are arithmetically CORRECT as delta counts, and the row is still wrong:
/// <c>Views/Controls/</c>'s "113 new files" is <b>96.5% other features</b> (87 Companion, 16
/// AppSettings, 6 Studio, 4 Trainer Card). A guard that pinned only the total would have agreed with
/// the row forever, so <see cref="TheViewsControlsCount_IsOverwhelminglyNotThisFeature"/> re-derives
/// the SPLIT, which is the number that carries the finding.</para>
///
/// <para><b>Non-vacuous design, and a DELIBERATE DEPARTURE from the two precedent census guards.</b>
/// The repo root is anchored on <c>client/CcpClient.sln</c> (present in every checkout and in a
/// worktree). Root-not-found, a missing census document, <b>and a missing reference tree</b> are all
/// hard FAILURES. <see cref="HapticSiteCensusTests"/> and <c>FypCensusTests</c> instead carry an
/// "unreachable reference tree" branch for a fully-absent <c>ConditioningControlPanel/</c>; this
/// guard does not, for three independent reasons that all point the same way. (1) The SP-127 packet
/// asked for exactly this: a missing reference tree FAILS rather than skips. (2) That tree is
/// in-repo, so the branch is unreachable on every real checkout and buys nothing. (3) The branch's
/// SHAPE — an early return past a filesystem predicate — is a silencing shape that
/// <see cref="VacuousShapeDetector"/> refuses without a disposition in
/// <c>client/tests/floor/vacuous-shape-ledger.json</c>, and that file is outside this packet's write
/// scope. So the branch is not merely unnecessary here, it is unrepresentable: this guard cannot
/// pass without the reference tree, which is a stronger property than the precedent's and never a
/// skip. Filesystem predicates live in the helpers at the bottom for the same reason.</para>
///
/// <para>The fixture facts pin the walker, the parser, the extractor and the document-shape comparer
/// against temp-dir and in-memory inputs, so none of this rests on today's tree happening to
/// agree.</para>
/// </summary>
public sealed class TrainerCardCensusTests
{
    private const string CensusRelativePath = "client/docs/trainer-card-census.md";

    private static readonly string[] RepoAnchorParts = ["client", "CcpClient.sln"];
    private static readonly string[] CensusParts = ["client", "docs", "trainer-card-census.md"];
    private static readonly string[] WpfRootParts = ["ConditioningControlPanel"];

    /// <summary>The censused trees: DIRECTORIES, searched whole and recursively. NOT a file list —
    /// a file list is exactly how the haptic count lost <c>VideoService.Browser.cs</c> twice and how
    /// the FYP count lost an entire subdirectory. The keys match the census's §9.1 table.</summary>
    private static readonly string[] CensusedDirectories =
    [
        "Views/Controls",
        "Views/Controls/Companion",
        "Views/Controls/AppSettings",
        "Views/Controls/Studio",
        "Services/Profile",
        "Services/Progression",
        "Resources/cosmetics",
        "Resources/banners",
        "Resources/achievements",
    ];

    /// <summary>Patterns over GENERATED bytes only. No source file is excluded by name.</summary>
    private static readonly string[] GeneratedDirectories = ["bin", "obj", ".git", "__pycache__", "node_modules"];

    /// <summary>The five thresholds the census pins, each re-derived from the file named here by the
    /// regex named here. The VALUE is never read from the document.</summary>
    private static readonly (string Key, string File, string Pattern)[] Thresholds =
    [
        ("HonorRollCategories", "Services/GamificationBridge.cs", @"HonorRollCategories\s*=\s*(\d+)"),
        ("TeachersPetPasses", "Services/GamificationBridge.cs", @"TeachersPetPasses\s*=\s*(\d+)"),
        ("HeldBackFailStreak", "Services/GamificationBridge.cs", @"HeldBackFailStreak\s*=\s*(\d+)"),
        ("TopMarksPercent", "Services/Quiz/IntakeHostService.cs", @"TopMarksPercent\s*=\s*([\d.]+)"),
        ("MaxPinnedAchievements", "Models/ProfileCosmetics.cs", @"MaxPinnedAchievements\s*=\s*(\d+)"),
    ];

    private const string PortNormalisationFile = "client/src/CcpClient.Desktop/Features/Intake/IntakeQuizRun.cs";
    private const string NormalisationExpression = "run.Niche.Trim().ToLowerInvariant()";

    /// <summary>The reachable, verified reference: repo root, census text, shipping tree.</summary>
    private sealed record Reference(string Root, string Census, string Wpf);

    // ---------------------------------------------------------------------------------------
    // Facts over the shipping bytes
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void EveryDirectoryCountInTheCensus_ReDerivesFromTheShippingBytes()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 9.1");
        Assert.Equal(CensusedDirectories.Length, declared.Count);

        var drift = new List<string>();
        foreach (var relative in CensusedDirectories)
        {
            var actual = CountFilesUnder(reference.Wpf, relative);
            Assert.True(declared.TryGetValue(relative, out var written),
                $"the census does not declare a count for {relative}");
            if (written != actual.ToString()) drift.Add($"{relative}: census says {written}, the bytes say {actual}");
        }

        Assert.True(drift.Count == 0, string.Join("; ", drift));
    }

    /// <summary>The finding the row's own number hides. The total 113/114 was RIGHT; what makes it
    /// misleading is the split, so the split is what gets pinned.</summary>
    [Fact]
    public void TheViewsControlsCount_IsOverwhelminglyNotThisFeature()
    {
        var reference = RequireReference();

        var total = CountFilesUnder(reference.Wpf, "Views/Controls");
        var foreign = CountFilesUnder(reference.Wpf, "Views/Controls/Companion")
                      + CountFilesUnder(reference.Wpf, "Views/Controls/AppSettings")
                      + CountFilesUnder(reference.Wpf, "Views/Controls/Studio");

        Assert.True(foreign < total, "the subtrees cannot exceed the tree that contains them");
        // The share is pinned EXACTLY, not behind a threshold. Code review's point: a `> 0.90`
        // assertion would have survived a drift from 95.6% all the way to 91%, and the share IS the
        // claim. Every term below re-derives from the shipping bytes.
        var declared = ParseKeyValueTable(reference.Census, "### 9.5");
        Assert.Equal(declared["views-controls-total"], total.ToString());
        Assert.Equal(declared["views-controls-foreign"], foreign.ToString());

        var sharePercent = Math.Round(foreign * 100.0 / total, 1);
        Assert.Equal(declared["views-controls-foreign-share-percent"],
            sharePercent.ToString("0.0", System.Globalization.CultureInfo.InvariantCulture));

        // The four Trainer Card files are found by PREFIX over the directory, never as a list.
        var trainerCard = TopLevelNamesUnder(reference.Wpf, "Views/Controls")
            .Where(n => n.StartsWith("AdornedAvatar", StringComparison.Ordinal)
                        || n.StartsWith("ProfilePrivacyPanel", StringComparison.Ordinal))
            .ToList();
        Assert.Equal(declared["views-controls-trainer-card"], trainerCard.Count.ToString());
        Assert.Equal(4, trainerCard.Count);
    }

    [Fact]
    public void TheWardrobeRegistry_ReDerivesItsItemTypeAndGateCounts()
    {
        var reference = RequireReference();
        var text = ReadShippingFile(reference.Wpf, "Resources/cosmetics/registry.json");

        var items = Regex.Matches(text, "\"type\"\\s*:\\s*\"(?<type>[^\"]+)\"").Count;
        var deco = Regex.Matches(text, "\"type\"\\s*:\\s*\"deco\"").Count;
        var charm = Regex.Matches(text, "\"type\"\\s*:\\s*\"charm\"").Count;
        var gated = Regex.Matches(text, "\"unlock\"\\s*:\\s*\"achievement:").Count;
        var free = Regex.Matches(text, "\"unlock\"\\s*:\\s*\"free\"").Count;

        var declared = ParseKeyValueTable(reference.Census, "### 9.2");
        Assert.Equal(items.ToString(), declared["registry-items"]);
        Assert.Equal(deco.ToString(), declared["registry-deco"]);
        Assert.Equal(charm.ToString(), declared["registry-charm"]);
        Assert.Equal(gated.ToString(), declared["registry-achievement-gated"]);
        Assert.Equal(free.ToString(), declared["registry-free"]);
        Assert.Equal(items, deco + charm);
        Assert.Equal(items, gated + free);

        // The row said "60 adornments". The bytes say otherwise, and that is a census finding, so
        // the guard refuses the row's number rather than only recording the real one.
        Assert.True(items > 60, "the census's §1.6 finding is that the row's 60 understates the registry");
    }

    [Fact]
    public void EveryWardrobeRegistryEntry_ResolvesToARealAssetFile()
    {
        var reference = RequireReference();
        var unresolved = UnresolvedRegistryEntries(reference.Wpf);

        var declared = ParseKeyValueTable(reference.Census, "### 9.2");
        Assert.Equal(unresolved.Count.ToString(), declared["registry-unresolved-files"]);
        Assert.True(unresolved.Count == 0,
            "a wardrobe entry pointing at a missing PNG would make the census's asset count a fiction: "
            + string.Join(", ", unresolved.Take(5)));
    }

    [Fact]
    public void EveryThresholdInTheCensus_ReDerivesFromTheShippingSource()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 9.3");
        Assert.Equal(Thresholds.Length, declared.Count);

        var drift = new List<string>();
        foreach (var (key, file, pattern) in Thresholds)
        {
            var actual = ExtractOne(ReadShippingFile(reference.Wpf, file), pattern);
            if (actual is null) drift.Add($"{key}: no longer present in {file}");
            else if (!declared.TryGetValue(key, out var written) || written != actual)
                drift.Add($"{key}: census says {(declared.TryGetValue(key, out var w) ? w : "(absent)")}, {file} says {actual}");
        }

        Assert.True(drift.Count == 0, string.Join("; ", drift));
    }

    /// <summary>The correctness trap the packet named. Two producers of ONE deliberately
    /// source-agnostic event disagree about normalisation, and the set that holds the result is
    /// ordinal. Re-derived from all four files so an upstream change reds this rather than leaving a
    /// stale sentence in a document.</summary>
    [Fact]
    public void TheTwoRaiseSites_DisagreeAboutNormalising_AndTheDistinctSetIsOrdinal()
    {
        var reference = RequireReference();

        var intake = ReadShippingFile(reference.Wpf, "Services/Quiz/IntakeHostService.cs");
        var quizWindow = ReadShippingFile(reference.Wpf, "Windows/QuizWindow.xaml.cs");
        var progress = ReadShippingFile(reference.Wpf, "Models/AchievementProgress.cs");
        var bridge = ReadShippingFile(reference.Wpf, "Services/GamificationBridge.cs");

        // Producer A normalises.
        Assert.Contains(NormalisationExpression, intake, StringComparison.Ordinal);

        // Producer B does not: its category is the definition id or the PascalCase enum name.
        Assert.Matches(@"catDef\?\.Id\s*\?\?\s*result\.Category\.ToString\(\)", quizWindow);

        var quizRaise = Regex.Match(quizWindow, @"RaiseQuizCompleted\([^;]*;", RegexOptions.Singleline);
        Assert.True(quizRaise.Success, "QuizWindow no longer raises; the asymmetry may be gone");
        Assert.DoesNotContain("ToLowerInvariant", quizRaise.Value, StringComparison.Ordinal);

        // The distinct set takes no comparer, so it is ordinal and case-sensitive.
        var declaration = Regex.Match(progress, @"HashSet<string>\s+PerfectedQuizCategories[^;]*;");
        Assert.True(declaration.Success, "PerfectedQuizCategories is gone; §5.2 needs re-deriving");
        Assert.DoesNotContain("Comparer", declaration.Value, StringComparison.Ordinal);

        // The consumer adds the raw value.
        Assert.Matches(@"PerfectedQuizCategories\.Add\(e\.Category\)", bridge);

        var declared = ParseKeyValueTable(reference.Census, "### 9.4");
        Assert.Equal("Services/Quiz/IntakeHostService.cs", declared["upstream-normalises"]);
        Assert.Equal("Windows/QuizWindow.xaml.cs", declared["upstream-does-not-normalise"]);
        Assert.Equal("default", declared["distinct-set-comparer"]);
    }

    [Fact]
    public void ThePortsNormalisation_IsVerbatimTheUpstreamExpression()
    {
        var reference = RequireReference();
        var port = ReadRepoFile(reference.Root, PortNormalisationFile);
        var intake = ReadShippingFile(reference.Wpf, "Services/Quiz/IntakeHostService.cs");

        // The same expression text, taken from the shipping bytes on both sides.
        Assert.Contains(NormalisationExpression, port, StringComparison.Ordinal);
        Assert.Contains("IntakeNiche.Fallback", port, StringComparison.Ordinal);
        Assert.Contains(NormalisationExpression, intake, StringComparison.Ordinal);
        Assert.Contains("IntakeNiche.Fallback", intake, StringComparison.Ordinal);

        var declared = ParseKeyValueTable(reference.Census, "### 9.4");
        Assert.Equal("true", declared["port-normalisation-matches"]);
    }
    /// <summary>The fact the D222 chain actually rests on, added at code review.
    ///
    /// <para>§9.4 originally pinned PATHS only, and
    /// <see cref="TheTwoRaiseSites_DisagreeAboutNormalising_AndTheDistinctSetIsOrdinal"/> matches the
    /// producer expression ANYWHERE in the file. That is green whether the census cites the right
    /// line or not — and it was not: three citations in the census were wrong, one of them the
    /// unnormalised producer's own line in §5.2 and in D222, the most owner-facing number in the
    /// packet. A pin that cannot see the number it is protecting is not protecting it.</para>
    ///
    /// <para><b>And this fact immediately earned itself.</b> The expression
    /// <c>catDef?.Id ?? result.Category.ToString()</c> occurs FOUR times in <c>QuizWindow.xaml.cs</c>
    /// — the history entry, a settings write, the raise path, and a session-text generator — so a
    /// grep-written citation lands on the FIRST one and is wrong by 63 lines. The raise-path site is
    /// therefore pinned STRUCTURALLY, as the line immediately above the file's single
    /// <c>RaiseQuizCompleted</c> call, which is what the citation actually means and what survives
    /// upstream drift.</para></summary>
    [Fact]
    public void TheDefectChainsLineNumbers_ReDeriveFromTheShippingBytes()
    {
        var reference = RequireReference();
        var declared = ParseKeyValueTable(reference.Census, "### 9.4");

        var quizWindow = ReadShippingFile(reference.Wpf, "Windows/QuizWindow.xaml.cs");
        var bridge = ReadShippingFile(reference.Wpf, "Services/GamificationBridge.cs");
        var intake = ReadShippingFile(reference.Wpf, "Services/Quiz/IntakeHostService.cs");

        // "The raise" is well-defined: QuizWindow makes exactly one.
        Assert.Equal(1, OccurrenceCount(quizWindow, @"QuizService\.RaiseQuizCompleted\("));
        var raiseLine = LineNumberOf(quizWindow, @"QuizService\.RaiseQuizCompleted\(");

        // The unnormalised producer is the line immediately above it.
        var producerLine = raiseLine - 1;
        Assert.Matches(@"var\s+categoryId\s*=\s*catDef\?\.Id\s*\?\?\s*result\.Category\.ToString\(\)",
            LineAt(quizWindow, producerLine));
        Assert.Equal(declared["unnormalised-producer-line"], producerLine.ToString());
        Assert.DoesNotContain("ToLowerInvariant", LineAt(quizWindow, producerLine), StringComparison.Ordinal);

        // The trap that produced the wrong citation, pinned so it cannot be forgotten: the bare
        // expression is NOT unique in this file, and only one of its sites feeds the raise.
        Assert.Equal(declared["unnormalised-producer-expression-occurrences"],
            OccurrenceCount(quizWindow, @"catDef\?\.Id\s*\?\?\s*result\.Category\.ToString\(\)").ToString());

        // The distinct-set add that takes the category raw.
        var addLine = LineNumberOf(bridge, @"PerfectedQuizCategories\.Add\(e\.Category\)");
        Assert.Equal(declared["distinct-set-add-line"], addLine.ToString());
        Assert.Equal(1, OccurrenceCount(bridge, @"PerfectedQuizCategories\.Add\(e\.Category\)"));

        // The normalising producer, so both halves of the asymmetry are pinned by number.
        var normalisingLine = LineNumberOf(intake, Regex.Escape(NormalisationExpression));
        Assert.Equal(declared["normalising-producer-line"], normalisingLine.ToString());
    }


    // ---------------------------------------------------------------------------------------
    // Facts over the document's shape (legitimate: their subject IS the document)
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void EveryBehaviourRow_CarriesOneLabelAndAPlatformCell()
    {
        var rows = BehaviourRows(RequireReference().Census);
        Assert.True(rows.Count >= 10, $"expected the full behaviour map, found {rows.Count} rows");

        foreach (var row in rows)
        {
            var labels = new[] { "COVERED", "PARTIAL", "GAP:", "OWNER-GATED" }
                .Count(l => row.Contains(l, StringComparison.Ordinal));
            Assert.True(labels >= 1, $"unlabelled behaviour row: {Head(row)}");
            Assert.True(row.Contains("Windows:", StringComparison.Ordinal), $"no Windows cell: {Head(row)}");
            Assert.True(row.Contains("Linux:", StringComparison.Ordinal), $"no Linux cell: {Head(row)}");
        }
    }

    /// <summary>There is no WSL distro on this machine, so a Linux cell claiming proof would be a
    /// laundered Windows-only result — the exact thing <c>docs/constitution.md:36</c> forbids.</summary>
    [Fact]
    public void NoBehaviourRow_ClaimsLinuxIsProven()
    {
        var rows = BehaviourRows(RequireReference().Census);
        Assert.NotEmpty(rows);

        foreach (var row in rows)
            Assert.DoesNotContain("Linux: proven", row, StringComparison.Ordinal);
    }

    [Fact]
    public void TheFourPrivacyQuestions_AreAllAnsweredAndTheSensorAnswerIsNone()
    {
        var census = RequireReference().Census;
        Assert.All(new[] { "| Q1 |", "| Q2 |", "| Q3 |", "| Q4 |" },
            q => Assert.Contains(q, census, StringComparison.Ordinal));

        // This surface differs from For You Feed exactly here, and the difference is load-bearing
        // for the verdict: no sensor means the capability-inventory sensor gate never fires.
        var q4 = census.Split('\n').Single(l => l.TrimStart().StartsWith("| Q4 |", StringComparison.Ordinal));
        Assert.Contains("NONE", q4, StringComparison.Ordinal);
    }

    [Fact]
    public void TheCensusDeclaresExactlyOneVerdictFromTheClosedSet()
    {
        var census = RequireReference().Census;
        var verdicts = new[] { "Verdict: BUILDABLE-IN-PART", "Verdict: REFUSED", "Verdict: BUILDABLE," };
        Assert.Equal(1, verdicts.Count(v => census.Contains(v, StringComparison.Ordinal)));
    }

    [Fact]
    public void TheOwnerGatedSection_IsNotFoldedIntoTheSize()
    {
        var census = RequireReference().Census;
        Assert.Contains("OWNER-FLAGGED", census, StringComparison.Ordinal);
        Assert.Contains("deliberately not priced", census, StringComparison.Ordinal);

        // The buildable unit's inventory must state what it needs from the owner, otherwise the
        // verdict has folded a gated behaviour into a size.
        Assert.Contains("Owner decisions required", census, StringComparison.Ordinal);
    }

    [Fact]
    public void TheCensusStatesWhatItDoesNotProve()
    {
        var census = RequireReference().Census;
        Assert.Contains("does NOT prove", census, StringComparison.Ordinal);
        Assert.Contains("No headed evidence", census, StringComparison.Ordinal);
        Assert.Contains("Linux is unproven for every row", census, StringComparison.Ordinal);
    }

    /// <summary>A bare pipe inside a code span silently truncates a markdown row — how D197 and D209
    /// lost their disposition and rationale, found only at a final review.</summary>
    [Fact]
    public void NoTableRow_CarriesAnUnescapedPipeInsideACodeSpan()
    {
        var offenders = UnescapedPipesInCodeSpans(RequireReference().Census);
        Assert.True(offenders.Count == 0, string.Join("; ", offenders));
    }

    // ---------------------------------------------------------------------------------------
    // Fixture facts — the machinery pinned against temp-dir and in-memory inputs
    // ---------------------------------------------------------------------------------------

    [Fact]
    public void TheWalker_CountsRealFilesRecursivelyAndIgnoresGeneratedBytesOnly()
    {
        var files = WalkTempTreeFixture();

        // Three real files, recursively. The DOTTED source file is KEPT: nothing is excluded by
        // name, only whole generated-byte directories are skipped.
        Assert.Equal(3, files.Count);
        Assert.Contains(files, f => f.EndsWith(".gitkeep", StringComparison.Ordinal));
        Assert.Contains(files, f => f.EndsWith("b.xaml", StringComparison.Ordinal));
        Assert.DoesNotContain(files, f => f.Contains("generated.cs", StringComparison.Ordinal));
        Assert.DoesNotContain(files, f => f.Contains("dep.js", StringComparison.Ordinal));
    }

    [Fact]
    public void TheKeyValueParser_ReadsATable_AndASeededDriftIsVisibleToTheComparer()
    {
        const string doc = """
            ### 9.1 Product

            | Key | Value |
            |---|---|
            | Views/Controls | 114 |
            | Services/Profile | 3 |

            ### 9.2 Other

            | Key | Value |
            |---|---|
            | registry-items | 79 |
            """;

        var first = ParseKeyValueTable(doc, "### 9.1");
        Assert.Equal(2, first.Count);
        Assert.Equal("114", first["Views/Controls"]);
        Assert.Equal("3", first["Services/Profile"]);

        // Sectioning is real: §9.2's row must not leak into §9.1.
        Assert.False(first.ContainsKey("registry-items"));
        Assert.Equal("79", ParseKeyValueTable(doc, "### 9.2")["registry-items"]);

        // A seeded drift is a mismatch, which is what the live facts assert on.
        Assert.NotEqual("113", first["Views/Controls"]);
    }

    [Fact]
    public void TheThresholdExtractor_FindsAConstant_AndReturnsNullWhenItIsGone()
    {
        Assert.Equal("3", ExtractOne("private const int HonorRollCategories = 3;  // 3 different",
            @"HonorRollCategories\s*=\s*(\d+)"));
        Assert.Equal("90.0", ExtractOne("const double TopMarksPercent = 90.0;",
            @"TopMarksPercent\s*=\s*([\d.]+)"));
        Assert.Null(ExtractOne("nothing here", @"HonorRollCategories\s*=\s*(\d+)"));
    }

    [Fact]
    public void ThePipeGuard_CatchesASeededBarePipeAndPassesTheEscapedForm()
    {
        Assert.Single(UnescapedPipesInCodeSpans("| a | `WS_EX_LAYERED | WS_EX_TRANSPARENT` | b |"));
        Assert.Empty(UnescapedPipesInCodeSpans(@"| a | `WS_EX_LAYERED \| WS_EX_TRANSPARENT` | b |"));

        // Prose outside a table row is not the failure mode D197 and D209 hit.
        Assert.Empty(UnescapedPipesInCodeSpans("a sentence with `a | b` in it"));
    }

    [Fact]
    public void TheBehaviourRowReader_SeesOnlyLabelledBehaviourRows()
    {
        const string doc = """
            | # | Owner's phrase | Label | Platform |
            |---|---|---|---|
            | B1 | a thing | **COVERED by x** | Windows: unproven. Linux: unproven |
            | B2 | another | **GAP: y** | Windows: unproven. Linux: unproven |
            | C1 | not a behaviour row | PRESENT | |
            """;

        var rows = BehaviourRows(doc);
        Assert.Equal(2, rows.Count);
        Assert.All(rows, r => Assert.Contains("Linux:", r, StringComparison.Ordinal));
    }

    // ---------------------------------------------------------------------------------------
    // Machinery. Every filesystem predicate lives HERE, never in a fact body, so no fact carries
    // a silencing shape and none of them can be satisfied by an absent tree.
    // ---------------------------------------------------------------------------------------

    /// <summary>Resolves the repo root, the census and the shipping tree. All three are hard
    /// requirements: this guard fails rather than skipping on any of them.</summary>
    private static Reference RequireReference()
    {
        var root = FindRepoRoot();
        Assert.True(root is not null,
            $"repo root not found (anchor: {string.Join('/', RepoAnchorParts)}); this guard never skips");

        var censusPath = Path.Combine(root!, Path.Combine(CensusParts));
        RequirePath(censusPath, isDirectory: false, $"{CensusRelativePath} is missing; this guard never skips");

        var wpf = Path.Combine(root!, Path.Combine(WpfRootParts));
        RequirePath(wpf, isDirectory: true,
            $"{WpfRootParts[0]}/ is missing. The reference tree is IN THIS REPOSITORY, so its absence is a "
            + "corrupt checkout, not an environment this guard may pass in.");

        return new Reference(root!, File.ReadAllText(censusPath), wpf);
    }

    private static void RequirePath(string path, bool isDirectory, string because)
    {
        var present = isDirectory ? Directory.Exists(path) : File.Exists(path);
        Assert.True(present, because);
    }

    private static string? FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, Path.Combine(RepoAnchorParts)))) return dir.FullName;
            dir = dir.Parent;
        }

        return null;
    }

    private static string Resolve(string root, string relative) =>
        Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar));

    /// <summary>A censused directory that has gone missing is a HALF-PRESENT reference tree, i.e. a
    /// corrupt checkout, and fails.</summary>
    private static int CountFilesUnder(string wpf, string relative)
    {
        var dir = Resolve(wpf, relative);
        RequirePath(dir, isDirectory: true,
            $"HALF-PRESENT reference tree: {WpfRootParts[0]}/ exists but {relative} does not. Corrupt checkout.");
        return WalkFiles(dir).Count;
    }

    private static IEnumerable<string> TopLevelNamesUnder(string wpf, string relative) =>
        Directory.GetFiles(Resolve(wpf, relative)).Select(p => Path.GetFileName(p)!);

    private static string ReadShippingFile(string wpf, string relative)
    {
        var path = Resolve(wpf, relative);
        RequirePath(path, isDirectory: false, $"HALF-PRESENT reference tree: {relative} is missing");
        return File.ReadAllText(path);
    }

    private static string ReadRepoFile(string root, string relative)
    {
        var path = Resolve(root, relative);
        RequirePath(path, isDirectory: false, $"{relative} is required by this pin and is missing");
        return File.ReadAllText(path);
    }

    private static List<string> UnresolvedRegistryEntries(string wpf)
    {
        var cosmetics = Resolve(wpf, "Resources/cosmetics");
        var text = ReadShippingFile(wpf, "Resources/cosmetics/registry.json");

        var unresolved = new List<string>();
        foreach (Match m in Regex.Matches(text, "\"file\"\\s*:\\s*\"(?<file>[^\"]+)\""))
        {
            var relative = m.Groups["file"].Value.Replace('\\', Path.DirectorySeparatorChar)
                                                 .Replace('/', Path.DirectorySeparatorChar);
            if (!File.Exists(Path.Combine(cosmetics, relative))) unresolved.Add(relative);
        }

        return unresolved;
    }

    /// <summary>Recursive directory walk. Generated-byte directories are skipped; nothing is skipped
    /// by source-file name. Symlinked directories are not followed.</summary>
    private static List<string> WalkFiles(string root)
    {
        var found = new List<string>();
        var stack = new Stack<string>();
        stack.Push(root);

        while (stack.Count > 0)
        {
            var dir = stack.Pop();
            foreach (var child in Directory.GetDirectories(dir))
            {
                if (GeneratedDirectories.Contains(Path.GetFileName(child))) continue;
                if (new DirectoryInfo(child).LinkTarget is not null) continue;
                stack.Push(child);
            }

            found.AddRange(Directory.GetFiles(dir));
        }

        return found;
    }

    /// <summary>Builds a throwaway tree containing one file of every class the walker must decide
    /// about, walks it, and cleans up. Kept out of the fact body so the fact's assertions sit at the
    /// top level rather than inside a try/finally.</summary>
    private static List<string> WalkTempTreeFixture()
    {
        var temp = Path.Combine(Path.GetTempPath(), "sp127-" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(Path.Combine(temp, "sub"));
            Directory.CreateDirectory(Path.Combine(temp, "obj"));
            Directory.CreateDirectory(Path.Combine(temp, "node_modules"));
            File.WriteAllText(Path.Combine(temp, "a.cs"), "");
            File.WriteAllText(Path.Combine(temp, "sub", "b.xaml"), "");
            File.WriteAllText(Path.Combine(temp, "sub", ".gitkeep"), "");
            File.WriteAllText(Path.Combine(temp, "obj", "generated.cs"), "");
            File.WriteAllText(Path.Combine(temp, "node_modules", "dep.js"), "");

            return WalkFiles(temp);
        }
        finally
        {
            Directory.Delete(temp, recursive: true);
        }
    }

    /// <summary>Reads the first two-column table after <paramref name="heading"/>, stopping at the
    /// next heading so sections cannot leak into each other.</summary>
    private static Dictionary<string, string> ParseKeyValueTable(string document, string heading)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        var lines = document.Split('\n');
        var index = Array.FindIndex(lines, l => l.TrimEnd('\r').StartsWith(heading, StringComparison.Ordinal));
        if (index < 0) return result;

        for (var i = index + 1; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (line.StartsWith("##", StringComparison.Ordinal)) break;
            if (!line.StartsWith('|')) continue;

            var cells = SplitRow(line);
            if (cells.Count < 2) continue;
            if (cells[0] is "Key" or "#" or "Id") continue;
            if (cells[0].Length > 0 && cells[0].All(c => c is '-' or ':')) continue;

            result[cells[0]] = cells[1];
        }

        return result;
    }

    private static List<string> SplitRow(string line)
    {
        var trimmed = line.Trim();
        if (trimmed.StartsWith('|')) trimmed = trimmed[1..];
        if (trimmed.EndsWith('|')) trimmed = trimmed[..^1];

        return trimmed.Split('|')
            .Select(c => c.Trim().Trim('`', '*').Trim())
            .ToList();
    }

    private static List<string> BehaviourRows(string document) =>
        document.Split('\n')
            .Select(l => l.Trim())
            .Where(l => Regex.IsMatch(l, @"^\|\s*B\d+\s*\|"))
            .ToList();

    private static List<string> UnescapedPipesInCodeSpans(string document)
    {
        var offenders = new List<string>();
        var lineNumber = 0;
        foreach (var line in document.Split('\n'))
        {
            lineNumber++;
            if (!line.TrimStart().StartsWith('|')) continue;
            foreach (Match span in Regex.Matches(line, "`[^`]*`"))
                if (span.Value.Contains('|') && !span.Value.Contains("\\|", StringComparison.Ordinal))
                    offenders.Add($"line {lineNumber}: {span.Value}");
        }

        return offenders;
    }


    /// <summary>1-based line number of the first line matching <paramref name="pattern"/>, or 0.
    /// Line-oriented on purpose: a citation is a line number, so the pin must be computed the way a
    /// reader would check it.</summary>
    private static int LineNumberOf(string text, string pattern)
    {
        var lines = text.Split('\n');
        for (var i = 0; i < lines.Length; i++)
            if (Regex.IsMatch(lines[i], pattern)) return i + 1;

        return 0;
    }

    private static int OccurrenceCount(string text, string pattern) =>
        text.Split('\n').Count(l => Regex.IsMatch(l, pattern));

    /// <summary>The 1-based line, or empty when out of range. Empty never matches the producer
    /// pattern, so an off-by-one in the structural pin fails rather than silently passing.</summary>
    private static string LineAt(string text, int oneBasedLine)
    {
        var lines = text.Split('\n');
        return oneBasedLine >= 1 && oneBasedLine <= lines.Length ? lines[oneBasedLine - 1] : string.Empty;
    }
    private static string? ExtractOne(string text, string pattern)
    {
        var match = Regex.Match(text, pattern);
        return match.Success ? match.Groups[1].Value : null;
    }

    private static string Head(string row) => row.Length <= 80 ? row : row[..80];
}
