using System;
using System.IO;
using System.Linq;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using Newtonsoft.Json;
using OpenCvSharp;
using CvRect = OpenCvSharp.Rect;
using CvSize = OpenCvSharp.Size;

namespace ConditioningControlPanel.Services
{
    // The three MediaPipe ONNX detectors, shared by every head. Frames are only ever held in
    // memory here - see the PRIVACY CONTRACT atop WebcamTrackingService.

    // ─────────────────────────────────────────────────────────────────────────
    //  BlazeFace short-range detector (MediaPipe)
    //  ────────────────────────────────────────────────────────────────────────
    //  Loads face_detection_short_range.onnx + the precomputed 896 SSD anchors
    //  (blazeface_anchors.json, generated by IntelliProve's _ssd_generate_anchors
    //  with SSD_OPTIONS_SHORT, ported in the phase-1 spike — bit-exact match
    //  against Python reference, see /tmp/blazeface-spike/).
    //
    //  The detector accepts a BGR Mat of arbitrary size, letterbox-resizes to
    //  128×128, normalizes to [-1,1], runs inference, picks the top-1 anchor
    //  above 0.5 sigmoid score, decodes the box, and unpads back to source-frame
    //  pixel coordinates.
    //
    //  This is a CPU-only inference path. Anchors and ONNX session are loaded
    //  once at Start() and reused across frames; no per-frame allocations beyond
    //  the input tensor buffer.
    // ─────────────────────────────────────────────────────────────────────────
    public sealed class BlazeFaceDetector : IDisposable
    {
        private const int InputSize = 128;
        private const float InputScale = 128f;
        private const float MinSigmoidScore = 0.5f;
        private const float RawScoreLimit = 80f;
        private const int NumAnchors = 896;
        private const int RegressorsPerAnchor = 16;   // [cx, cy, w, h, kp0x, kp0y ... kp5x, kp5y]
        // Below this raw logit we know sigmoid ≤ MinSigmoidScore=0.5; skip the exp.
        // logit(0.5) = 0; we filter with raw>0 then sigmoid only the survivors.
        private const float RawScoreCheap = 0f;

        private readonly InferenceSession _session;
        private readonly float[] _anchorsFlat;        // length 2*NumAnchors (x,y interleaved)
        private readonly string _inputName;

        // Reusable buffers (capture-thread-only access; no locking needed).
        private readonly float[] _inputBuffer = new float[InputSize * InputSize * 3];
        // Cached byte staging buffer for the BGR→RGB float conversion in
        // FillInputBufferFromBgr — at ~49KB per BlazeFace frame this would
        // otherwise allocate fresh each frame. Caching it drops Gen0
        // pressure noticeably across the three detectors.
        private readonly byte[] _byteBuffer = new byte[InputSize * InputSize * 3];
        private Mat? _resizeBuffer;       // 128×96 (or whatever the aspect-preserving size is)
        private Mat? _paddedBuffer;       // 128×128

        public BlazeFaceDetector(string modelPath, string anchorsJsonPath)
        {
            var so = new SessionOptions
            {
                GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL,
                InterOpNumThreads = 1,
                IntraOpNumThreads = 2,
            };
            _session = new InferenceSession(modelPath, so);
            _inputName = _session.InputMetadata.Keys.First();

            var json = File.ReadAllText(anchorsJsonPath);
            var nested = JsonConvert.DeserializeObject<float[][]>(json)
                ?? throw new InvalidOperationException("blazeface_anchors.json: deserialized null");
            if (nested.Length != NumAnchors)
                throw new InvalidOperationException($"blazeface_anchors.json: expected {NumAnchors} anchors, got {nested.Length}");
            _anchorsFlat = new float[NumAnchors * 2];
            for (int i = 0; i < NumAnchors; i++)
            {
                if (nested[i].Length != 2)
                    throw new InvalidOperationException($"blazeface_anchors.json: anchor[{i}] not 2 values");
                _anchorsFlat[2 * i + 0] = nested[i][0];
                _anchorsFlat[2 * i + 1] = nested[i][1];
            }
        }

        /// <summary>
        /// Detects the most-confident face in <paramref name="bgr"/>. Returns the
        /// face rect in source-image pixel coords, clipped to the source bounds,
        /// or null if no face above MinSigmoidScore.
        /// </summary>
        public CvRect? Detect(Mat bgr)
        {
            int srcW = bgr.Width, srcH = bgr.Height;
            if (srcW <= 0 || srcH <= 0) return null;

            // Letterbox-resize: scale so the longer side fills 128 px, pad the
            // shorter side with black to a square 128×128. This preserves face
            // aspect ratio (the model was trained on undistorted faces).
            float scale = Math.Min((float)InputSize / srcW, (float)InputSize / srcH);
            int newW = Math.Max(1, (int)Math.Round(srcW * scale));
            int newH = Math.Max(1, (int)Math.Round(srcH * scale));
            int padX = (InputSize - newW) / 2;
            int padY = (InputSize - newH) / 2;

            if (_resizeBuffer == null || _resizeBuffer.Width != newW || _resizeBuffer.Height != newH)
            {
                _resizeBuffer?.Dispose();
                _resizeBuffer = new Mat();
            }
            if (_paddedBuffer == null)
            {
                _paddedBuffer = new Mat(InputSize, InputSize, MatType.CV_8UC3, Scalar.All(0));
            }
            else
            {
                _paddedBuffer.SetTo(Scalar.All(0));
            }

            Cv2.Resize(bgr, _resizeBuffer, new CvSize(newW, newH), 0, 0, InterpolationFlags.Linear);
            using (var roi = new Mat(_paddedBuffer, new CvRect(padX, padY, newW, newH)))
            {
                _resizeBuffer.CopyTo(roi);
            }

            // BGR → RGB and normalize to [-1, 1] in channel-last order.
            // We avoid an extra Mat allocation by walking the padded buffer directly.
            FillInputBufferFromBgr(_paddedBuffer, _inputBuffer, _byteBuffer);

            var inputTensor = new DenseTensor<float>(_inputBuffer, new[] { 1, InputSize, InputSize, 3 });
            using var results = _session.Run(new[] { NamedOnnxValue.CreateFromTensor(_inputName, inputTensor) });

            var rawBoxes = results.First(r => r.Name == "regressors").AsTensor<float>();
            var rawScores = results.First(r => r.Name == "classificators").AsTensor<float>();

            // Find best anchor above threshold (raw>0 ⇒ sigmoid>0.5).
            int bestIdx = -1;
            float bestRaw = float.NegativeInfinity;
            for (int i = 0; i < NumAnchors; i++)
            {
                float raw = rawScores[0, i, 0];
                if (raw > bestRaw) { bestRaw = raw; bestIdx = i; }
            }
            if (bestIdx < 0 || bestRaw <= RawScoreCheap) return null;

            // Sigmoid only the winner — cheaper than computing all 896.
            float clipped = bestRaw > RawScoreLimit ? RawScoreLimit : (bestRaw < -RawScoreLimit ? -RawScoreLimit : bestRaw);
            float sig = 1f / (1f + (float)Math.Exp(-clipped));
            if (sig < MinSigmoidScore) return null;

            // Decode box: cx,cy,w,h are anchor offsets (in 128-px units), normalize.
            float ax = _anchorsFlat[2 * bestIdx + 0];
            float ay = _anchorsFlat[2 * bestIdx + 1];
            float cx = rawBoxes[0, bestIdx, 0] / InputScale + ax;
            float cy = rawBoxes[0, bestIdx, 1] / InputScale + ay;
            float w  = rawBoxes[0, bestIdx, 2] / InputScale;
            float h  = rawBoxes[0, bestIdx, 3] / InputScale;
            float xmin01 = cx - w / 2f;
            float ymin01 = cy - h / 2f;

            // Convert from 128-px-padded normalized [0,1] → source pixel coords.
            // padded_pixel = norm * 128. Then subtract pad and divide by scale.
            float srcXmin = (xmin01 * InputSize - padX) / scale;
            float srcYmin = (ymin01 * InputSize - padY) / scale;
            float srcW01  = (w * InputSize) / scale;
            float srcH01  = (h * InputSize) / scale;

            int rx = (int)Math.Round(srcXmin);
            int ry = (int)Math.Round(srcYmin);
            int rw = (int)Math.Round(srcW01);
            int rh = (int)Math.Round(srcH01);

            // Final clip to source bounds.
            if (rx < 0) { rw += rx; rx = 0; }
            if (ry < 0) { rh += ry; ry = 0; }
            if (rx + rw > srcW) rw = srcW - rx;
            if (ry + rh > srcH) rh = srcH - ry;
            if (rw <= 0 || rh <= 0) return null;

            return new CvRect(rx, ry, rw, rh);
        }

        private static void FillInputBufferFromBgr(Mat bgr128, float[] dst, byte[] bytes)
        {
            // bgr128 is contiguous CV_8UC3, 128×128. Copy raw bytes once, then
            // rearrange in place: BGR → RGB and uint8 → float in [-1,1].
            if (bgr128.Width != InputSize || bgr128.Height != InputSize || bgr128.Type() != MatType.CV_8UC3)
                throw new InvalidOperationException("FillInputBufferFromBgr: expected 128×128 CV_8UC3");

            int total = InputSize * InputSize;
            System.Runtime.InteropServices.Marshal.Copy(bgr128.Data, bytes, 0, total * 3);
            const float kScale = 2f / 255f;
            for (int i = 0; i < total; i++)
            {
                // OpenCV channel order is BGR; we want RGB at the dst.
                byte b = bytes[3 * i + 0];
                byte g = bytes[3 * i + 1];
                byte r = bytes[3 * i + 2];
                dst[3 * i + 0] = r * kScale - 1f;
                dst[3 * i + 1] = g * kScale - 1f;
                dst[3 * i + 2] = b * kScale - 1f;
            }
        }

        public void Dispose()
        {
            try { _session.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _resizeBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _paddedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            _resizeBuffer = null;
            _paddedBuffer = null;
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  FaceMesh detector (MediaPipe — face_landmark.onnx)
    //  ────────────────────────────────────────────────────────────────────────
    //  Input: 1×192×192×3 RGB normalized to [0, 1] of a 1.5×-expanded square
    //  crop around the BlazeFace face rect.
    //  Output: 1404 floats (468 landmarks × x,y,z) in 192-px tensor coords +
    //  a face-presence sigmoid.
    //
    //  Returns: 468 (x, y) landmarks in source-frame pixel coordinates, or
    //  null if face presence sigmoid < 0.5.
    //
    //  Z is intentionally dropped (not used by gaze/blink). All output coords
    //  stay in float pixel space — caller rounds when needed.
    // ─────────────────────────────────────────────────────────────────────────
    public sealed class FaceMeshDetector : IDisposable
    {
        // FaceMesh eye-corner landmark indices (outer, inner) the iris crop is built from.
        public const int LeftEyeOuterIdx = 33, LeftEyeInnerIdx = 133;
        public const int RightEyeOuterIdx = 263, RightEyeInnerIdx = 362;

        private const int InputSize = 192;
        private const int NumLandmarks = 468;
        private const int LandmarkDims = 3;     // x, y, z (z dropped on output)
        private const float MinPresenceScore = 0.5f;
        private const float RoiScale = 1.5f;    // SquareLong scale around face bbox

        private readonly InferenceSession _session;
        private readonly string _inputName;
        private readonly float[] _inputBuffer = new float[InputSize * InputSize * 3];
        // Cached byte staging buffer — see BlazeFaceDetector for reasoning.
        // 192×192×3 = ~110KB, the largest of the three detectors.
        private readonly byte[] _byteBuffer = new byte[InputSize * InputSize * 3];
        private Mat? _croppedBuffer;            // square crop with black padding
        private Mat? _resizedBuffer;            // 192×192 resized
        private int _lastSide = -1;

        public FaceMeshDetector(string modelPath)
        {
            var so = new SessionOptions
            {
                GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL,
                InterOpNumThreads = 1,
                IntraOpNumThreads = 2,
            };
            _session = new InferenceSession(modelPath, so);
            _inputName = _session.InputMetadata.Keys.First();
        }

        /// <summary>
        /// Detect 468 face landmarks. Returns array of [x, y] in source-frame
        /// pixel coords, or null if no face.
        /// </summary>
        public float[][]? Detect(Mat bgr, CvRect faceRect)
        {
            int srcW = bgr.Width, srcH = bgr.Height;

            // Square ROI around face center, 1.5× the longer side.
            float cx = faceRect.X + faceRect.Width / 2f;
            float cy = faceRect.Y + faceRect.Height / 2f;
            float side = Math.Max(faceRect.Width, faceRect.Height) * RoiScale;
            int rx = (int)Math.Round(cx - side / 2f);
            int ry = (int)Math.Round(cy - side / 2f);
            int rs = (int)Math.Round(side);
            if (rs < 16) return null;

            if (_croppedBuffer == null || _lastSide != rs)
            {
                _croppedBuffer?.Dispose();
                _croppedBuffer = new Mat(rs, rs, MatType.CV_8UC3, Scalar.All(0));
                _lastSide = rs;
            }
            else
            {
                _croppedBuffer.SetTo(Scalar.All(0));
            }
            _resizedBuffer ??= new Mat();

            // Black-padded crop: copy in only the in-bounds portion.
            int sx0 = Math.Max(0, rx);
            int sy0 = Math.Max(0, ry);
            int sx1 = Math.Min(srcW, rx + rs);
            int sy1 = Math.Min(srcH, ry + rs);
            if (sx1 > sx0 && sy1 > sy0)
            {
                int dx0 = sx0 - rx;
                int dy0 = sy0 - ry;
                using var src = new Mat(bgr, new CvRect(sx0, sy0, sx1 - sx0, sy1 - sy0));
                using var dst = new Mat(_croppedBuffer, new CvRect(dx0, dy0, sx1 - sx0, sy1 - sy0));
                src.CopyTo(dst);
            }

            Cv2.Resize(_croppedBuffer, _resizedBuffer, new CvSize(InputSize, InputSize), 0, 0, InterpolationFlags.Linear);
            FillInputBufferFromBgr(_resizedBuffer, _inputBuffer, _byteBuffer);

            var inputTensor = new DenseTensor<float>(_inputBuffer, new[] { 1, InputSize, InputSize, 3 });
            using var results = _session.Run(new[] { NamedOnnxValue.CreateFromTensor(_inputName, inputTensor) });

            // Identify outputs by tensor length rather than by name (the ONNX
            // exporter named them generic conv2d_X).
            Tensor<float>? landmarksRaw = null;
            Tensor<float>? presenceRaw = null;
            foreach (var r in results)
            {
                var t = r.AsTensor<float>();
                long len = 1;
                foreach (var d in t.Dimensions) len *= d;
                if (len >= NumLandmarks * LandmarkDims) landmarksRaw = t;
                else if (len == 1) presenceRaw = t;
            }
            if (landmarksRaw == null || presenceRaw == null) return null;

            float presenceVal = presenceRaw.ToArray()[0];
            float presence = 1f / (1f + (float)Math.Exp(-presenceVal));
            if (presence < MinPresenceScore) return null;

            var raw = landmarksRaw.ToArray();
            var output = new float[NumLandmarks][];
            for (int i = 0; i < NumLandmarks; i++)
            {
                float x192 = raw[i * LandmarkDims + 0];
                float y192 = raw[i * LandmarkDims + 1];
                float nx = x192 / InputSize;
                float ny = y192 / InputSize;
                output[i] = new[] { rx + nx * rs, ry + ny * rs };
            }
            return output;
        }

        private static void FillInputBufferFromBgr(Mat bgr192, float[] dst, byte[] bytes)
        {
            if (bgr192.Width != InputSize || bgr192.Height != InputSize || bgr192.Type() != MatType.CV_8UC3)
                throw new InvalidOperationException("FaceMesh.FillInputBufferFromBgr: expected 192×192 CV_8UC3");

            int total = InputSize * InputSize;
            System.Runtime.InteropServices.Marshal.Copy(bgr192.Data, bytes, 0, total * 3);
            const float kScale = 1f / 255f;
            for (int i = 0; i < total; i++)
            {
                dst[3 * i + 0] = bytes[3 * i + 2] * kScale; // R
                dst[3 * i + 1] = bytes[3 * i + 1] * kScale; // G
                dst[3 * i + 2] = bytes[3 * i + 0] * kScale; // B
            }
        }

        public void Dispose()
        {
            try { _session.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _croppedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _resizedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            _croppedBuffer = null;
            _resizedBuffer = null;
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Iris detector (MediaPipe — iris_landmark.onnx)
    //  ────────────────────────────────────────────────────────────────────────
    //  Input: 1×64×64×3 RGB normalized to [0, 1]. ROI is a 2.3×-expanded
    //  SquareLong bbox of the eye-corner pair. Right eye is flipped horizontally
    //  before inference and the output landmarks are un-flipped (x' = 64 - x)
    //  before mapping back. (The model was trained on left eyes only.)
    //
    //  Output: 71 eyelid contour points + 5 iris points per eye, each (x, y, z)
    //  in 64-px tensor coords. We use iris[0] (CENTER) for gaze and the eye
    //  contour for blink EAR (more responsive to closure than FaceMesh).
    //
    //  Returns: EyeLandmarks containing iris center + 71-point eye contour
    //  in source-frame pixel coords, or null if the eye corners aren't far
    //  enough apart to give a meaningful crop.
    // ─────────────────────────────────────────────────────────────────────────
    public sealed class EyeLandmarks
    {
        public (double X, double Y) IrisCenter;
        public float[][] Contour = System.Array.Empty<float[]>();   // 71 [x, y]
    }

    public sealed class IrisDetector : IDisposable
    {
        private const int InputSize = 64;
        private const float RoiScale = 2.3f;
        private const int NumEyeContour = 71;
        private const int NumIrisPoints = 5;
        private const int LandmarkDims = 3;

        private readonly InferenceSession _session;
        private readonly string _inputName;
        private readonly float[] _inputBuffer = new float[InputSize * InputSize * 3];
        // Cached byte staging buffer — see BlazeFaceDetector for reasoning.
        // 64×64×3 = 12KB; called twice per frame (once per eye) so the
        // saving here doubles up.
        private readonly byte[] _byteBuffer = new byte[InputSize * InputSize * 3];
        private Mat? _croppedBuffer;
        private Mat? _resizedBuffer;
        private Mat? _flippedBuffer;
        private int _lastSide = -1;

        /// <summary>
        /// Side length, in SOURCE-FRAME pixels, of the square eye ROI most
        /// recently fed to the model — i.e. the size BEFORE it is resized to
        /// the fixed <see cref="InputSize"/> (64) input. Diagnostic only,
        /// nothing reads it in the detection path.
        ///
        /// <para>It is the number that decides whether raising capture
        /// resolution could help a given user: at or above 64 the resize is
        /// a DOWNscale and any extra capture pixels are discarded inside
        /// Cv2.Resize; below 64 it is an UPscale and detail is genuinely
        /// missing. Written on the capture thread and read by the same
        /// thread's periodic log line.</para>
        /// </summary>
        public int LastRoiPx { get; private set; }

        public IrisDetector(string modelPath)
        {
            var so = new SessionOptions
            {
                GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL,
                InterOpNumThreads = 1,
                IntraOpNumThreads = 2,
            };
            _session = new InferenceSession(modelPath, so);
            _inputName = _session.InputMetadata.Keys.First();
        }

        public EyeLandmarks? Detect(Mat bgr, float[] outerCorner, float[] innerCorner, bool isRightEye)
        {
            int srcW = bgr.Width, srcH = bgr.Height;

            // Square ROI of the corner-pair bbox, expanded 2.3x.
            float xMin = Math.Min(outerCorner[0], innerCorner[0]);
            float xMax = Math.Max(outerCorner[0], innerCorner[0]);
            float yMin = Math.Min(outerCorner[1], innerCorner[1]);
            float yMax = Math.Max(outerCorner[1], innerCorner[1]);
            float cx = (xMin + xMax) / 2f;
            float cy = (yMin + yMax) / 2f;
            float side = Math.Max(xMax - xMin, yMax - yMin) * RoiScale;
            if (side < 8) return null;
            int rx = (int)Math.Round(cx - side / 2f);
            int ry = (int)Math.Round(cy - side / 2f);
            int rs = (int)Math.Round(side);
            if (rs < InputSize / 4) return null;
            LastRoiPx = rs;

            if (_croppedBuffer == null || _lastSide != rs)
            {
                _croppedBuffer?.Dispose();
                _croppedBuffer = new Mat(rs, rs, MatType.CV_8UC3, Scalar.All(0));
                _lastSide = rs;
            }
            else
            {
                _croppedBuffer.SetTo(Scalar.All(0));
            }
            _resizedBuffer ??= new Mat();
            _flippedBuffer ??= new Mat();

            int sx0 = Math.Max(0, rx);
            int sy0 = Math.Max(0, ry);
            int sx1 = Math.Min(srcW, rx + rs);
            int sy1 = Math.Min(srcH, ry + rs);
            if (sx1 > sx0 && sy1 > sy0)
            {
                using var src = new Mat(bgr, new CvRect(sx0, sy0, sx1 - sx0, sy1 - sy0));
                using var dst = new Mat(_croppedBuffer, new CvRect(sx0 - rx, sy0 - ry, sx1 - sx0, sy1 - sy0));
                src.CopyTo(dst);
            }

            Cv2.Resize(_croppedBuffer, _resizedBuffer, new CvSize(InputSize, InputSize), 0, 0, InterpolationFlags.Linear);

            Mat fed = _resizedBuffer;
            if (isRightEye)
            {
                Cv2.Flip(_resizedBuffer, _flippedBuffer, FlipMode.Y);
                fed = _flippedBuffer;
            }

            FillInputBufferFromBgr(fed, _inputBuffer, _byteBuffer);

            var inputTensor = new DenseTensor<float>(_inputBuffer, new[] { 1, InputSize, InputSize, 3 });
            using var results = _session.Run(new[] { NamedOnnxValue.CreateFromTensor(_inputName, inputTensor) });

            // Iris output: 5×3 = 15 floats. Eye contour: 71×3 = 213 floats.
            Tensor<float>? irisT = null;
            Tensor<float>? eyeT = null;
            foreach (var r in results)
            {
                var t = r.AsTensor<float>();
                long len = 1;
                foreach (var d in t.Dimensions) len *= d;
                if (len == NumIrisPoints * LandmarkDims) irisT = t;
                else if (len == NumEyeContour * LandmarkDims) eyeT = t;
            }
            if (irisT == null || eyeT == null) return null;

            float invInput = 1f / InputSize;

            // Iris center is point 0 (IrisIndex.CENTER in IntelliProve constants).
            var iris = irisT.ToArray();
            float ix64 = iris[0];
            float iy64 = iris[1];
            if (isRightEye) ix64 = InputSize - ix64;
            double irisX = rx + (ix64 * invInput) * rs;
            double irisY = ry + (iy64 * invInput) * rs;

            // Eye contour 71 points → source-frame pixel coords.
            var eye = eyeT.ToArray();
            var contour = new float[NumEyeContour][];
            for (int i = 0; i < NumEyeContour; i++)
            {
                float ex64 = eye[i * LandmarkDims + 0];
                float ey64 = eye[i * LandmarkDims + 1];
                if (isRightEye) ex64 = InputSize - ex64;
                contour[i] = new[] { rx + (ex64 * invInput) * rs, ry + (ey64 * invInput) * rs };
            }

            return new EyeLandmarks { IrisCenter = (irisX, irisY), Contour = contour };
        }

        private static void FillInputBufferFromBgr(Mat bgr64, float[] dst, byte[] bytes)
        {
            if (bgr64.Width != InputSize || bgr64.Height != InputSize || bgr64.Type() != MatType.CV_8UC3)
                throw new InvalidOperationException("IrisDetector.FillInputBufferFromBgr: expected 64×64 CV_8UC3");

            int total = InputSize * InputSize;
            System.Runtime.InteropServices.Marshal.Copy(bgr64.Data, bytes, 0, total * 3);
            const float kScale = 1f / 255f;
            for (int i = 0; i < total; i++)
            {
                dst[3 * i + 0] = bytes[3 * i + 2] * kScale; // R
                dst[3 * i + 1] = bytes[3 * i + 1] * kScale; // G
                dst[3 * i + 2] = bytes[3 * i + 0] * kScale; // B
            }
        }

        public void Dispose()
        {
            try { _session.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _croppedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _resizedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            try { _flippedBuffer?.Dispose(); } catch (Exception ex) { Diag.Swallowed(ex); }
            _croppedBuffer = null;
            _resizedBuffer = null;
            _flippedBuffer = null;
        }
    }
}
